### ISSUE TITLE
The service port name restriction should be removed 

### ISSUE THREAD

**Issue by 18664599806** [kubeedge/edgemesh#105]
**What would you like to be added/modified**:
In current edgemesh version , the service port name has the following restriction: "Service ports must be named. The key/value pairs of port name must have the following syntax: name: <protocol>[-<suffix>]"

The restriction should be removed.

**Why is this needed**:
This problem is easily triggered. As a result, services cannot be accessed accross cloud and edge.

**Comment by Poorunga** [comment]
fix in pr #175
