### ISSUE TITLE
After edge node install edgemesh-agent, access to public network becomes very slow!

### ISSUE THREAD

**Issue by 844700118** [kubeedge/edgemesh#114]
**After edge node install edgemesh-agent, access to public network becomes very slow!**

EdgeMesh version: release-1.8

Kubernetes version (use kubectl version): 1.19

KubeEdge version(e.g. cloudcore --version and edgecore --version): 1.8

**1. edge node**
  [root@localhost ~]#  time curl https://www.baidu.com

    <html> <head>......</head> </html>
	real    0m5.667s
	user    0m0.051s
	sys     0m0.077s
    
    [root@localhost ~]#  cat /etc/resolv.conf
	nameserver 172.17.0.1
	nameserver 223.5.5.5
	nameserver 114.114.114.114

	[root@localhost ~]#  curl http://nginx1.default.svc.cluster.local:8001
	<html> <head>......</head> </html>
	real    0m0.012s
	user    0m0.002s
	sys     0m0.007s

**2. How to configure listenInterface and subNet ?**

    After edge node install edgemesh-agent, access to public network becomes very slow, it takes more than 5 seconds !
	Everything else is normal, If you delete dns 172.17.0.1 in /etc/resolv.conf, access to the public network will recover faster.

**Comment by 844700118** [comment]
> /assign
> 
> Would you like to print edgemesh log for us, use command: `docker logs -f <edgemesh-container-id>`


kubectl logs -f -n kubeedge edgemesh-agent-edge-98c4s
**service reverse clusterIP error: service "www" not found**
日志里报上面这个错误

**Comment by Poorunga** [comment]
EdgeMesh DNS module cannot be resolved or is handed over to the host for resolution. By the way, can you copy the complete log?

**Comment by 844700118** [comment]
[root@kubeedge-129 kubeedge_bak]#  curl www.baidu.com
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
<!DOCTYPE html>
<!--STATUS OK--><html> <head><meta http-equiv=content-type content=text/html;charset=utf-8><meta http-equiv=X-UA-Compatible content=IE=Edge><meta content=always name=referrer><link rel=stylesheet type=text/css href=http://s1.bdstatic.com/r/www/cache/bdorz/baidu.min.css><title>百度一下，你就知道</title></head> <body link=#0000cc> <div id=wrapper> <div id=head> <div class=head_wrapper> <div class=s_form> <div class=s_form_wrapper> <div id=lg> <img hidefocus=true src=//www.baidu.com/img/bd_logo1.png width=270 height=129> </div> <form id=form name=f action=//www.baidu.com/s class=fm> <input type=hidden name=bdorz_come value=1> <input type=hidden name=ie value=utf-8> <input type=hidden name=f value=8> <input type=hidden name=rsv_bp value=1> <input type=hidden name=rsv_idx value=1> <input type=hidden name=tn value=baidu><span class="bg s_ipt_wr"><input id=kw name=wd class=s_ipt value maxlength=255 autocomplete=off autofocus></span><span class="bg s_btn_wr"><input type=submit id=su value=百度一下 class="bg s_btn"></span> </form> </div> </div> <div id=u1> <a href=http://news.baidu.com name=tj_trnews class=mnav>新闻</a> <a href=http://www.hao123.com name=tj_trhao123 class=mnav>hao123</a> <a href=http://map.baidu.com name=tj_trmap class=mnav>地图</a> <a href=http://v.baidu.com name=tj_trvideo class=mnav>视频</a> <a href=http://tieba.baidu.com name=tj_trtieba class=mnav>贴吧</a> <noscript> <a href=http://www.baidu.com/bdorz/login.gif?login&amp;tpl=mn&amp;u=http%3A%2F%2Fwww.baidu.com%2f%3fbdorz_come%3d1 name=tj_login class=lb>登录</a> </noscript> <script>document.write('<a href="http://www.baidu.com/bdorz/login.gif?login&tpl=mn&u='+ encodeURIComponent(window.location.href+ (window.location.search === "" ? "?" : "&")+ "bdorz_come=1")+ '" name="tj_login" class="lb">登录</a>');</script> <a href=//www.baidu.com/more/ name=tj_briicon class=bri style="display: block;">更多产品</a> </div> </div> </div> <div id=ftCon> <div id=ftConw> <p id=lh> <a href=http://home.baidu.com>关于百度</a> <a href=http://ir.baidu.com>About Baidu</a> </p> <p id=cp>&copy;2017&nbsp;Baidu&nbsp;<a href=http://www.baidu.com/duty/>使用百度前必读</a>&nbsp; <a href=http://jianyi.baidu.com/ class=cp-feedback>意见反馈</a>&nbsp;京ICP证030173号&nbsp; <img src=//www.baidu.com/img/gs.gif> </p> </div> </div> </div> </body> </html>

[root@k8s-master ~]# kubectl logs -f -n kubeedge edgemesh-agent-edge-qqw29   

2021/10/09 01:24:33 INFO: Install client plugin, protocol: rest
2021/10/09 01:24:33 INFO: Installed service discovery plugin: edge
I1009 01:24:33.206361       1 server.go:54] Version: 1.8.0-dirty
I1009 01:24:33.206400       1 server.go:88] [1] New informers manager
I1009 01:24:33.207054       1 server.go:95] [2] Register beehive modules
I1009 01:24:33.207816       1 module.go:34] Module edgedns registered successfully
I1009 01:24:33.711520       1 module.go:34] Module edgeproxy registered successfully
W1009 01:24:33.711539       1 module.go:37] Module edgegateway is disabled, do not register
I1009 01:24:33.725960       1 privkey.go:40] Private key exist, skip generate
I1009 01:24:33.812800       1 module.go:34] Module tunnelagent registered successfully
I1009 01:24:33.812853       1 server.go:104] [3] Install go-chassis plugins
I1009 01:24:33.813012       1 log.go:181] DEBUG: Installed strategy plugin: [RoundRobin].
I1009 01:24:33.813030       1 log.go:181] DEBUG: Installed strategy plugin: [Random].
I1009 01:24:33.813040       1 log.go:181] DEBUG: Installed strategy plugin: [ConsistentHash].
I1009 01:24:33.813066       1 log.go:181] DEBUG: ConfigurationFactory Initiated
I1009 01:24:33.813084       1 log.go:181] INFO: Configuration files: []
I1009 01:24:33.813114       1 log.go:181] WARN: empty configurtion from [FileSource]
I1009 01:24:33.813124       1 log.go:181] INFO: invoke dynamic handler:FileSource
I1009 01:24:33.813166       1 log.go:181] INFO: archaius init success
I1009 01:24:33.813174       1 server.go:109] [4] Start informers manager
I1009 01:24:33.816202       1 log.go:181] INFO: create new watcher
I1009 01:24:34.115095       1 server.go:113] [5] Start all modules
I1009 01:24:34.115273       1 core.go:24] Starting module edgedns
I1009 01:24:34.115320       1 core.go:24] Starting module edgeproxy
I1009 01:24:34.115352       1 core.go:24] Starting module tunnelagent
W1009 01:24:34.117814       1 tunnel.go:28] Connection between agent and server [/ip4/192.168.1.228/tcp/10004 /ip4/127.0.0.1/tcp/10004 /ip4/192.168.1.228/tcp/10004] is not established, try connect
I1009 01:24:34.117851       1 tunnel.go:31] Tunnel agent connecting to tunnel server
I1009 01:24:34.204821       1 tunnel.go:50] agent success connected to server [/ip4/192.168.1.228/tcp/10004 /ip4/127.0.0.1/tcp/10004 /ip4/192.168.1.228/tcp/10004]
E1009 01:24:58.779268       1 dns.go:70] service reverse clusterIP error: service "www" not found

**Comment by 844700118** [comment]
**1.cloud node**

	[root@k8s-master ~]#  cat /etc/resolv.conf
		nameserver 10.1.235.192
		nameserver 223.5.5.5
		nameserver 114.114.114.114

	[root@k8s-master ~]# route
		Kernel IP routing table
		Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
		default         192.168.1.1     0.0.0.0         UG    100    0        0 ens192
		10.1.235.192    0.0.0.0         255.255.255.192 U     0      0        0 *
		10.1.235.193    0.0.0.0         255.255.255.255 UH    0      0        0 calid431889f8cb
		10.1.235.195    0.0.0.0         255.255.255.255 UH    0      0        0 cali994c0794b56
		10.1.235.203    0.0.0.0         255.255.255.255 UH    0      0        0 cali3a862295657
		10.1.235.204    0.0.0.0         255.255.255.255 UH    0      0        0 calic1561f3b5d0
		172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
		192.168.1.0     0.0.0.0         255.255.255.0   U     100    0        0 ens192

	[root@k8s-master ~]# dig www.baidu.com
		; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.7 <<>> www.baidu.com
		;; global options: +cmd
		;; Got answer:
		;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12198
		;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

		;; QUESTION SECTION:
		;www.baidu.com.                 IN      A

		;; ANSWER SECTION:
		www.baidu.com.          33      IN      CNAME   www.a.shifen.com.
		www.a.shifen.com.       33      IN      A       14.215.177.38
		www.a.shifen.com.       33      IN      A       14.215.177.39

		;; Query time: 6 msec
		;; SERVER: 223.5.5.5#53(223.5.5.5)
		;; WHEN: Sun Oct 10 13:14:40 CST 2021
		;; MSG SIZE  rcvd: 90

	[root@k8s-master ~]# nslookup www.baidu.com
		Server:         223.5.5.5
		Address:        223.5.5.5#53

		Non-authoritative answer:
		www.baidu.com   canonical name = www.a.shifen.com.
		Name:   www.a.shifen.com
		Address: 14.215.177.39
		Name:   www.a.shifen.com
		Address: 14.215.177.38


**2.edge node**

	[root@kubeedge-129 ~]#  cat /etc/resolv.conf
		nameserver 172.17.0.1
		nameserver 223.5.5.5
		nameserver 114.114.114.114

	[root@kubeedge-129 ~]#  route
		Kernel IP routing table
		Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
		default         gateway         0.0.0.0         UG    0      0        0 ens192
		link-local      0.0.0.0         255.255.0.0     U     1002   0        0 ens192
		172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
		192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 ens192
	
	[root@kubeedge-129 ~]# dig www.baidu.com
		; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.7 <<>> www.baidu.com
		;; global options: +cmd
		;; Got answer:
		;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32371
		;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

		;; QUESTION SECTION:
		;www.baidu.com.                 IN      A

		;; ANSWER SECTION:
		www.baidu.com.          24      IN      CNAME   www.a.shifen.com.
		www.a.shifen.com.       24      IN      A       14.215.177.39
		www.a.shifen.com.       24      IN      A       14.215.177.38

		;; Query time: 3 msec
		;; SERVER: 223.5.5.5#53(223.5.5.5)
		;; WHEN: Sun Oct 10 12:59:26 CST 2021
		;; MSG SIZE  rcvd: 90

	[root@kubeedge-129 ~]# nslookup www.baidu.com
		Server:         223.5.5.5
		Address:        223.5.5.5#53

		Non-authoritative answer:
		www.baidu.com   canonical name = www.a.shifen.com.
		Name:   www.a.shifen.com
		Address: 14.215.177.38
		Name:   www.a.shifen.com
		Address: 14.215.177.39

**3.my question**

        After installing the edgemesh agent on the edge/cloud node, dns 10.1.235.192 or 172.17.0.1 
        will be automatically added to /etc/resolv.conf, and access to the external network will slow down, 
        with a delay of about 5 seconds.

**Comment by Poorunga** [comment]
EdgeMesh DNS module cannot be resolved or is handed over to the host for resolution.

**Comment by 93425129** [comment]
We use mesh just want to find the service in cluster, when the outside of cluster, such as our external domain, the private harbor repo, we want to forward the /etc/hosts or upstream dns.
But the dns module in the edgemesh-agent can not lookup the external domain's ip, or forward to other dns.
just try twice, used 10s,  logs like this:
E1117 07:19:21.323516       1 dns.go:70] service reverse clusterIP error: service "harbor" not found
after failed, and jump to the next dns. So it's slow.

Please fix this issue quickly!

**Comment by Poorunga** [comment]
@93425129  OK we are fixing this problem

**Comment by Poorunga** [comment]
bug fixed in PR #245
