### ISSUE TITLE
coredns in edge node fail , unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST 

### ISSUE THREAD

**Issue by 844700118** [kubeedge/edgemesh#116]
EdgeMesh version: release-1.8

Kubernetes version (use kubectl version): 1.19

KubeEdge version(e.g. cloudcore --version and edgecore --version): 1.8

**coredns in edge node fail !**

    [root@k8s-master edgemesh-1.8.0]#    kubectl logs -n kube-system  coredns-6c76c8bb89-trblr
	  plugin/kubernetes: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
  
    [root@k8s-master edgemesh-1.8.0]# kubectl get pod -A -o wide
      NAMESPACE     NAME                                      READY   STATUS       RESTARTS   AGE    IP              NODE           NOMINATED NODE   READINESS GATES
	  default       busybox-sleep-cloud                       1/1     Running      0          55m    10.1.235.204    k8s-master     <none>           <none>
	  default       busybox-sleep-edge                        1/1     Running      0          55m    172.17.0.5      kubeedge-129   <none>           <none>
	  default       nginx1-b97c459f7-s6t7w                    1/1     Running      0          24h    172.17.0.3      kubeedge-129   <none>           <none>
	  default       nginx2-5fc4444698-4rgtj                   1/1     Running      0          24h    172.17.0.4      kubeedge-129   <none>           <none>
	  default       tcp-echo-cloud                            1/1     Running      0          55m    10.1.235.203    k8s-master     <none>           <none>
	  default       tcp-echo-edge                             1/1     Running      0          55m    172.17.0.2      kubeedge-129   <none>           <none>
	  kube-system   calico-kube-controllers-bcc6f659f-z4s89   1/1     Running      0          19m    10.1.235.193    k8s-master     <none>           <none>
	  kube-system   calico-node-kfnrd                         1/1     Running      0          19m    192.168.1.228   k8s-master     <none>           <none>
	  kube-system   calico-node-zp7r4                         0/1     Init:Error   8          19m    192.168.1.81    kubeedge-129   <none>           <none>
	  kube-system   coredns-6c76c8bb89-nl72n                  1/1     Running      0          31m    10.1.235.206    k8s-master     <none>           <none>
	  kube-system   coredns-6c76c8bb89-xmbb6                  0/1     Error        1          31s    172.17.0.7      kubeedge-129   <none>           <none>
	  kube-system   etcd-k8s-master                           1/1     Running      0          2d2h   192.168.1.228   k8s-master     <none>           <none>
	  kube-system   kube-apiserver-k8s-master                 1/1     Running      0          2d2h   192.168.1.228   k8s-master     <none>           <none>
	  kube-system   kube-controller-manager-k8s-master        1/1     Running      0          2d2h   192.168.1.228   k8s-master     <none>           <none>
	  kube-system   kube-proxy-74jbw                          1/1     Running      0          2d2h   192.168.1.228   k8s-master     <none>           <none>
	  kube-system   kube-proxy-g7l4t                          1/1     Running      0          42h    192.168.1.81    kubeedge-129   <none>           <none>
	  kube-system   kube-scheduler-k8s-master                 1/1     Running      0          2d2h   192.168.1.228   k8s-master     <none>           <none>
	  kubeedge      edgemesh-agent-edge-j4kp8                 1/1     Running      0          38m    192.168.1.81    kubeedge-129   <none>           <none>
	  kubeedge      edgemesh-server-5f4d8b8b5b-jt9qm          1/1     Running      0          28h    192.168.1.228   k8s-master     <none>           <none>

**Comment by Poorunga** [comment]
Maybe you can configure the node affinity of codedns so that they do not schedule to edge nodes.
