### ISSUE TITLE
via relay forwarding or holes punch fail

### ISSUE THREAD

**Issue by 844700118** [kubeedge/edgemesh#125]
EdgeMesh version: release-1.8
Kubernetes version (use kubectl version): 1.19
KubeEdge version(e.g. cloudcore --version and edgecore --version): 1.8
cloud node 
	ip: 192.168.1.228
	0.0.0.0:10004   edgemesh-serv 
	0.0.0.0:10006   edgemesh-agent
	
cloud edge 
	ip: 192.168.1.81
	0.0.0.0:10006   edgemesh-agent

**1.my issues**

	cloud access edge is normal, 
	cloud access edge is cloud, 
	edge access edge is normal, 
	but edge access cloud is abnormal.
	The correct communication link: edge node(172.17.0.1:14499) --> edgemesh-agent(172.17.0.1:10006) --> edgemesh-server(192.168.1.228:10004) --> edgemesh-agent(192.168. 1.228:10006) --> tcp-echo-cloud-svc(10.1.146.68)
    but my edge node communication link: edge node --> edgemesh-agent(192.168.1.81:37293) --> tcp-echo-cloud-svc(10.1.146.68)
	Why is this, and where is the configuration problematic?

**2.cloud node**

	[root@kubeedge-129 ~]#  vi /etc/kubeedge/config/cloudcore.yaml
		modules:
		  cloudHub:
			advertiseAddress:
			- 192.168.1.228
			https:
			  address: 0.0.0.0
			  enable: true
			  port: 10002
			quic:
			  address: 0.0.0.0
			  enable: false
			  port: 10001
			websocket:
			  address: 0.0.0.0
			  enable: true
			  port: 10000
		  cloudStream:
			enable: true
			streamPort: 10003
			tunnelPort: 20004
		  dynamicController:
			enable: true

	[root@k8s-master ~]# kubectl get pod -A -o wide
		NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE   IP               NODE           NOMINATED NODE   READINESS GATES
		default       tcp-echo-cloud-6f74565b6c-92nlx           1/1     Running   0          18h   10.233.235.206   k8s-master     <none>           <none>
		default       tcp-echo-edge-6f54447cb-65fzr             1/1     Running   0          18h   172.17.0.5       kubeedge-129   <none>           <none>
		kube-system   calico-kube-controllers-bcc6f659f-7dsw6   1/1     Running   0          46h   10.233.235.195   k8s-master     <none>           <none>
		kube-system   calico-node-w6tq7                         1/1     Running   0          46h   192.168.1.228    k8s-master     <none>           <none>
		kube-system   coredns-565fc5c9d8-qlg92                  1/1     Running   0          42h   10.233.235.202   k8s-master     <none>           <none>
		kube-system   kube-proxy-v9gv7                          1/1     Running   1          44h   192.168.1.81     kubeedge-129   <none>           <none>
		kube-system   kube-proxy-wwkn5                          1/1     Running   0          44h   192.168.1.228    k8s-master     <none>           <none>
		kubeedge      edgemesh-agent-cloud-tlwtz                1/1     Running   0          18h   192.168.1.228    k8s-master     <none>           <none>
		kubeedge      edgemesh-agent-edge-rp4vz                 1/1     Running   0          18h   192.168.1.81     kubeedge-129   <none>           <none>
		kubeedge      edgemesh-server-5f4d8b8b5b-pmpqx          1/1     Running   5          19h   192.168.1.228    k8s-master     <none>           <none>

	[root@k8s-master ~]# kubectl get svc -A
		NAMESPACE     NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
		default       kubernetes           ClusterIP   10.1.0.1       <none>        443/TCP                  46h
		default       tcp-echo-cloud-svc   ClusterIP   10.1.146.68    <none>        2701/TCP                 41h
		default       tcp-echo-edge-svc    ClusterIP   10.1.65.64     <none>        2701/TCP                 45h
		kube-system   kube-dns             ClusterIP   10.1.0.10      <none>        53/UDP,53/TCP,9153/TCP   46h

**3.edge access cloud fail**

	[root@kubeedge-129 ~]#  cat /etc/kubeedge/config/edgecore.yaml
		modules:
		  edgeHub:
			enable: true
			httpServer: https://192.168.1.228:10002
			quic:
			  enable: false
			  server: 192.168.1.228:10001
			websocket:
			  enable: true
			  server: 192.168.1.228:10000
		  edgeStream:
			enable: true
			server: 192.168.1.228:20003
		  edgeMesh:
			enable: false
		  edged:
			hostnameOverride: kubeedge-129
			nodeIP: 192.168.1.81
		  metaManager:
			metaServer:
			  debug: false
			  enable: true
		  serviceBus:
			enable: false

	[root@kubeedge-129 ~]#  telnet tcp-echo-cloud-svc.default.svc.cluster.local 2701
		Trying 10.1.146.68...
		telnet: connect to address 10.1.146.68: Connection timed out

	[root@kubeedge-129 ~]# tcpdump -i any -s 0 tcp port 2701 -n -nn -tttt -l 
		11:44:20.006061 IP 192.168.1.81.27211 > 10.233.235.206.2701: Flags [S], seq 333152774, win 29200, options [mss 1460,sackOK,TS val 1372992106 ecr 0,nop,wscale 7], length 0
		192.168.1.81	10.233.235.206	TCP	76	[TCP Retransmission] 2721→2701 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=1285279592 TSecr=0 WS=128

**4.edge access edge success**

	[root@kubeedge-129 ~]# telnet tcp-echo-edge-svc.default.svc.cluster.local 2701
		Trying 10.1.65.64...
		Connected to tcp-echo-edge-svc.default.svc.cluster.local.
		Escape character is '^]'.
		Welcome, you are connected to node kubeedge-129.
		Running on Pod tcp-echo-edge-6f54447cb-fntpr.
		In namespace default.
		With IP address 172.17.0.2.
		Service default.

	[root@kubeedge-129 ~]# tcpdump -i any -s 0 dst port 2701 -n -nn 
		10:53:14.179112 IP 172.17.0.1.9865 > 172.17.0.5.2701: Flags [S], seq 2611685187, win 29200, options [mss 1460,sackOK,TS val 1369926279 ecr 0,nop,wscale 7], length 0

**Comment by Poorunga** [comment]
edgemesh使用libp2p技术进行数据传输：
在两个应用进行通信的时候，edgemesh-agent会尝试使用libp2p进行NAT打洞。打洞成功时两个edgemesh-agent建立直连，打洞失败时，使用edgemesh-server做中继服务器转发流量，保障应用间的通信不断。

打洞成功的流量路径： 应用A -> edgemesh-agent-A -> edgemesh-agent-B -> 应用B
打洞失败的流量路径： 应用A -> edgemesh-agent-A -> edgemesh-server -> edgemesh-agent-B -> 应用B

打洞成功率受到NAT设备影响：
锥形：
 - 完全锥形NAT
 - 限制锥形NAT
 - 端口限制锥形NAT
对称型：
 - 对称NAT
 **（从上到下：穿透性下降，安全性上升）**

**Comment by 844700118** [comment]
edge node(172.17.0.1:14499) --> edgemesh-agent(172.17.0.1:10006) --> edgemesh-agent(192.168. 1.228:10006) --> tcp-echo-cloud-svc(10.1.146.68)
如果能这样通信, 也行啊, 问题是现在  edge node(172.17.0.1:14499)  直连 --> tcp-echo-cloud-svc(10.1.146.68)

**Comment by Poorunga** [comment]
尝试自己编译代码和生成镜像。

make agentimage 可以快速生成一个edgmesh-agent镜像
