### ISSUE TITLE
create dummy device edgemesh0 err: operation not supported

### ISSUE THREAD

**Issue by davedavedavid** [kubeedge/edgemesh#163]
**What happened**:
kubeedge/edgemesh-agent run failed：
run edgemesh-agent failed: create dummy device edgemesh0 err: operation not supported
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
device：atlas500

uname -a
Linux a500-124 4.19.36-vhulk1907.1.0.h1017.eulerosv2r8.aarch64 #1 SMP Sat Mar 27 10:04:38 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

ip link add test0 type dummy 
RTNETLINK answers: Operation not supported

modprobe dummy
modprobe: FATAL: Module dummy not found in directory /lib/modules/4.19.36-vhulk1907.1.0.h1017.eulerosv2r8.aarch64
**Environment**:
- EdgeMesh version:10dada6234c7edbccfc5069abfa63da27c53788c
- Kubernetes version (use `kubectl version`):v1.21.3
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.8.2
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
/assign 

look like you OS can create dummy device

**Comment by davedavedavid** [comment]
kubeedge/edgemesh-agent running successful on A500
