### ISSUE TITLE
After add a new edge node,  the edge node can't access the service 

### ISSUE THREAD

**Issue by Icedroid** [kubeedge/edgemesh#17]
I have two edge node,  one node to curl  service is normal, But after I add another edge node it can't access service:
```
 #curl -v -X GET 'http://nginx.default'
* Could not resolve host: nginx.default; 未知的错误
* Closing connection 0
curl: (6) Could not resolve host: nginx.default; 未知的错误
#curl 127.0.0.1:10550/api/v1/services
{"apiVersion":"v1","items":[],"kind":"ServiceList","metadata":{"selfLink":"/api/v1/services"}}
```

After I restart cloudcore and edgecore, It is ok.

**Environment**:
- EdgeMesh version: v1.7.0
- Kubernetes version (use `kubectl version`): v1.16.1
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.7.0

**Comment by Poorunga** [comment]
Can you provide us with more information through `docker logs -f <edgemesh_container_id>`?

**Comment by Icedroid** [comment]
@Poorunga I have restrat cloudcore edgemesh, now the logs is gone. Next time I add new edge node may be it happen, you can reproduce for add a new  vm edge node.
