### ISSUE TITLE
edgemesh causes service connect failed

### ISSUE THREAD

**Issue by king-jingxiang** [kubeedge/edgemesh#173]
**What happened**:
deploy edgemesh, the edge svc connect successed.
```bash
$ kubectl get svc
NAME           TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
hostname-svc   ClusterIP   10.100.26.38   <none>        80/TCP    9m11s
kubernetes     ClusterIP   10.96.0.1      <none>        443/TCP   12d
$ kubectl get endpoints
NAME           ENDPOINTS        AGE
hostname-svc   172.17.0.3:80    9m18s
kubernetes     10.12.3.7:6443   12d
$ curl 10.100.26.38
<!DOCTYPE html>...
$ kubectl get cm edgemesh-agent-cfg -nkubeedge -oyaml
    modules:
      edgeProxy:
        enable: true
        listenPort: 40001
        subNet: 10.96.0.0/12
```
but, other svc connect failed
```bash
$ kubectl get svc -nkubesphere-system
NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
ks-apiserver            ClusterIP   10.100.185.141   <none>        80/TCP         12d
ks-console              NodePort    10.98.93.250     <none>        80:30009/TCP   12d
ks-controller-manager   ClusterIP   10.100.234.102   <none>        443/TCP        12d
$ curl 10.98.93.250
curl: (56) Recv failure: Connection reset by peer
$ kubectl get endpoints -nkubesphere-system -owide
NAME                    ENDPOINTS            AGE
ks-apiserver            10.244.124.31:9090   12d
ks-console              10.244.124.3:8000    12d
ks-controller-manager   10.244.124.32:8443   12d
$ curl 10.244.124.3:8000
Redirecting to <a href="/login">/login</a>.
```
uninstall edgemesh, other svc connect successed
```bash
$ curl 10.98.93.250
Redirecting to <a href="/login">/login</a>.
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version:
```
KubeEdge v0.0.0-master+$Format:%h$
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
```
KubeEdge v1.8.2
```
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by king-jingxiang** [comment]
the reason is `proxy.go:68` split unreasonable, please fix it.
```go
func getSvcPorts(svc *v1.Service) string {
	svcPorts := ""
	svcName := svc.Namespace + "." + svc.Name
	for _, p := range svc.Spec.Ports {
		pro := strings.Split(p.Name, "-")
		sub := fmt.Sprintf("%s,%d,%d|", pro[0], p.Port, p.TargetPort.IntVal)
		svcPorts = svcPorts + sub
	}
	svcPorts += svcName
	return svcPorts
}
```
the svc spec is
```yaml
spec:
  clusterIP: 10.98.93.250
  clusterIPs:
  - 10.98.93.250
  ports:
  - name: nginx
    nodePort: 30009
    port: 80
    protocol: TCP
    targetPort: 8000
```
the edgemesh agent error logs
```
I1109 12:24:11.473400       1 proxy.go:37] clusterIP: 10.98.93.250, servicePort: 80
W1109 12:14:37.103060       1 proxy.go:45] get protocol from sock error: protocol: nginx is not supported yet
```
when change svc spec ports name is `tcp-nginx`, the connect successed.

**Comment by khalid-jobs** [comment]
Because the `protocol` only supports `tcp`, `udp` and  `sctp`, but edgemesh needs to support `http` and other application protocol. So we follow the istio's rule [link](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection), and may be we can use `appProtocol` to do the things, but it need the kubernetes' version is 1.18+

**Comment by king-jingxiang** [comment]
1、`http`、`https`或其它的协议都当做普通的tcp流量处理不可以吗？我这边修改了一下代码测试目前好像没什么问题，而通过name获取protocol会有一些问题，比如operator生成的`service.spec.port.name`，不符合`protocol-name`的命名规范就会通信受限。
2、有没有什么方式可以设置部分svc流量通过`edgemesh`转发，比如云边和边边通信的流量，部分svc流量还是通过k8s默认的走`iptables`，比如云端集群内服务互访的流量。

**Comment by khalid-jobs** [comment]
1. Maybe we can try to fetch the protocol from the name, and if we fail , then we fetch the value from `protocol`. The protocol has a default value `TCP`.
2. For the second question, you can try to use [Hybrid-NAT](https://edgemesh.netlify.app/advanced/hybirdnat.html)

**Comment by khalid-jobs** [comment]
And the reason we support application layer protocol (such as `http` protocol) is that we want to support more feature for the traffic, such as load balance strategy for application layer protocol.

**Comment by king-jingxiang** [comment]
I get it, thanks.

**Comment by khalid-jobs** [comment]
And would you like to pull a request for the protocol  fetching logic?

**Comment by king-jingxiang** [comment]
ok, let me pull a request to fix it.

**Comment by king-jingxiang** [comment]
And the `Hybrid-NAT` `noproxy: edgemesh` label have considered change to `proxy: edgemesh`. Only used to set up service that need to use edgemesh?

**Comment by khalid-jobs** [comment]
Actually, the edgemesh  as the data plane component of the KubeEdge cluster, we think that the default proxy software should be edgemesh in kubeedge cluster.

**Comment by king-jingxiang** [comment]
还有一个问题是`iptables.go:194`,这里赋值是一个指针类型，这么赋值有问题，会修改之前插入的数据，现象就是插入iptables表数据丢失，我就在这个pr里面一起修改了啊。
```go
	// Other services we want to ignore(which service has noproxy=edgemesh label)...
	otherIgnoreServiceList, err := proxier.kubeClient.CoreV1().Services("").List(context.Background(), metav1.ListOptions{LabelSelector: labelNoProxy})
	if err != nil && !util.IsNotFoundError(err) {
		klog.Warningf("failed to list service labeled with noproxy=edgemesh, err: %v", err)
	} else if err == nil {
		for _, item := range otherIgnoreServiceList.Items {
			klog.V(4).Infof("ignored containing noproxy=edgemesh label service: %s", item.Name)
			ignoreRulesIptablesEnsureMap[strings.Join([]string{item.Namespace, item.Name}, ".")] = &item
		}
	}
```
edgemesh-agent logs
```
I1111 06:18:11.840371       1 iptables.go:281] ignore rules: [
{nat RETURN EDGE-MESH ignore weave/weave-scope-app service [-d 10.110.96.38/32]} 
{nat RETURN EDGE-MESH ignore default/kubernetes service [-d 10.96.0.1/32]} 
{nat RETURN EDGE-MESH ignore kube-system/kube-dns service [-d 10.96.0.10/32]} 
{nat RETURN EDGE-MESH ignore weave/weave-scope-app service [-d 10.110.96.38/32]} 
{nat RETURN EDGE-MESH ignore weave/weave-scope-app service [-d 10.110.96.38/32]} 
{nat RETURN EDGE-MESH ignore weave/weave-scope-app service [-d 10.110.96.38/32]} 
{nat RETURN EDGE-MESH ignore weave/weave-scope-app service [-d 10.110.96.38/32]}]
```

**Comment by king-jingxiang** [comment]
还有Kubeedge部署在k8s之上，edgemesh作为默认的数据通道会对集群内其它服务造成影响，在大多数情况下通常是一个k8s集群，而不是多集群的方案，集群内会有很多的云上业务，如果使用edgemesh，则云上业务都需要修改，添加noproxy=edgemesh的label，可能但大多数情况下不愿意这么处理，我觉得kube-proxy依然应当作为svc默认的数据通道，使用edgemesh可以通过label的方式开启。这个是否可以考虑一下。

**Comment by king-jingxiang** [comment]
再补充一个问题，如何k8s部署时使用的是ipvs，edgemesh是否还可以正常工作

**Comment by Poorunga** [comment]
> 再补充一个问题，如何k8s部署时使用的是ipvs，edgemesh是否还可以正常工作

这个与iptables和ipvs的优先级有关系，我们暂时还没有测试过。等测试过后会告知您

**Comment by Poorunga** [comment]
> 可能但大多数情况下不愿意这么处理，我觉得kube-proxy依然应当作为svc默认的数据通道，使用edgemesh可以通过label的方式开启

这确实是一个有争议的话题。有些用户具有大量只跑在边缘上的应用，他们只使用edgemesh做应用间的通信（他们并不想在仅有一点点内存的边缘节点上部署kube-proxy和cni，因为很浪费资源 部署也很麻烦，他们只需要边缘应用能够简单的通信，所以他们选择了edgemesh）。在这种情况下，如果按你所说的，那么他们边上所有的业务都要修改，他们也不太愿意。

@yz271544 作为此特性的owner，您有什么看法呢？

**Comment by koulq** [comment]
> 

你好，我这边也遇到类似的问题，edgemesh能否添加一个这样的配置，让使用者选择，对于云上业务多的，默认走云上的coredns和kube-proxy，对于边缘业务多的默认走edgemesh。

**Comment by Poorunga** [comment]
@koulq 目前edgemesh-agent的DNS配置，默认在云上关闭，走云上coredns；默认在边缘开启，走edgemesh自己的dns。见：https://edgemesh.netlify.app/zh/reference/config-items.html#%E8%A1%A81-4-1-edgedns

 edgemesh支持使用service的label过滤不走edgemesh代理。见：https://edgemesh.netlify.app/zh/advanced/hybirdnat.html#%E7%9B%AE%E6%A0%87

**Comment by koulq** [comment]
> @koulq 目前edgemesh-agent的DNS配置，默认在云上关闭，走云上coredns；默认在边缘开启，走edgemesh自己的dns。见：https://edgemesh.netlify.app/zh/reference/config-items.html#%E8%A1%A81-4-1-edgedns
> 
> edgemesh支持使用service的label过滤不走edgemesh代理。见：https://edgemesh.netlify.app/zh/advanced/hybirdnat.html#%E7%9B%AE%E6%A0%87

@Poorunga 你好，这两个配置我都知晓，我的意思是：1、关掉了云上的DNS配置，就无法实现跨边云了；2，通过label忽略一些service不走edgemesh，这个执行起来了稍微有点麻烦，因为对于部署云上业务和kubeedge共享一个集群的场景，云上业务都是已经部署好的，在进行修改有些不合适。有木有更好的解决办法，对于需要跨云边、边边访问的service走edgemesh（使用标签），默认的不走edgemesh
