### ISSUE TITLE
Can't run edgemesh without deploying flannel/calico ahead

### ISSUE THREAD

**Issue by zyliu0402** [kubeedge/edgemesh#176]
**What happened**: In the introduction, edgemesh is introduced as a replacement of other cni plugin like flannel or calico. However, during edgemesh deployment, the coredns modules are always showing wrong STATUS - "ContainerCreating", which is result of can't find the correct conf file. Now, to deploy edgemesh successfully,  after “_kubeadm init_”，I firstly "kubectl apply -f flannel.yaml" to install the flannel cni plugin and make coredns module running. Then, "_kubectl delete -f flannel.yaml_". Finally, follow the EdgeMesh installation document to install EdgeMesh.  So, the role of edgemesh confuses me in the whole installation. Or maybe there is someway to run coredns module with edgemesh?

**Environment**:
- EdgeMesh version:v1.8.1
- Kubernetes version (use `kubectl version`):v1.20.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`): X86_64
    - OS (e.g. `cat /etc/os-release`): Ubuntu18.04
    - Kernel (e.g. `uname -a`): amd64
    - Go version (e.g. `go version`): 1.16.9
    - Others:

  </details>

**Comment by khalid-jobs** [comment]
The edgemesh provides simple service discovery and traffic proxy functions for applications in edge computing cluster.  K8s requires that all nodes can access each other. On edge clusters, cloud nodes generally cannot directly access edge nodes, and CNI plugins cannot work. Edgemesh is to solve the application communication on the edge node. EdgeMesh will take care of the network which cni plugin(flannel) can not l take care of.

**Comment by zyliu0402** [comment]
So，we need flannel/calico to achieve the communicaion between cloud and edge , and need edgemesh to take care of the communication between edges?

**Comment by khalid-jobs** [comment]
The flannel/calico only can achive the communicatin between cloud node and cloud node. The edgemesh will take care of the communication between cloud and edge,  also between edge and edge

**Comment by zyliu0402** [comment]
But why only deploy edgemesh can not run the coredns modules?

**Comment by khalid-jobs** [comment]
What do you mean "But why only deploy edgemesh can not run the coredns modules" ?

**Comment by zyliu0402** [comment]
I have resolve this problem. Let me explain in more detail. As the kubeedge as well as edgemesh installation in github do not include the k8s deployment.,we need to follow other guides to install k8s before. When we install k8s, in "kubeadm init" procedure, the argument "--pod-network-cidr=10.244.0.0/16" should be follow as well (almost in every guides). This argument decides that the coredns modules should be initialized by flannel instead of edgemesh or other cni plugin. Thus, when I  "kubeadm init" without assign the the argument "--pod-network-cidr", the coredns module running automatically. And then I just need to install edgemesh to take care of the network.  In one word, I need to learn more about k8s and understand every command's meaning. Thanks a lot!

**Comment by khalid-jobs** [comment]
@zyliu0402 Do you have any problem with this issue? If not, you can close this issue.
