### ISSUE TITLE
Can we upgrade istio-related CRDs to a stable version like v1?

### ISSUE THREAD

**Issue by zhu733756** [kubeedge/edgemesh#179]
As mentioned in the title,  currently,  the istio-related CRDs in the helm package are  with unstable versions.

The istio official has supported v1 version, see 
https://github.com/istio/istio/blob/bd50200e9be9170d375d5843365eaf629afa77b0/manifests/charts/base/crds/crd-all.gen.yaml#L97

Since Kubernetes v1.22+, the APIs of the CRDs with an unstable version have been removed.  See https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes

**Comment by Poorunga** [comment]
/assign

ok

**Comment by zhu733756** [comment]
> /assign
> 
> ok

Thanks！
