### ISSUE TITLE
edgemesh-agent cannot  access to the K8s service created newly

### ISSUE THREAD

**Issue by davedavedavid** [kubeedge/edgemesh#181]
**What happened**:
![image](https://user-images.githubusercontent.com/87642892/141958762-41bf6c62-a3a1-4a6c-bba4-30626ff1e281.png)
![image](https://user-images.githubusercontent.com/87642892/141958907-17c02bcc-d7fe-4926-8c5d-32ee9973be22.png)
edgemesh-agent cannot  access the newly created service.
would recover if restart edgecore.
![image](https://user-images.githubusercontent.com/87642892/141959699-eee08e73-d835-4cb8-b788-f0f69d9b382f.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version:latest
- Kubernetes version (use `kubectl version`):v1.21.3
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.8.2
- <details><summary>Cloud nodes Environment:</summary>
- $ k edit svc/yolo-v5-aggregation：

apiVersion: v1
kind: Service

apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2021-11-16T11:14:21Z","labels":{"federatedlearningjob.sedna.io/name":"yolo-v5","federatedlearningjob.sedna.io/uid":"c1fe8446-cb32-4246-913d-40816ea297eb","federatedlearningjob.sedna.io/worker-type":"aggregation"},"name":"yolo-v5-aggregation","namespace":"default","ownerReferences":[{"apiVersion":"sedna.io/v1alpha1","blockOwnerDeletion":true,"controller":true,"kind":"FederatedLearningJob","name":"yolo-v5","uid":"c1fe8446-cb32-4246-913d-40816ea297eb"}],"resourceVersion":"8233981","uid":"f2af1f3d-9c38-4180-8c39-df85d8610a10"},"spec":{"clusterIP":"130.5.7.152","clusterIPs":["130.5.7.152"],"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"tcp-0","port":7363,"protocol":"TCP","targetPort":7363}],"selector":{"federatedlearningjob.sedna.io/name":"yolo-v5","federatedlearningjob.sedna.io/uid":"c1fe8446-cb32-4246-913d-40816ea297eb","federatedlearningjob.sedna.io/worker-type":"aggregation"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2021-11-16T11:32:19Z"
  labels:
    federatedlearningjob.sedna.io/name: yolo-v5
    federatedlearningjob.sedna.io/uid: c1fe8446-cb32-4246-913d-40816ea297eb
    federatedlearningjob.sedna.io/worker-type: aggregation
  name: yolo-v5-aggregation
  namespace: default
  ownerReferences:
  - apiVersion: sedna.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: FederatedLearningJob
    name: yolo-v5
    uid: c1fe8446-cb32-4246-913d-40816ea297eb
  resourceVersion: "8239197"
  uid: c0ec5c4c-9eb2-40ad-a9c8-ea1d37135223
spec:
  clusterIP: 130.5.7.152
  clusterIPs:
  - 130.5.7.152
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-0
    port: 7363
    protocol: TCP
    targetPort: 7363
  selector:
    federatedlearningjob.sedna.io/name: yolo-v5
    federatedlearningjob.sedna.io/uid: c1fe8446-cb32-4246-913d-40816ea297eb
    federatedlearningjob.sedna.io/worker-type: aggregation
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
Every time the service: yolo-v5-aggregation is modified, the domain name cannot be resolved(yolo-v5-aggregation not found) and clusterip cannot be resolved. Only yolo-v5-aggregation will appear.

**Comment by Poorunga** [comment]
/close

edgecore list-watch will receive a lot of delete service events cause: yolo-v5-aggregation not found
issue move to https://github.com/kubeedge/kubeedge/issues/3445
