### ISSUE TITLE
I deployed edgemesh according to the tutorial, but an error occurred

### ISSUE THREAD

**Issue by 916264367** [kubeedge/edgemesh#182]
**What happened**:
![image](https://user-images.githubusercontent.com/51771785/142092319-e723958c-a159-4159-8427-2b07edfcadaa.png)

**What you expected to happen**:
The tutorial tells me that I need to modify the values of "publicip" and "nodeName" tags in 05-configmap.yaml and 06-deployment.yaml.(build/server/edgemesh/)
V1.8.1 kubeedge can automatically identify the public IP, so I didn't modify 05-configmap.yaml.
I modified nodeName: cloud node, and the node name on the server side is 06-deployment.yaml
The server side node-name：
![image](https://user-images.githubusercontent.com/51771785/142093175-31760173-1a17-46b8-ab43-05df2773937f.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version:Latest version
- Kubernetes version (use `kubectl version`):v1.20.5
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):v1.8.1
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by khalid-jobs** [comment]
Can you paste the log of the `edgemesh-agent`? Try `docker logs -f <container-id>` in edge-node-1

**Comment by 916264367** [comment]
> 

hello. After I tried again and again, Now only one pod is running. Edgemesh-agent is missing
![image](https://user-images.githubusercontent.com/51771785/142966853-67a2b895-6143-4d27-9b68-d36dafbd731e.png)

**Comment by 916264367** [comment]
> /分配



> /分配
so the log cannot be found in the edge-node-1

**Comment by Poorunga** [comment]
use `kubectl get daemonset -n kubbedge` to see your edgemesh-agent DESIRE.

**Comment by 916264367** [comment]
> kubectl get daemonset -n kubbedge

![image](https://user-images.githubusercontent.com/51771785/142978459-d8afc85d-07d2-4306-adc4-17ac2a319db6.png)

**Comment by 916264367** [comment]
> 用于`kubectl get daemonset -n kubbedge`查看您的edgemesh-agent DESIRE。

What does this picture show

**Comment by Poorunga** [comment]
You can see edgemesh-agent DESIRED is 0.

See if you have configured node tolerance or taint.

https://kubernetes.io/zh/docs/concepts/scheduling-eviction/taint-and-toleration/

**Comment by 916264367** [comment]
> 您可以看到 edgemesh-agent DESIRED 为 0。
> 
> 查看您是否已配置节点容错或污点。
> 
> 可以参考https://kubernetes.io/zh/docs/concepts/scheduling-eviction/taint-and-toleration/

**Comment by 916264367** [comment]
> 您可以看到 edgemesh-agent DESIRED 为 0。
> 
> 查看您是否已配置节点容错或污点。
> 
> 可以参考https://kubernetes.io/zh/docs/concepts/scheduling-eviction/taint-and-toleration/

I changed the version of Kubeedge to 1.8.0 and it was resolved

**Comment by 916264367** [comment]
> 您可以看到 edgemesh-agent DESIRED 为 0。
> 
> 查看您是否已配置节点容错或污点。
> 
> 可以参考https://kubernetes.io/zh/docs/concepts/scheduling-eviction/taint-and-toleration/
![image](https://user-images.githubusercontent.com/51771785/142984216-b1bfc40e-019b-451b-b79d-4f7f670fa546.png)
I don’t know why, but thank you

**Comment by khalid-jobs** [comment]
so, if you use kubeedge 1.8.0, the edgemesh works fine, right?
