### ISSUE TITLE
There is an error when i deployed edgemesh according to the tutorial

### ISSUE THREAD

**Issue by dqzgkyh** [kubeedge/edgemesh#194]
**What happened**:

![图片](https://user-images.githubusercontent.com/58615473/142822266-803ae21e-469e-48c4-b495-6baa8fc8da74.png)

![图片](https://user-images.githubusercontent.com/58615473/142823910-5b2b20e5-767d-4ed7-9e84-a0323d2d13b7.png)
容器就没有日志；The container has no logs

**Anything else we need to know?**:

利用helm安装的，但是agent一直运行失败，并且对应的pod容器是没有日志的。也就是说，一运行就退出，没有任何有效的日志
Installed using helm, but the agent has been running failed, and the corresponding pod container has no logs. In other words, it exits as soon as it runs, without any valid logs

有效的设备有两个，一个是Ubuntu 18.04.5 LTS，另一个是Debian GNU/Linux 10 (buster)。我知道暂时没有arm32架构的镜像，所以就希望那两个arm64的可以运行，但是一直成功不了。
There are two effective devices, one is Ubuntu 18.04.5 LTS, and the other is Debian GNU/Linux 10 (buster). I know that there is no arm32 architecture mirroring for the time being, so I hope that the two arm64 can run, but it has been unable to succeed.
![图片](https://user-images.githubusercontent.com/58615473/142822994-160aa8d4-6599-4ca3-afb4-e0bac840f220.png)

另外手动部署也试过，这个镜像（kevindavis/edgemesh-agent:v1.8.0-arm64）可以运行，虽然会报错缺少环境变量（估计要和deployment配合），但是起码是有日志的；另外，如果是架构不兼容的话，会报另一个错（这个暂时复现不了...），所以我猜测也许是官方镜像有点问题。
In addition, I also tried manual deployment. This image (kevindavis/edgemesh-agent:v1.8.0-arm64) can run. Although it will report a lack of environment variables (estimated to cooperate with deployment), at least there is a log; in addition, if it is If the architecture is incompatible, another error will be reported (this cannot be reproduced temporarily...), so I guess there may be some problems with the official mirror.

**Environment**:
- EdgeMesh version: 1.8.0
- Kubernetes version (use `kubectl version`): v1.21.4
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): cloudcore : v1.8.2; edgecore : 1.8.2

**Comment by Poorunga** [comment]
> 一运行就退出，没有任何有效的日志

可以使用docker ps -a | grep edgemesh-agent获取容器id，再使用docker logs <edgemesh-agent-container-id>查看日志信息。（即使因Error而退出的容器，也是可以看日志的）

> 另外手动部署也试过，这个镜像（kevindavis/edgemesh-agent:v1.8.0-arm64）可以运行，虽然会报错缺少环境变量（估计要和deployment配合），但是起码是有日志的；另外，如果是架构不兼容的话，会报另一个错（这个暂时复现不了...），所以我猜测也许是官方镜像有点问题。

pr #184 已经支持多架构构建edgemesh镜像了，而且我们已经制作了arm64的镜像并上传至dockerhub仓库中。所以你只需要在你的arm64的设备上使用 docker pull kubeedge/edgemesh-agent:latest 就可以获得最新的arm64架构的edgemesh-agent镜像了。

**Comment by dqzgkyh** [comment]
> 可以使用docker ps -a | grep edgemesh-agent获取容器id，再使用docker logs 查看日志信息。（即使因Error而退出的容器，也是可以看日志的）

是的，下图是类似的操作，手动获取边缘节点所有的容器，然后打印指定容器的日志，什么日志都没有（不过这是使用的上一版的arm64架构的镜像，**使用最新的镜像再次进行部署就可以成功运行了**）
![图片](https://user-images.githubusercontent.com/58615473/143030052-6cbaffde-029e-4684-85cd-99bcf60a9785.png)

使用最新的镜像之后，arm64架构的镜像就可以成功运行了（没运行的那个是arm32架构，没运行属实正常）
![图片](https://user-images.githubusercontent.com/58615473/143031190-fc221797-256c-4102-abbc-ac494096c6de.png)

![图片](https://user-images.githubusercontent.com/58615473/143031484-6791218d-cd23-4568-a687-19cc386718c6.png)

**Comment by dqzgkyh** [comment]
但是官网给的测试用例无法运行，日志里面显示的是 `exec user process caused: exec format error`。这个错误实际上就是之前不支持arm64架构会报的错。
![图片](https://user-images.githubusercontent.com/58615473/143035844-e39bcc76-7b74-4afb-bce4-421ba8aa7d22.png)


我明天再试试其他的镜像，再配合 service 进行测试

**Comment by Poorunga** [comment]
目前edgemesh只有 amd64 和 arm64两个架构的镜像

**Comment by khalid-jobs** [comment]
arm32的可以试试自己编译，`PLATFORMS` 添加 `linux/arm/v7`, https://github.com/kubeedge/edgemesh/blob/main/Makefile#L28

**Comment by dqzgkyh** [comment]
> arm32的可以试试自己编译，PLATFORMS 添加 linux/arm/v7, https://github.com/kubeedge/edgemesh/blob/main/Makefile#L28

好的。再次感谢。
