### ISSUE TITLE
03-configmap.yaml and 04-deployment.yaml are missing

### ISSUE THREAD

**Issue by stingshen** [kubeedge/edgemesh#20]
**What happened**:

I am following README.md to test HTTP Gateway, but 03-configmap.yaml and 04-deployment.yaml are not found.

**What you expected to happen**:

03-configmap.yaml and 04-deployment.yaml are in code base.

**How to reproduce it (as minimally and precisely as possible)**:

Follow README.md to deploy edgemesh-gateway

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version: master

**Comment by Poorunga** [comment]
The file is here: https://github.com/kubeedge/edgemesh/tree/main/build/kubernetes/edgemesh-gateway

**Comment by stingshen** [comment]
thank you!
