### ISSUE TITLE
边缘端edgemesh-agent启动失败

### ISSUE THREAD

**Issue by nuckydong** [kubeedge/edgemesh#200]
**What happened**:  边缘侧启动edegemesh-agent失败
![1637664690](https://user-images.githubusercontent.com/19926347/143011439-3cd4b5db-b260-4597-bc27-fd2d0024e0a1.png)
kubectl logs 没有任何日志
docker logs 也没有日志输出

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version: 1.8
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.8.0
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`): x86_64
    - OS (e.g. `cat /etc/os-release`): ubuntu
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`): 1.16.8 
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>
    - edgecore version (e.g. `edgecore --version`):1.8
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):ubuntu 
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):1.16.8 
    - Others:
  </details>

**Comment by Poorunga** [comment]
请问你的edgenode-1是arm64的设备吗？

**Comment by nuckydong** [comment]
对 arm64的设备

**Comment by Poorunga** [comment]
之前的arm64镜像有点问题，昨晚修复了，你可以重新部署edgemesh试试。

最新的edgemesh-agent的arm64 imageID： 6b8a8e3466ba

**Comment by nuckydong** [comment]
好的 我试一试 谢谢

**Comment by nuckydong** [comment]
好了 感谢
