### ISSUE TITLE
edgemesh-agent built docker images in ARM64 will encounter a segment fault

### ISSUE THREAD

**Issue by Poorunga** [kubeedge/edgemesh#215]
**What happened**:
edgemesh-agent build docker images in ARM64 will encounter a segment fault.

**What you expected to happen**:
edgemesh-agent running normally.

**How to reproduce it (as minimally and precisely as possible)**:
Build edgemesh-agent image in arm64 environment, use `make agentimage` then `docker run xxx`

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version: 1.8.0
- Kubernetes version (use `kubectl version`): 1.18.20
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.8.2

**Comment by llhuii** [comment]
A golang program using golang plugin built by alpine image in ARM64 would be segment fault , I have created [an issue]( https://github.com/docker-library/golang/issues/402) in golang docker library.

`edgemesh-agent` => [`go-chassis`](https://github.com/go-chassis/go-chassis/blob/master/pkg/goplugin/plugin_enable.go) => `golang plugin`

**Comment by Poorunga** [comment]
pr #245 uses the golang:1.17 image as the new compiled image, so this problem no longer exists.
