### ISSUE TITLE
pod/edgemesh-agent-7crgk   error

### ISSUE THREAD

**Issue by 916264367** [kubeedge/edgemesh#229]
**What happened**:
that is cloud:
![image](https://user-images.githubusercontent.com/51771785/144957301-c8ef016f-7d20-411b-9c59-6a312df50b0d.png)
that is edge:
![image](https://user-images.githubusercontent.com/51771785/144957398-04724d3d-fc26-4073-9bc2-3f70bfcbc84b.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
If you need more information, let me know in the comments and I will provide
**Environment**:
- EdgeMesh version:The latest version
- Kubernetes version (use `kubectl version`):1.21.5
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.8.0
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by khalid-jobs** [comment]
How do you install the edgemesh?

**Comment by 916264367** [comment]
> 

This tutorial I refer to https://edgemesh.netlify.app/guide/getting-started.html#dependencies

**Comment by 916264367** [comment]
> > 
> 
> This tutorial I refer to https://edgemesh.netlify.app/guide/getting-started.html#dependencies

Manual Installation

**Comment by 916264367** [comment]
> How do you install the edgemesh?

This tutorial I refer to https://edgemesh.netlify.app/guide/getting-started.html#dependencies

Manual Installation

**Comment by khalid-jobs** [comment]
It seems that the edgemesh-agent do not get the <ApiServer-url>. Please let us see you configmap for edgemesh-agent. Try `kubectl get cm edgemesh-agent-cfg -n kubeedge -o yaml`

**Comment by 916264367** [comment]
> 似乎 edgemesh-agent 没有得到 . 请让我们看看你的 edgemesh-agent 配置图。尝试`kubectl get cm edgemesh-agent-cfg -n kubeedge -o yaml`

![image](https://user-images.githubusercontent.com/51771785/144986573-6910b16b-cdc5-4296-a510-1ce4e6a19304.png)
![image](https://user-images.githubusercontent.com/51771785/144986646-09c98096-6335-42b1-9a68-b57062607c8f.png)

**Comment by Poorunga** [comment]
把 configmap/edgemesh-agent-cfg 删掉再重新创建

**Comment by khalid-jobs** [comment]
推荐直接使用helm安装，估计可能时你之前edgmesh的configmap版本导致部署有问题。目前master分支的内容时与helm里面的保持一致的。或者你可以手动把KubeAPIConfig的配置删除。
