### ISSUE TITLE
1.7.1 metaServer doesn't work well

### ISSUE THREAD

**Issue by RobinsChens** [kubeedge/edgemesh#24]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version: release-1.7
- Kubernetes version (use `kubectl version`): 1.18.20
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.7.1
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`): 4
    - OS (e.g. `cat /etc/os-release`):  centos 7.6
    - Kernel (e.g. `uname -a`): 5.13
    - Go version (e.g. `go version`): 
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`): 1.7.1
    - Hardware configuration (e.g. `lscpu`): 4
    - OS (e.g. `cat /etc/os-release`):  centos7.6
    - Kernel (e.g. `uname -a`):  5.13
    - Go version (e.g. `go version`):
    - Others:

  </details>

####config 
```
  edgeMesh:
    enable: false
 metaManager:
    contextSendGroup: hub
    contextSendModule: websocket
    enable: true
    metaServer:
      debug: true
      enable: true
    podStatusSyncInterval: 60
    remoteQueryTimeout: 60
```
### api service success 
```
exec  in edgecore node --    icurl 127.0.0.1:10550/api/v1/services --->   response success
```

### curl service failed
```
[root@edge46 ~]# curl hostname-svc46.edgemesh-test:12345
curl: (6) Could not resolve host: hostname-svc46.edgemesh-test; Unknown error
```

### kubectl check
```
[root@chenwei78 ~]# kubectl -n edgemesh-test get ep -owide
NAME             ENDPOINTS         AGE
hostname-svc     172.17.0.2:9376   24h
hostname-svc46   172.17.0.2:9376   34h
You have new mail in /var/spool/mail/root
[root@chenwei78 ~]# kubectl -n edgemesh-test get pod -owide
NAME              READY   STATUS    RESTARTS   AGE   IP           NODE     NOMINATED NODE   READINESS GATES
hostname-edge     1/1     Running   0          25h   172.17.0.2   edge47   <none>           <none>
hostname-edge46   1/1     Running   0          25h   172.17.0.2   edge46   <none>           <none>
[root@chenwei78 ~]# kubectl -n edgemesh-test get svc -owide
NAME             TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE   SELECTOR
hostname-svc     ClusterIP   None         <none>        12345/TCP   24h   app=hostname-edge
hostname-svc46   ClusterIP   None         <none>        12345/TCP   34h   app=hostname-edge46
```

**Comment by ZBoIsHere** [comment]
@RobinsChens if you curl 127.0.0.1:10550/api/v1/services get a success response, it looks like metaServer work well. when you curl hostname-svc46.edgemesh-test:12345 get a unknown error, can you paste the edgemesh log when you launch a request.

**Comment by RobinsChens** [comment]
> @RobinsChens if you curl 127.0.0.1:10550/api/v1/services get a success response, it looks like metaServer work well. when you curl hostname-svc46.edgemesh-test:12345 get a unknown error, can you paste the edgemesh log when you launch a request.
E0806 06:26:15.273033       1 dns.go:287] [EdgeMesh] service hostname-svc.edgemesh-test is not found in this cluster
W0806 06:26:15.273069       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns
W0806 06:26:15.273087       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns
E0806 06:26:17.292035       1 dns.go:287] [EdgeMesh] service hostname-svc.edgemesh-test is not found in this cluster
W0806 06:26:17.292070       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns
W0806 06:26:17.292090       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns
E0806 06:26:19.311475       1 dns.go:287] [EdgeMesh] service hostname-svc.edgemesh-test is not found in this cluster
W0806 06:26:19.311533       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns
W0806 06:26:19.311563       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns
E0806 06:26:21.331779       1 dns.go:287] [EdgeMesh] service hostname-svc.edgemesh-test is not found in this cluster
W0806 06:26:21.331831       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns
W0806 06:26:21.331856       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns
E0806 06:26:23.352466       1 dns.go:287] [EdgeMesh] service hostname-svc.edgemesh-test is not found in this cluster
W0806 06:26:23.352503       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns
W0806 06:26:23.352525       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns
I0806 06:26:25.373078       1 dns.go:284] [EdgeMesh] dns server parse hostname-svc.edgemesh-test ip 10.102.52.176
W0806 06:26:25.373189       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns
I0806 06:27:12.616515       1 dns.go:284] [EdgeMesh] dns server parse hostname-svc.edgemesh-test ip 10.102.52.176
W0806 06:27:12.616610       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns
I0806 06:30:50.481463       1 dns.go:284] [EdgeMesh] dns server parse hostname-svc.edgemesh-test ip 10.102.52.176
W0806 06:30:50.481577       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns
I0806 06:33:04.782991       1 dns.go:284] [EdgeMesh] dns server parse hostname-svc.edgemesh-test ip 10.102.52.176
W0806 06:33:04.783090       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns
I0806 06:35:15.853812       1 dns.go:284] [EdgeMesh] dns server parse hostname-svc.edgemesh-test ip 10.102.52.176
W0806 06:35:15.853937       1 dns.go:122] [EdgeMesh] failed to resolve dns: get from real dns

**Comment by ZBoIsHere** [comment]
[root@chenwei78 ~]# kubectl -n edgemesh-test get svc -owide
NAME             TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE   SELECTOR
hostname-svc     ClusterIP   None         <none>        12345/TCP   24h   app=hostname-edge
hostname-svc46   ClusterIP   None         <none>        12345/TCP   34h   app=hostname-edge46

@RobinsChens which service type of hostname-svc, in this i saw the Cluster-IP is None, but in the log, hostname-svc.edgemesh-test parse info 10.102.52.106

**Comment by RobinsChens** [comment]
➜  keadm git:(v1.7.0offline) ✗ kubectl -n edgemesh-test delete svc hostname-svc45
service "hostname-svc45" deleted
➜  keadm git:(v1.7.0offline) ✗ kubectl -n edgemesh-test get pod,ep,svc -o wide   
NAME                READY   STATUS    RESTARTS   AGE     IP           NODE     NOMINATED NODE   READINESS GATES
pod/hostname-edge   1/1     Running   1          3d20h   172.17.0.2   edge46   <none>           <none>

NAME                     ENDPOINTS         AGE
endpoints/hostname-svc   172.17.0.2:9376   6d6h

NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE    SELECTOR
service/hostname-svc   ClusterIP   10.102.52.176   <none>        12345/TCP   6d6h   app=hostname-edge
➜  keadm git:(v1.7.0offline) ✗ ssh edge46                                        
Last login: Mon Aug  9 14:07:23 2021 from 172.16.0.66
[root@edge46 ~]#  curl hostname-svc.edgemesh-test:12345
curl: (7) Failed connect to hostname-svc.edgemesh-test:12345; Connection timed out

**Comment by RobinsChens** [comment]
edgemesh daemonset always  concreating



edgemesh-ww6j8   0/1     ContainerCreating   0          13m    192.168.1.10    edge01   <none>           <none>

**Comment by RobinsChens** [comment]
> [root@chenwei78 ~]# kubectl -n edgemesh-test get svc -owide
> NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE SELECTOR
> hostname-svc ClusterIP None 12345/TCP 24h app=hostname-edge
> hostname-svc46 ClusterIP None 12345/TCP 34h app=hostname-edge46
> 
> @RobinsChens which service type of hostname-svc, in this i saw the Cluster-IP is None, but in the log, hostname-svc.edgemesh-test parse info 10.102.52.106

i change the service type to none for testing,now i set it back

**Comment by ZBoIsHere** [comment]
@RobinsChens do <curl hostname-svc.edgemesh-test:12345 -v> on your host, and paste the result to me;
In addition, If the service name can't be resolve, then an error may occur in the edgemesh DNS module;
If the backend is healthy, but the request failed, then an error may occur in edgemesh proxy module;

**Comment by RobinsChens** [comment]
> curl hostname-svc.edgemesh-test:12345 -v

[root@edge46 ~]# curl hostname-svc.edgemesh-test:12345 -v
* About to connect() to hostname-svc.edgemesh-test port 12345 (#0)
*   Trying 10.102.52.176...

**Comment by RobinsChens** [comment]
> @RobinsChens do <curl hostname-svc.edgemesh-test:12345 -v> on your host, and paste the result to me;
> In addition, If the service name can't be resolve, then an error may occur in the edgemesh DNS module;
> If the backend is healthy, but the request failed, then an error may occur in edgemesh proxy module;

[root@edge46 ~]# curl hostname-svc.edgemesh-test:12345 -v
* About to connect() to hostname-svc.edgemesh-test port 12345 (#0)
*   Trying 10.102.52.176...



* Connection timed out
* Failed connect to hostname-svc.edgemesh-test:12345; Connection timed out
* Closing connection 0
curl: (7) Failed connect to hostname-svc.edgemesh-test:12345; Connection timed out

**Comment by RobinsChens** [comment]
> @RobinsChens do <curl hostname-svc.edgemesh-test:12345 -v> on your host, and paste the result to me;
> In addition, If the service name can't be resolve, then an error may occur in the edgemesh DNS module;
> If the backend is healthy, but the request failed, then an error may occur in edgemesh proxy module;

[root@edge46 ~]# curl localhost:9376
hostname-edge
[root@edge46 ~]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:9376

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            
[root@edge46 ~]# curl 172.17.0.2:9376
hostname-edge
[root@edge46 ~]# cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 172.17.0.1
nameserver 172.16.20.254
nameserver 192.168.1.1

**Comment by ZBoIsHere** [comment]
From the info above, the service name can resolve into clusterIP, and the backend is healthy. Probably the edge proxy module does't work well.
do the cmd <iptables -L -t nat> in you host, and check EDGE_MESH chain exist or not
and open the log by <docker logs -f $edgemeshid> when you launch a request to see the detail

**Comment by RobinsChens** [comment]
> From the info above, the service name can resolve into clusterIP, and the backend is healthy. Probably the edge proxy module does't work well.
> do the cmd <iptables -L -t nat> in you host, and check EDGE_MESH chain exist or not
> and open the log by <docker logs -f $edgemeshid> when you launch a request to see the detail

[root@edge46 ~]# iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
EDGE-MESH  tcp  --  anywhere             9.251.0.0/16        
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
EDGE-MESH  tcp  --  anywhere             10.10.0.0/16        
EDGE-MESH  tcp  --  anywhere             10.96.0.0/12        

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
EDGE-MESH  tcp  --  anywhere             9.251.0.0/16        
DOCKER     all  --  anywhere            !loopback/8           ADDRTYPE match dst-type LOCAL
EDGE-MESH  tcp  --  anywhere             10.10.0.0/16        
EDGE-MESH  tcp  --  anywhere             10.96.0.0/12        

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            
MASQUERADE  tcp  --  172.17.0.2           172.17.0.2           tcp dpt:9376

Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            
DNAT       tcp  --  anywhere             anywhere             tcp dpt:9376 to:172.17.0.2:9376

Chain EDGE-MESH (6 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             anywhere             to: random persistent random persistent random persistent
DNAT       tcp  --  anywhere             anywhere             to: random persistent random persistent random persistent

**Comment by RobinsChens** [comment]
> From the info above, the service name can resolve into clusterIP, and the backend is healthy. Probably the edge proxy module does't work well.
> do the cmd <iptables -L -t nat> in you host, and check EDGE_MESH chain exist or not
> and open the log by <docker logs -f $edgemeshid> when you launch a request to see the detail

i find some special issue 

[root@master01 edgemesh]# kubectl get svc -A
NAMESPACE       NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default         kubernetes           ClusterIP   10.96.0.1        <none>        443/TCP                  4d18h
edgemesh-test   hostname-svc         ClusterIP   10.96.176.71     <none>        12345/TCP                39m
edgemesh-test   hostname-svcedge01   ClusterIP   10.96.226.198    <none>        12345/TCP                40m
edgemesh-test   tcp-echo-service     ClusterIP   10.101.122.40    <none>        2701/TCP                 19m
edgemesh-test   ws-svc               ClusterIP   10.106.110.132   <none>        12348/TCP                10m
kube-system     kube-dns             ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   4d18h

  containers:
  - command:
    - kube-apiserver
    - --advertise-address=192.168.1.9
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --feature-gates=TTLAfterFinished=true
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-cluster-ip-range=10.96.0.0/12


the service clusterip out of api server config range 10.96.0.0/12

**Comment by EnfangCui** [comment]
Have you solved this problem? I also encountered this problem.
```
root@i-cpc3wtjy:/home/ubuntu# telnet tcp-echo-service.default 2701
telnet: could not resolve tcp-echo-service.default/2701: Name or service not known

```

**Comment by RobinsChens** [comment]
> Have you solved this problem? I also encountered this problem.
> 
> ```
> root@i-cpc3wtjy:/home/ubuntu# telnet tcp-echo-service.default 2701
> telnet: could not resolve tcp-echo-service.default/2701: Name or service not known
> ```

yes , i 

> From the info above, the service name can resolve into clusterIP, and the backend is healthy. Probably the edge proxy module does't work well.
> do the cmd <iptables -L -t nat> in you host, and check EDGE_MESH chain exist or not
> and open the log by <docker logs -f $edgemeshid> when you launch a request to see the detail

some new problem appears now , 

Aug 13 17:39:02 edge01 edgecore: E0813 17:39:02.779293    9489 secret.go:195] Couldn't get secret default/default-token-jrlsw: get secret from metaManager failed, err: timed out waiting for the condition
Aug 13 17:39:02 edge01 edgecore: I0813 17:39:02.779376    9489 record.go:24] Warning FailedMount MountVolume.SetUp failed for volume "default-token-jrlsw" : get secret from metaManager failed, err: timed out waiting for the condition
Aug 13 17:39:02 edge01 edgecore: E0813 17:39:02.779469    9489 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/secret/61b397ad-dc8c-40da-bc28-ea8b87f037b1-default-token-jrlsw podName:61b397ad-dc8c-40da-bc28-ea8b87f037b1 nodeName:}" failed. No retries permitted until 2021-08-13 17:41:04.779410739 +0800 CST m=+7004.892756162 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"default-token-jrlsw\" (UniqueName: \"kubernetes.io/secret/61b397ad-dc8c-40da-bc28-ea8b87f037b1-default-token-jrlsw\") pod \"nginx-edge-677d5dbd8-54ff8\" (UID: \"61b397ad-dc8c-40da-bc28-ea8b87f037b1\") : get secret from metaManager failed, err: timed out waiting for the condition"
Aug 13 17:39:02 edge01 edgecore: I0813 17:39:02.781181    9489 process.go:469] ########## process get: req[{Header:{ID:54b519df-aa02-41f9-bf02-e322733fdc8c ParentID: Timestamp:1628847422767 ResourceVersion: Sync:true} Router:{Source:edged Group:meta Operation:query Resource:default/secret/default-token-jrlsw} Content:<nil>}], resp[{Header:{ID: ParentID: Timestamp:0 ResourceVersion: Sync:false} Router:{Source: Group: Operation: Resource:} Content:<nil>}], err[timeout to get response]
Aug 13 17:39:02 edge01 edgecore: E0813 17:39:02.781335    9489 process.go:471] remote query failed: timeout to get response
Aug 13 17:39:10 edge01 edgecore: I0813 17:39:10.461956    9489 edged_status.go:198] Sync VolumesInUse: []
Aug 13 17:39:12 edge01 edgecore: I0813 17:39:12.980535    9489 storage.go:159] [metaserver/reststorage] successfully apply for a watch listener (/api/v1/endpoints) through cloud

**Comment by RobinsChens** [comment]
> Have you solved this problem? I also encountered this problem.
> 
> ```
> root@i-cpc3wtjy:/home/ubuntu# telnet tcp-echo-service.default 2701
> telnet: could not resolve tcp-echo-service.default/2701: Name or service not known
> ```

yes, you can attention 


部署 edgemesh 组件-- need to change service-cluster-ip-range

```shell
# 请将03-configmap.yaml里面的subNet配置成kube-apiserver的service-cluster-ip-range的值
# 你可以在k8s master节点上的/etc/kubernetes/manifests/kube-apiserver.yaml文件中找到这个配置项的值
$ kubectl apply -f build/kubernetes/edgemesh/03-configmap.yaml
configmap/edgemesh-cfg created
$ kubectl apply -f build/kubernetes/edgemesh/04-daemonset.yaml
daemonset.apps/edgemesh created

**Comment by EnfangCui** [comment]
> yes, you can attention
> 
> 部署 edgemesh 组件-- need to change service-cluster-ip-range
> 
> ```shell
> # 请将03-configmap.yaml里面的subNet配置成kube-apiserver的service-cluster-ip-range的值
> # 你可以在k8s master节点上的/etc/kubernetes/manifests/kube-apiserver.yaml文件中找到这个配置项的值
> $ kubectl apply -f build/kubernetes/edgemesh/03-configmap.yaml
> configmap/edgemesh-cfg created
> $ kubectl apply -f build/kubernetes/edgemesh/04-daemonset.yaml
> daemonset.apps/edgemesh created
> ```

Thank you very much. I successfully solved the problem according to this solution.

**Comment by EnfangCui** [comment]
> yes, you can attention
> 
> 部署 edgemesh 组件-- need to change service-cluster-ip-range
> 
> ```shell
> # 请将03-configmap.yaml里面的subNet配置成kube-apiserver的service-cluster-ip-range的值
> # 你可以在k8s master节点上的/etc/kubernetes/manifests/kube-apiserver.yaml文件中找到这个配置项的值
> $ kubectl apply -f build/kubernetes/edgemesh/03-configmap.yaml
> configmap/edgemesh-cfg created
> $ kubectl apply -f build/kubernetes/edgemesh/04-daemonset.yaml
> daemonset.apps/edgemesh created
> ```

Thank you very much. I successfully solved the problem according to this solution.
