### ISSUE TITLE
EdgeMesh causing addition non-edge pods to be pulled to edge and run

### ISSUE THREAD

**Issue by markretallack** [kubeedge/edgemesh#276]
**What happened**:

When deploying the edgemesh, the device running the edgecore starts to "pull" and run pods that should not be running on the edge (nodeSelector prevents them).

**What you expected to happen**:

Pods with nodeSelector set for "cloud" to only be run on the cloud. 

**How to reproduce it (as minimally and precisely as possible)**:

Deploy CloudCore, edgecore and then deploy edgemesh

**Anything else we need to know?**:

I have tracked it down to after the "*v1.Pod" Watch List informer. All is working correctly until the WatchFunc in vendor/k8s.io/client-go/informers/core/v1/pod.go is called. Once this function returns, the systems starts to pull pods that should not be running. 

**Environment**:
- EdgeMesh version: 49bbe4a27e23b0ae1b0ffaf65fb9668f8249ef3a
- Kubernetes version (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): f457f96aa05b770070db24df54990a9c2993232a
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
What is your KubeEdge version?

**Comment by markretallack** [comment]
> What is your KubeEdge version?

Its from the head of kubeedge from last week, so 1.9+

https://github.com/kubeedge/kubeedge/tree/f457f96aa05b770070db24df54990a9c2993232a

**Comment by markretallack** [comment]
> 

Thanks, do not know how I managed to miss that issue in the kubeedge repo. 



Mark
