### ISSUE TITLE
where is the offical image？

### ISSUE THREAD

**Issue by pengbinbin1** [kubeedge/edgemesh#279]
I have serarched the image about edgemesn-agent on the dockerio.com,but i got a 404 ,where can i get the image

**Comment by Poorunga** [comment]
docker pull kubeedge/edgemesh-agent:<tag>

**Comment by pengbinbin1** [comment]
> 
i want the version about arm


>

**Comment by pengbinbin1** [comment]
And where is the difference between v1.8.0 and v1.8.0-48-gc8b6721?

**Comment by Poorunga** [comment]
docker pull kubeedge/edgemesh-agent:<tag> in arm64 machine you will get a arm64 edgemesh-agent image

**Comment by Poorunga** [comment]
v1.8.0-48-gc8b6721 is a test image don't use it

**Comment by pengbinbin1** [comment]
On the docker hub,the v1.8.0 do not have the arm version,are you sure i can get the v1.8.0 arm image on the  arm64 machine?

**Comment by Poorunga** [comment]
You can get the v1.9.0 and latest arm64 image on the arm64 machine? 
If you need an arm64 image of v1.8.0, I can build it for you

**Comment by pengbinbin1** [comment]
Yes i  need an arm64 image of v1.8.0, can you build it for me,thank you very much.

**Comment by Poorunga** [comment]
Now you can try docker pull kubeedge/edgemesh-agent:v1.8.0

**Comment by pengbinbin1** [comment]
ok ,thank you !
