### ISSUE TITLE
coredns readiness probe failed after installing edgemesh

### ISSUE THREAD

**Issue by vikarna** [kubeedge/edgemesh#293]
HI, Below is the describe for the coredns pod. I have used kubeedge. 

  Type     Reason     Age                  From     Message
  ----     ------     ----                 ----     -------
  Normal   Created    28m                  kubelet  Created container coredns
  Warning  Unhealthy  28m                  kubelet  Readiness probe failed: Get "http://10.40.69.200:8181/ready": read tcp 192.168.15.136:34086->10.40.69.200:8181: read: connection reset by peer
  Warning  Unhealthy  27m                  kubelet  Readiness probe failed: Get "http://10.40.69.200:8181/ready": read tcp 192.168.15.136:34154->10.40.69.200:8181: read: connection reset by peer
  Warning  Unhealthy  27m                  kubelet  Readiness probe failed: Get "http://10.40.69.200:8181/ready": read tcp 192.168.15.136:34208->10.40.69.200:8181: read: connection reset by peer
  Warning  Unhealthy  27m                  kubelet  Readiness probe failed: Get "http://10.40.69.200:8181/ready": read tcp 192.168.15.136:34374->10.40.69.200:8181: read: connection reset by peer
  Warning  Unhealthy  27m                  kubelet  Readiness probe failed: Get "http://10.40.69.200:8181/ready": read tcp 192.168.15.136:34428->10.40.69.200:8181: read: connection reset by peer
  Warning  Unhealthy  26m                  kubelet  Readiness probe failed: Get "http://10.40.69.200:8181/ready": read tcp 192.168.15.136:34536->10.40.69.200:8181: read: connection reset by peer
  Warning  Unhealthy  26m                  kubelet  Readiness probe failed: Get "http://10.40.69.200:8181/ready": read tcp 192.168.15.136:34592->10.40.69.200:8181: read: connection reset by peer
  Warning  Unhealthy  26m                  kubelet  Readiness probe failed: Get "http://10.40.69.200:8181/ready": read tcp 192.168.15.136:34646->10.40.69.200:8181: read: connection reset by peer
  Normal   Killing    25m                  kubelet  Container coredns failed liveness probe, will be restarted
  Normal   Pulled     25m (x2 over 28m)    kubelet  Container image "k8s.gcr.io/coredns:1.7.0" already present on machine
  Normal   Started    18m (x5 over 28m)    kubelet  Started container coredns
  Warning  Unhealthy  13m (x71 over 26m)   kubelet  (combined from similar events): Readiness probe failed: Get "http://10.40.69.200:8181/ready": read tcp 192.168.15.136:39182->10.40.69.200:8181: read: connection reset by peer
  Warning  BackOff    8m5s (x14 over 10m)  kubelet  Back-off restarting failed container

root@kmaster1:~/edgemesh# kubectl get nodes
NAME       STATUS   ROLES                  AGE    VERSION
kmaster1   Ready    control-plane,master   120m   v1.20.15
kworker1   Ready    agent,edge             97m    v1.19.3-kubeedge-v1.9.1

root@kmaster1:~/edgemesh# kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS             RESTARTS   AGE
default       alpine-test                               1/1     Running            0          78m
default       hostname-edge-84cb45ccf4-2n2pl            1/1     Running            0          50m
default       websocket-test                            1/1     Running            0          78m
kube-system   calico-kube-controllers-9f9fc867d-csj9x   1/1     Running            0          112m
kube-system   calico-node-7kk9j                         1/1     Running            0          72m
kube-system   coredns-c85546cff-jlkmx                   0/1     CrashLoopBackOff   8          30m
kube-system   etcd-kmaster1                             1/1     Running            0          120m
kube-system   kube-apiserver-kmaster1                   1/1     Running            0          120m
kube-system   kube-controller-manager-kmaster1          1/1     Running            0          120m
kube-system   kube-proxy-jjz5k                          1/1     Running            0          110m
kube-system   kube-scheduler-kmaster1                   1/1     Running            0          120m
kubeedge      edgemesh-agent-87jl7                      1/1     Running            0          56m
kubeedge      edgemesh-server-5469fbc686-lf4nq          1/1     Running            0          63m

**Comment by Poorunga** [comment]
show me `kubectl get all -n kube-system -owide`

**Comment by Poorunga** [comment]
Try `curl` again and show me edgemesh logs using `docker logs <edgemesh-container-id>`

**Comment by vikarna** [comment]
docker logs edgemesh-agent
From Master 
I0217 12:54:30.205430       1 handler.go:58] l4 proxy get tcpserver address: kworker1:172.17.0.8:9376
I0217 12:55:42.371370       1 proxy.go:42] clusterIP: 10.40.231.78, servicePort: 12345
I0217 12:55:42.371783       1 log.go:184] DEBUG: add [2] handlers for chain [tcp]
I0217 12:55:42.371964       1 handler.go:58] l4 proxy get tcpserver address: kworker1:172.17.0.8:9376
I0217 12:55:54.670904       1 proxy.go:42] clusterIP: 10.40.231.78, servicePort: 12345
I0217 12:55:54.671081       1 log.go:184] DEBUG: add [2] handlers for chain [tcp]
I0217 12:55:54.671122       1 handler.go:58] l4 proxy get tcpserver address: kworker1:172.17.0.8:9376
I0217 12:57:31.715646       1 proxy.go:42] clusterIP: 10.40.231.78, servicePort: 12345
I0217 12:57:31.716122       1 log.go:184] DEBUG: add [2] handlers for chain [tcp]
I0217 12:57:31.716214       1 handler.go:58] l4 proxy get tcpserver address: kworker1:172.17.0.8:9376
I0217 13:01:47.238874       1 proxy.go:42] clusterIP: 10.40.231.78, servicePort: 12345
I0217 13:01:47.239456       1 log.go:184] DEBUG: add [2] handlers for chain [tcp]
I0217 13:01:47.239677       1 handler.go:58] l4 proxy get tcpserver address: kworker1:172.17.0.8:9376
I0217 13:02:29.791778       1 proxy.go:42] clusterIP: 10.40.231.78, servicePort: 12345
I0217 13:02:29.791950       1 log.go:184] DEBUG: add [2] handlers for chain [tcp]
I0217 13:02:29.792050       1 handler.go:58] l4 proxy get tcpserver address: kworker1:172.17.0.8:9376
I0217 13:04:57.536862       1 proxy.go:42] clusterIP: 10.40.231.78, servicePort: 12345
I0217 13:04:57.537503       1 log.go:184] DEBUG: add [2] handlers for chain [tcp]
I0217 13:04:57.537757       1 handler.go:58] l4 proxy get tcpserver address: kworker1:172.17.0.8:9376
I0217 13:14:00.812121       1 proxy.go:42] clusterIP: 10.40.231.78, servicePort: 12345
I0217 13:14:00.812646       1 log.go:184] DEBUG: add [2] handlers for chain [tcp]
I0217 13:14:00.812956       1 handler.go:58] l4 proxy get tcpserver address: kworker1:172.17.0.8:9376
I0217 13:17:48.403950       1 proxy.go:42] clusterIP: 10.40.231.78, servicePort: 12345
I0217 13:17:48.404445       1 log.go:184] DEBUG: add [2] handlers for chain [tcp]
I0217 13:17:48.404626       1 handler.go:58] l4 proxy get tcpserver address: kworker1:172.17.0.8:9376
I0217 13:19:31.193295       1 proxy.go:42] clusterIP: 10.40.231.78, servicePort: 12345
I0217 13:19:31.193507       1 log.go:184] DEBUG: add [2] handlers for chain [tcp]
I0217 13:19:31.193563       1 handler.go:58] l4 proxy get tcpserver address: kworker1:172.17.0.8:9376
I0217 13:40:57.895543       1 proxy.go:42] clusterIP: 10.40.231.78, servicePort: 12345
I0217 13:40:57.896450       1 log.go:184] DEBUG: add [2] handlers for chain [tcp]
I0217 13:40:57.896786       1 handler.go:58] l4 proxy get tcpserver address: kworker1:172.17.0.8:9376
I0217 13:42:31.739612       1 proxy.go:42] clusterIP: 10.40.231.78, servicePort: 12345
I0217 13:42:31.739782       1 log.go:184] DEBUG: add [2] handlers for chain [tcp]
I0217 13:42:31.739823       1 handler.go:58] l4 proxy get tcpserver address: kworker1:172.17.0.8:9376


From worker
I0217 13:01:47.243541       1 proxy.go:49] Get a new stream from QmRZbchZy3XT4aeS5rW53KJZWdJcVr1FRrkYUd8SjZZt5m
E0217 13:01:53.246343       1 proxy.go:110] max retries for tcp dial
E0217 13:01:53.246398       1 proxy.go:68] l4 proxy connect to type:CONNECT protocol:"tcp" node_name:"kworker1" ip:"172.17.0.8" port:9376  err: dial tcp 172.17.0.8:9376: connect: connection refused
I0217 13:02:29.795784       1 proxy.go:49] Get a new stream from QmRZbchZy3XT4aeS5rW53KJZWdJcVr1FRrkYUd8SjZZt5m
E0217 13:02:35.799822       1 proxy.go:110] max retries for tcp dial
E0217 13:02:35.799868       1 proxy.go:68] l4 proxy connect to type:CONNECT protocol:"tcp" node_name:"kworker1" ip:"172.17.0.8" port:9376  err: dial tcp 172.17.0.8:9376: connect: connection refused
I0217 13:04:57.540739       1 proxy.go:49] Get a new stream from QmRZbchZy3XT4aeS5rW53KJZWdJcVr1FRrkYUd8SjZZt5m
E0217 13:05:03.544479       1 proxy.go:110] max retries for tcp dial
E0217 13:05:03.544509       1 proxy.go:68] l4 proxy connect to type:CONNECT protocol:"tcp" node_name:"kworker1" ip:"172.17.0.8" port:9376  err: dial tcp 172.17.0.8:9376: connect: connection refused
I0217 13:14:00.815868       1 proxy.go:49] Get a new stream from QmRZbchZy3XT4aeS5rW53KJZWdJcVr1FRrkYUd8SjZZt5m
E0217 13:14:06.820150       1 proxy.go:110] max retries for tcp dial
E0217 13:14:06.820194       1 proxy.go:68] l4 proxy connect to type:CONNECT protocol:"tcp" node_name:"kworker1" ip:"172.17.0.8" port:9376  err: dial tcp 172.17.0.8:9376: connect: connection refused
I0217 13:17:48.407591       1 proxy.go:49] Get a new stream from QmRZbchZy3XT4aeS5rW53KJZWdJcVr1FRrkYUd8SjZZt5m
E0217 13:17:54.410165       1 proxy.go:110] max retries for tcp dial
E0217 13:17:54.410218       1 proxy.go:68] l4 proxy connect to type:CONNECT protocol:"tcp" node_name:"kworker1" ip:"172.17.0.8" port:9376  err: dial tcp 172.17.0.8:9376: connect: connection refused
I0217 13:19:31.196331       1 proxy.go:49] Get a new stream from QmRZbchZy3XT4aeS5rW53KJZWdJcVr1FRrkYUd8SjZZt5m
E0217 13:19:37.198815       1 proxy.go:110] max retries for tcp dial
E0217 13:19:37.198861       1 proxy.go:68] l4 proxy connect to type:CONNECT protocol:"tcp" node_name:"kworker1" ip:"172.17.0.8" port:9376  err: dial tcp 172.17.0.8:9376: connect: connection refused
I0217 13:40:57.900043       1 proxy.go:49] Get a new stream from QmRZbchZy3XT4aeS5rW53KJZWdJcVr1FRrkYUd8SjZZt5m
E0217 13:41:03.903368       1 proxy.go:110] max retries for tcp dial
E0217 13:41:03.903419       1 proxy.go:68] l4 proxy connect to type:CONNECT protocol:"tcp" node_name:"kworker1" ip:"172.17.0.8" port:9376  err: dial tcp 172.17.0.8:9376: connect: connection refused
I0217 13:42:31.742356       1 proxy.go:49] Get a new stream from QmRZbchZy3XT4aeS5rW53KJZWdJcVr1FRrkYUd8SjZZt5m
E0217 13:42:37.745043       1 proxy.go:110] max retries for tcp dial
E0217 13:42:37.745094       1 proxy.go:68] l4 proxy connect to type:CONNECT protocol:"tcp" node_name:"kworker1" ip:"172.17.0.8" port:9376  err: dial tcp 172.17.0.8:9376: connect: connection refused
root@kworker1:~# curl 172.17.0.8:9376
curl: (7) Failed to connect to 172.17.0.8 port 9376: Connection refused
root@kworker1:~# docker ps | grep hostname
c6398e21a5aa        a1abbd75d6c0         "/serve_hostname"        59 minutes ago      Up 59 minutes                           k8s_hostname_hostname-edge-84cb45ccf4-88mxv_default_ab3d566d-665e-4acc-8255-d46355c6b012_2
deda3c0d37f2        kubeedge/pause:3.1   "/pause"                 59 minutes ago      Up 59 minutes                           k8s_POD_hostname-edge-84cb45ccf4-88mxv_default_ab3d566d-665e-4acc-8255-d46355c6b012_2
root@kworker1:~# ping 172.17.0.8
PING 172.17.0.8 (172.17.0.8) 56(84) bytes of data.
64 bytes from 172.17.0.8: icmp_seq=1 ttl=64 time=0.137 ms
64 bytes from 172.17.0.8: icmp_seq=2 ttl=64 time=0.111 ms

**Comment by Poorunga** [comment]
```
$ curl 172.17.0.8:9376
Failed to connect to 172.17.0.8 port 9376: Connection refused
```
Are your pod running normal?

**Comment by vikarna** [comment]
Yes. I am not seeing any restarts. Do you suspect any iptables problem?

**Comment by Poorunga** [comment]
It doesn't look like an iptables problem, because the traffic is correctly forwarded to the kworker.

Try `kubectl get pod ` to see your pod running status.

**Comment by vikarna** [comment]
root@kmaster1:~# kubectl get pod hostname-edge-84cb45ccf4-88mxv
NAME                             READY   STATUS    RESTARTS   AGE
hostname-edge-84cb45ccf4-88mxv   1/1     Running   1          4h53m


I see the same ip for the two worker nodes below. Is this normal?

kubeedge      edgemesh-agent-75q64                      1/1     Running   2          143m    192.168.15.135   kworker1   <none>           <none>
kubeedge      edgemesh-agent-s6qqg                      1/1     Running   2          143m    192.168.15.135   kworker2   <none>           <none>
kubeedge      edgemesh-agent-s8vxr                      1/1     Running   1          143m    192.168.15.136   kmaster1   <none>           <none>
kubeedge      edgemesh-server-5469fbc686-lf4nq          1/1     Running   2          27h     192.168.15.136   kmaster1   <none>           <none>

**Comment by Poorunga** [comment]
On my edge node, accessing pods through curl:
```
root@ke-edge2:~# curl 172.17.0.2:9376
hostname-lb-edge-5cdf5c758c-f5tqj
```

It is able to return something instead of `Connection refused`

**Comment by vikarna** [comment]
Nope

root@kmaster1:~# kubectl get nodes -o wide
NAME       STATUS   ROLES                  AGE     VERSION                   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
kmaster1   Ready    control-plane,master   28h     v1.20.15                  192.168.15.136   <none>        Ubuntu 20.04.3 LTS   5.4.0-99-generic   docker://19.3.15
kworker1   Ready    agent,edge             28h     v1.19.3-kubeedge-v1.9.1   192.168.15.137   <none>        Ubuntu 20.04.3 LTS   5.4.0-99-generic   docker://19.3.15
kworker2   Ready    agent,edge             5h31m   v1.19.3-kubeedge-v1.9.1   192.168.15.135   <none>        Ubuntu 20.04.3 LTS   5.4.0-90-generic   docker://19.3.15

**Comment by Poorunga** [comment]
This is very strange, edgemesh-agent is started using hostnetwork and will keep the same ip as the host...

**Comment by vikarna** [comment]
Let me delete and create again

**Comment by Poorunga** [comment]
You can try to deploy the hostname application directly without installing edgemesh. Then access it through curl podip:port in kworker. We need to rule this out first.

**Comment by abhinavjha126** [comment]
@Poorunga 
I am also facing the same issue
I have tried with and without edgemesh ,without edgemesh pods are working well and are not restarting.
Pods are restarting as soon as i deploy Edgemesh.
Dont know whats the issue and i also noticed that all edge nodes are having same ip.
What reason it could be??
![Screenshot 2022-02-24 at 7 36 47 PM](https://user-images.githubusercontent.com/85448474/155548928-65a954ed-144c-4d40-9f4e-3a19f57b999d.png)

**Comment by Poorunga** [comment]
@vikarna @abhinavjha126 Is your kubeedge version v1.9.0+?

Maybe it's because of this bug: https://github.com/kubeedge/kubeedge/issues/3489

Try rolling back the version of kubeedge to v1.8.2 to test again.

**Comment by abhinavjha126** [comment]
@Poorunga my kubeedge version is 1.9.1
Is it for that reason we are facing issue??
Does kubeedge  v1.8.2 require golang??

**Comment by Poorunga** [comment]
@abhinavjha126 

>1. Is CNI/Calico mandatory to be used along with KubeEdge setup??? (We are using)

You can install or not install the cni plugin. kubeedge and edgemesh don't care and are compatible with them.

> 2. Why all pods are restarting as soon as we deploy edgemesh??

A known kubeedge bug: https://github.com/kubeedge/kubeedge/issues/3489. The problem is caused by someone doing a list-watch of the pod. (edgemesh will list-watch pod then it tigger this bug...)

> 3. Do you have any document/commands from where we can install kubeedge step by step??

It is best to follow the official documentation of kubeedge: https://kubeedge.io

**Comment by Poorunga** [comment]
https://github.com/kubeedge/kubeedge/issues/3489 this bug is fixed in https://github.com/kubeedge/kubeedge/pull/3606

**Comment by abhinavjha126** [comment]
@Poorunga I will try kubeedge v1.8.2 and let u know whether pods are still restarting or not

**Comment by abhinavjha126** [comment]
@Poorunga I downgraded the version to v1.8.1 and it's working quiet nicely.Now pods are not restarting.Thanks a lot.
Can i get some advanced test cases to run on this???
Suppose if i shutdown 1 edge node then will all pods running on that node work???

**Comment by abhinavjha126** [comment]
@Poorunga I stopped one of the two nodes to test and when i restarted that node its not getting ready.What could be the reason??
And pod also got stuck in termination

![29db76d3-a0c8-49e5-9aa5-6bd86a807039](https://user-images.githubusercontent.com/85448474/155996709-532f5802-f161-47e4-a30b-d429bfa15054.jpg)

**Comment by abhinavjha126** [comment]
@Poorunga Is there any command or file path to enable or disable autonomy??
Please provide

**Comment by Poorunga** [comment]
@abhinavjha126  This is a feature that is enabled by default.

**Comment by abhinavjha126** [comment]
@Poorunga What if i want to disable that feature..There will be some file from where i can disable that

**Comment by Poorunga** [comment]
@abhinavjha126  After learning some information about kubeedge, I found that the edge autonomy function cannot be turned off.

**Comment by abhinavjha126** [comment]
@Poorunga Thanks a lot.
Last query from my side
I want to check pod status when connection is unsable/break between core and edge.
What should i do or which ports should i stop to cut the connection between core and edge???

**Comment by Poorunga** [comment]
@abhinavjha126 
I can't provide any answer, maybe you can move the question to: https://github.com/kubeedge/kubeedge/issues
