### ISSUE TITLE
if  a service have more than one port, only one of the port can be used

### ISSUE THREAD

**Issue by pengbinbin1** [kubeedge/edgemesh#314]
**What happened**:
I created a service on my server with 2 ports ,but when i curl the service with the port, only one of the 2 ports can be accessed,another one can not be accessed

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version:
- v.1.8.0
- Kubernetes version (use `kubectl version`):
- v1.20.10
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- v1.8.1
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
release-1.9 has fix this issue: https://github.com/kubeedge/edgemesh/blob/release-1.9/agent/pkg/chassis/registry/registry.go#L98-L115

You can patch it by yourself or upgrade edgemesh version.

**Comment by pengbinbin1** [comment]
OK， thank you

**Comment by pengbinbin1** [comment]
> release-1.9 has fix this issue: https://github.com/kubeedge/edgemesh/blob/release-1.9/agent/pkg/chassis/registry/registry.go#L98-L115
> 
> You can patch it by yourself or upgrade edgemesh version.

I hvae patch it to edgemesh-agent v1.8.0 and i have build the image by the Dockerfile in edgemesh, but how can i build the image based arm?

**Comment by Poorunga** [comment]
make IMAGE_REPO=<your dockerhub name> IMAGE_TAG=latest push-all

**Comment by pengbinbin1** [comment]
> make IMAGE_REPO= IMAGE_TAG=latest push-all

My branch is v1.8.0 .I  have checked the makefile in v1.8.0 and can not find the "push all".

**Comment by pengbinbin1** [comment]
And i want to build the arm64 image on my x86 server

**Comment by Poorunga** [comment]
> My branch is v1.8.0 .I have checked the makefile in v1.8.0 and can not find the "push all".

You can checkout branch to `main`, then refer to the Makefile and Dockerfile and hack/*.sh files of main branch. These files also can work on branch v1.8.0.

**Comment by pengbinbin1** [comment]
> docker `buildx` subcommand can meet your needs.

thanks
