### ISSUE TITLE
Pods/Service inaccessible when connection between cloud node and edge node is down

### ISSUE THREAD

**Issue by vikarna** [kubeedge/edgemesh#317]
**What happened**:
Node not ready and pods went to pending state
**What you expected to happen**:
after breaking the connection between  cloud and  edge node, the pods and services should work normally
 **How to reproduce it (as minimally and precisely as possible)**:
Block the connection between cloud and edge node
**Anything else we need to know?**:

**Environment**:
- EdgeMesh version:  1.8.1
- Kubernetes version (use `kubectl version`):v1.21.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.19.3-kubeedge-v1.8.1

**Comment by Poorunga** [comment]
Print some edgemesh-agent logs

**Comment by abhinavjha126** [comment]
@Poorunga Here is the screenshot of node state not ready and pods are also terminating
![terminating](https://user-images.githubusercontent.com/85448474/156608938-bf7d5f85-9808-472d-803c-b604a680ac60.jpeg)
Here are the logs of edgemesh-agent
![edgemesh agent log](https://user-images.githubusercontent.com/85448474/156609072-71964a9b-5ff9-4f0d-b98e-e625cee4afd0.jpeg)
Here is the observation which i have done to block connection between core and edge
![observation_done](https://user-images.githubusercontent.com/85448474/156609173-67033545-2978-4dbb-8cc2-fa40fcabb8da.jpeg)

**Comment by Poorunga** [comment]
At this stage edgemesh-agent needs to connect to edgemesh-server

**Comment by vikarna** [comment]
Can we deploy multiple edgemesh server instead of only one?

**Comment by Poorunga** [comment]
The high availability design of edgemesh-server is in progress...

**Comment by vikarna** [comment]
Thanks @Poorunga. When is the release expected? 

Please close this issue.

**Comment by Poorunga** [comment]
@vikarna  Maybe in v1.11

/close
