### ISSUE TITLE
which mod edit the resolve.conf in the pod?

### ISSUE THREAD

**Issue by pengbinbin1** [kubeedge/edgemesh#318]
I have read the code on version v1.8.0.  I konw that the edgemesh-agent will change the /etc/resolve.conf in the pod, and it will affect the resolve.conf on the host。 But I can not find which mod edit the resolve.conf in another pod, just like my tomcat pod ,the detail of the resolve.conf in the tomcat pod is also "nameserver 172.17.0.1"

**Comment by Poorunga** [comment]
edged (kubelet-lite) copies the first three nameservers of /etc/resolv.conf on the host to /etc/resolv.conf in the pod

**Comment by pengbinbin1** [comment]
> edged (kubelet-lite) copies the first three nameservers of /etc/resolv.conf on the host to /etc/resolv.conf in the pod
ok ,so if the pod is created before the edgemesh-agent, then the  /etc/resolv.conf will be incorrect?

**Comment by Poorunga** [comment]
Yes, so edgemesh > 1.8 has been fixed this bug.

**Comment by pengbinbin1** [comment]
ok,thank you
