### ISSUE TITLE
bug: every informer runs twice

### ISSUE THREAD

**Issue by sdghchj** [kubeedge/edgemesh#320]
I am reading the source code, find that there is no need to traverse the informers to run, just [here](https://github.com/kubeedge/edgemesh/blob/62f6e4f145b81be872401e3b26323af16fa3a983/common/informers/informers.go#L85),
because every informer has a pointer copy in the SharedInformerFactory and when [runing the factory](https://github.com/kubeedge/edgemesh/blob/62f6e4f145b81be872401e3b26323af16fa3a983/common/informers/informers.go#L89), all the informers run.

that is to say , every informer runs twice.

So, we can remove the member `informers`  from struct `Manager`, it's useless.

**Comment by Poorunga** [comment]
Will this cause this warning log:
```
W0308 19:23:24.353318 2469356 shared_informer.go:372] The sharedIndexInformer has started, run more than once is not allowed
```

**Comment by sdghchj** [comment]
> Will this cause this warning log?
> 
> ```
> W0308 19:23:24.353318 2469356 shared_informer.go:372] The sharedIndexInformer has started, run more than once is not allowed
> ```

I am not sure. I just reviewed the code, have not run it yet.
