### ISSUE TITLE
Unable to access URL!! 

### ISSUE THREAD

**Issue by abhinavjha126** [kubeedge/edgemesh#335]
I am using Kubeedge version v1.8.1
---------------------------------
**GATEWAY**
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: edgemesh-gateway
  namespace: abcd
spec:
  selector:
    kubeedge: edgemesh-gateway
  servers:
    - hosts:
        - ‘app.mydomain.com’
      port:
        name: http-0
        number: 80
        protocol: HTTP
---------------------------------
**VIRTUAL SERVICE** 
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx
  namespace: abcd
spec:
  gateways:
  - edgemesh-gateway
  hosts:
  - app.mydomain.com
  http:
  - match:
    - uri:
        prefix: /app
    route:
    - destination:
        host: nginx-service
        port:
          number: 80
---------------------------------
**SERVICE**
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: abcd
spec:
  selector:
    app: nginx-server-deploy
  ports:
   - name: http-0
      port: 80
      protocol: TCP
      targetPort: 80
---------------------------------
NGINX DEPLOYMENT IS ALSO THERE.I AM UNABLE TO OPEN URL "http://app.mydomain.com/app"
NOTE:- prefix is added in virtualservice

**Comment by Poorunga** [comment]
> NGINX DEPLOYMENT IS ALSO THERE.I AM UNABLE TO OPEN URL "http://app.mydomain.com/app"

You need a DNS for domain name resolution, or you can configure domain name to IP mapping in /etc/hosts.

**Comment by abhinavjha126** [comment]
@Poorunga I have this domain open as "http://app.mydomain.com/" . Can i open different url's like "http://app.mydomain.com/app", "http://app.mydomain.com/mongo" from this by making virtual service???
