### ISSUE TITLE
Connection closed by foreign host

### ISSUE THREAD

**Issue by Banghao-BYR** [kubeedge/edgemesh#336]
测试edgemesh的时候云边通信案例，一直连接不上，请问怎么解决
<img width="614" alt="image" src="https://user-images.githubusercontent.com/71920251/161236660-d3c03f45-2668-4e9f-97bf-fa757e94510d.png">

**Comment by 8183736** [comment]
老哥怎么解决的

**Comment by 8183736** [comment]
> > 老哥怎么解决的
> 
> 重新安装了一下edgemesh

用的啥版本，我发现重装后还是会出现这个报错，但是使用ssh隧道登录又OK

**Comment by Piwriw** [comment]
怎么解决的，重装还是这个问题
