### ISSUE TITLE
有关 github 页面中相同局域网之间的边缘节点的直接通信的原理的疑惑

### ISSUE THREAD

**Issue by LOMOGO** [kubeedge/edgemesh#350]
**Which jobs are failing**:

**Which test(s) are failing**:
当我阅读贵项目的 github 页面的文档描述中有一项描述让我感到疑惑，即在描述 edgemesh 的优势部分时有这样的描写：
```shell
高可用性
利用 LibP2P 提供的能力，来打通边缘节点间的网络
将边缘节点间的通信分为局域网内和跨局域网
局域网内的通信：直接通信
跨局域网的通信：打洞成功时 Agent 之间建立直连通道，否则通过 Server 中继转发
```
您对边缘节点间通信分为了局域网和跨局域网，其中跨局域网的部分的通信原理我可以理解，但是我不理解局域网内的通信是直接通信这一描述。我对这直接通信的原理存在疑惑，即这些边缘节点之间是如何做到在没有类似 k8s 网络插件辅助的情况下实现直接通信的，原理是什么？如果把视野扩大一些，相同局域网中的不同节点（边云节点）间是如何通信的呢？
**Since when has it been failing**:

**Reason for failure**:

**Anything else we need to know**:
期待您的回复

**Comment by Poorunga** [comment]
直接通信的意思是，不需要打洞，两个edgemesh-agent本身就可以直接相连。

> 即这些边缘节点之间是如何做到在没有类似 k8s 网络插件辅助的情况下实现直接通信的，原理是什么？

通过建立一个p2p数据隧道，可以参考：https://docs.libp2p.io/concepts/transport/

> 相同局域网中的不同节点（边云节点）间是如何通信的呢？

也是通过p2p数据隧道通信

**Comment by LOMOGO** [comment]
> 直接通信的意思是，不需要打洞，两个edgemesh-agent本身就可以直接相连。
> 
> > 即这些边缘节点之间是如何做到在没有类似 k8s 网络插件辅助的情况下实现直接通信的，原理是什么？
> 
> 通过建立一个p2p数据隧道，可以参考：https://docs.libp2p.io/concepts/transport/
> 
> > 相同局域网中的不同节点（边云节点）间是如何通信的呢？
> 
> 也是通过p2p数据隧道通信

谢谢您的回复，帮助我解决了这个疑惑。另外对于您的回复，我是不是也可以这样理解：即相同局域网下的 edgemesh-server 与 edgemesh-agent 之间也是不需要打洞直接相连的。

**Comment by Poorunga** [comment]
> 即相同局域网下的 edgemesh-server 与 edgemesh-agent 之间也是不需要打洞直接相连的。

是的

**Comment by LOMOGO** [comment]
> > 即相同局域网下的 edgemesh-server 与 edgemesh-agent 之间也是不需要打洞直接相连的。
> 
> 是的

好的，再次谢谢您的回复
