### ISSUE TITLE
run lots of edgemesh-agent containerd in one edge node

### ISSUE THREAD

**Issue by songxiang93** [kubeedge/edgemesh#355]
when I run damonset of edgemesh-agent, It is giving me a headache。
Each edge node runs 7 containers of edgemesh-agent just like this :
I use "crictl ps in the edge node":

CONTAINER IMAGE CREATED STATE NAME ATTEMPT POD ID
5dca92111b73b 9d055bb5d3ee9 8 minutes ago Running edgemesh-agent 0 a2f7b509d6df3
c62c19758aec9 9d055bb5d3ee9 8 minutes ago Running edgemesh-agent 0 ed0cb92149286
136d52205f522 9d055bb5d3ee9 8 minutes ago Running edgemesh-agent 0 6c6d823ce753c
4660cc7b443dd 9d055bb5d3ee9 8 minutes ago Running edgemesh-agent 0 758a3a3467d72
dbc08f1694e3c 9d055bb5d3ee9 9 minutes ago Running edgemesh-agent 0 b2a8997ee9a5a
17708e057ceec 9d055bb5d3ee9 9 minutes ago Running edgemesh-agent 0 0d79b14253ed5
3b6497b273b4d 9d055bb5d3ee9 9 minutes ago Running edgemesh-agent 0 679cd0237169c

if I use "kubectl get pods -n kubeedge in k8s-master,we can see the ip of same value"

edgemesh-agent-7rg6q 1/1 Running 0 3m58s 172.26.43.46 terminal-00-e0-4c-68-59-04
edgemesh-agent-f7xlv 1/1 Running 0 3m58s 172.28.101.179 k8s-node2
edgemesh-agent-gj8bs 1/1 Running 0 3m58s 172.26.43.46 terminal-80-05-88-66-11-1d
edgemesh-agent-n8tjl 1/1 Running 0 3m58s 172.28.101.182 k8s-node3
edgemesh-agent-tlcr9 1/1 Running 0 3m58s 172.26.43.46 k8s-node4
edgemesh-agent-v5snt 1/1 Running 0 3m58s 172.26.43.46 terminal-00-e0-4c-68-59-0b
edgemesh-agent-vh9bw 1/1 Running 0 3m58s 172.26.43.46 terminal-30-0d-9e-3d-54-29
edgemesh-server-67874567d7-6knnj 1/1 Running 0 7m23s 172.28.101.179 k8s-node2

after I install edgemesh-agent in node,whenever I emit an image to an edge node, multiple identical containerd will be created in an edge node.

**Comment by ppt93** [comment]
![image](https://user-images.githubusercontent.com/106756188/171660082-755f2ec2-c6f2-41d4-81d6-9211a1bdfbb9.png)
![image](https://user-images.githubusercontent.com/106756188/171660299-96b17642-c16f-44d4-b1f9-1c3a4fbc71d3.png)
![image](https://user-images.githubusercontent.com/106756188/171660330-b8738ba8-6231-447b-bb99-462ee32b9b64.png)

**Comment by Poorunga** [comment]
This is a kubeedge/edgecore bug
