### ISSUE TITLE
Modify the deployment resource configuration，create a large number of edge pods

### ISSUE THREAD

**Issue by JiaweiGithub** [kubeedge/edgemesh#356]
**What happened**:
Modify the deployment resource configuration，create a large number of edge pods

**What you expected to happen**:
Create the correct number of edges

**How to reproduce it :
Change the configuration of the deployment, such as cpu, memory

**Anything else we need to know?**:
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/8078735/173173209-3b8db3e5-ff3f-4dc6-9d77-9371c800c7c5.png">

**Environment**:
 helm install edgemesh \
--set server.nodeName=k8s-node1 \
--set server.advertiseAddress="{xxx.xxx.xxx.xxx}" \
https://raw.githubusercontent.com/kubeedge/edgemesh/main/build/helm/edgemesh.tgz

k8s 1.20.5

**Comment by Poorunga** [comment]
Maybe a kubeedge bug, see issue: https://github.com/kubeedge/kubeedge/issues/3489
