### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 8183736** [kubeedge/edgemesh#361]
edgemesh-agent log:
root@ubuntu:~# docker logs -f 670d674efbdb
2022/06/24 17:12:22 INFO: Install client plugin, protocol: rest
2022/06/24 17:12:22 INFO: Installed service discovery plugin: edge
I0624 17:12:23.019276       1 server.go:55] Version: v1.10.0-12+597959bf325dbd-dirty
I0624 17:12:23.019337       1 server.go:89] [1] New informers manager
I0624 17:12:23.020340       1 server.go:96] [2] Prepare agent to run
I0624 17:12:23.020710       1 netif.go:98] bridge device edgemesh0 already exists
I0624 17:12:23.020860       1 server.go:100] edgemesh-agent running on EdgeMode
I0624 17:12:23.020874       1 server.go:110] [3] Register beehive modules
I0624 17:12:23.022232       1 module.go:34] Module edgedns registered successfully
I0624 17:12:23.223133       1 server.go:87] Using userspace Proxier.
I0624 17:12:23.508604       1 module.go:34] Module edgeproxy registered successfully
W0624 17:12:23.508670       1 module.go:37] Module edgegateway is disabled, do not register
I0624 17:12:23.508774       1 manager.go:33] Use noCaManager to handle security
I0624 17:12:23.508842       1 nocamanager.go:44] Private key exist, skip generate
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xf6ac34]

goroutine 1 [running]:
github.com/kubeedge/edgemesh/common/security.(*noCaManager).GetPrivateKey(0xc000347450)
	/code/common/security/nocamanager.go:73 +0xd4
github.com/kubeedge/edgemesh/agent/pkg/tunnel.newTunnelAgent(0xc00004f100, 0xc0000c6088, {0x22af4dc, 0xc00016a000})
	/code/agent/pkg/tunnel/module.go:54 +0x10e
github.com/kubeedge/edgemesh/agent/pkg/tunnel.Register(0xc00042a680, 0x0, {0x22af4dc, 0xc000337bc8})
	/code/agent/pkg/tunnel/module.go:103 +0x1e
github.com/kubeedge/edgemesh/agent/cmd/edgemesh-agent/app.registerModules(0xc00004f140, 0x1)
	/code/agent/cmd/edgemesh-agent/app/server.go:148 +0x2c5
github.com/kubeedge/edgemesh/agent/cmd/edgemesh-agent/app.Run(0xc00004f140)
	/code/agent/cmd/edgemesh-agent/app/server.go:111 +0x36b
github.com/kubeedge/edgemesh/agent/cmd/edgemesh-agent/app.NewEdgeMeshAgentCommand.func1(0xc000039680, {0x229dbe9, 0x0, 0x0})
	/code/agent/cmd/edgemesh-agent/app/server.go:56 +0x38b
github.com/spf13/cobra.(*Command).execute(0xc000039680, {0xc00010a1d0, 0x0, 0x0})
	/code/vendor/github.com/spf13/cobra/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000039680)
	/code/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/code/vendor/github.com/spf13/cobra/command.go:902
main.main()
	/code/agent/cmd/edgemesh-agent/agent.go:21 +0xc5

edgemesh-agent node:
操作系统版本:
Ubuntu 18.04.6 LTS
操作系统类型:
Linux
内核版本:
5.4.191-0504191-generic
容器运行时:
docker://20.10.14
kubelet 版本:
v1.21.4-kubeedge-v1.9.2
kube-proxy 版本:
系统架构:
AMD64

edgemesh-server  Version: v1.10.0-12+597959bf325dbd-dirty

container version:
edgemesh-server | kubeedge/edgemesh-server | v1.10.0-12-g597959b
edgemesh-agent | kubeedge/edgemesh-agent | v1.10.0-12-g597959b

**Comment by Poorunga** [comment]
Maybe a bug, we'll fix it
