### ISSUE TITLE
Edgemesh-server pod roaming between k8s node and edge node

### ISSUE THREAD

**Issue by shanchenggang** [kubeedge/edgemesh#365]
**What happened**:
edgemesh-server-** pod on K8s node roaming between k8s node and edge, edgemesh-server-** pod on edge encountered Error.
**What you expected to happen**:
Deploy edgemesh on my k8s1.19.6 + kubeedge1.9.1 and test Service function.

**Environment**:
- EdgeMesh version: 
- Kubernetes version (use `kubectl version`):1.19.6   one master + two k8s nodes + two edge nodes(Raspbettry Pi)
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 

![image](https://user-images.githubusercontent.com/46772842/184167173-64ed2b63-72c1-4b7a-be7a-b1f1ae356998.png)

**reporting a bug**
advertiseAddress: 192.168.0.161  nodeName: 192.168.0.161, edgeserver pod is deployed on K8s node1(192.168.0.161). However, after the Edge agents are deployed, Edgeserver drifts between the k8s node(192.168.0.161) and edge node(192.168.0.164) displays errors on the edge node. In addition, the name of the edge server pod is unique.

> 
![image](https://user-images.githubusercontent.com/46772842/184167697-00510c7e-8b95-46a2-8f61-f0e3a5670167.png)

The following photo presents logs in edgeserver.

> 
![image](https://user-images.githubusercontent.com/46772842/184170010-bf9bc18d-6f4e-4851-8047-4b1e0aa2b197.png)

In addition, the Pod iPs of Edge Agents seem to be confused.

> 
![image](https://user-images.githubusercontent.com/46772842/184171382-616b5c27-848a-44dd-bed3-ecff8f35c36f.png)

> Logs in edge agent on K8s master node(192.168.0.160):
![image](https://user-images.githubusercontent.com/46772842/184172166-5dd2f9e7-9692-4234-9e37-ce07283fed49.png)
Logs in edge agent on K8s node1 or node2 (192.168.0.161 or 192.168.0.162):
> 
![image](https://user-images.githubusercontent.com/46772842/184172559-1ffb77c2-d58a-487e-bb3f-5314914a5746.png)

>  Logs in edge agent on edge (192.168.0.164):
![image](https://user-images.githubusercontent.com/46772842/184172923-20e1ccb7-c3dd-4854-80d3-12e33cc1938e.png)

  </details>

**Comment by Poorunga** [comment]
This may be a known kubeedge issue. You can refer to: https://github.com/kubeedge/kubeedge/issues/3489

**Comment by shanchenggang** [comment]
i have looked up some issues: [https://github.com/kubeedge/kubeedge/issues/3489](url) , [https://github.com/kubeedge/kubeedge/pull/2808](url). It seems like that it has been solved in new version of Kubeedge. Subsequently, i try to install the latest KubeEdge version 1.11.1, but ecounter a new issue as follow: 

> edge nodes include 192.168.0.163 and 192.168.0.164.
![image](https://user-images.githubusercontent.com/46772842/186094037-2a102996-83bd-493a-b92d-92d83e066dad.png)
edgemesh server and edgemesh agents are deployed ad follows:
![image](https://user-images.githubusercontent.com/46772842/186094710-e88ca3a5-343b-48fe-b42a-d5650f7fcb12.png)
We observe that edgemesh agents on edges (192.168.0.163 and 192.168.0.164) are always in the form of "Pending".

Next i look up issues [https://github.com/kubeedge/edgemesh/issues/69](url), [https://github.com/kubeedge/kubeedge/issues/3108](url) and [https://github.com/kubeedge/kubeedge/issues/3019](url). And i still fail to find the solution.
Logs on 192.168.0.163:
![image](https://user-images.githubusercontent.com/46772842/186097413-0715c604-95c8-4968-8eda-af382c35a07d.png)
Logs on 192.168.0.164:
![image](https://user-images.githubusercontent.com/46772842/186097252-83c70cf4-12be-434a-9ae0-c69750873230.png)
The cloudcore.log on 192.168.0.160:
![image](https://user-images.githubusercontent.com/46772842/186098207-9a352058-05f0-4d96-9286-a7556fe7edb4.png)

I don't know how should I do next.

**Comment by shanchenggang** [comment]
Next, I tested Kubeedge V1.9.4, deployed Edgemesh, and found that edgemesh server and edgemesh agent worked fine.

> K8s master(192.168.0.160), nodes(192.168.0.161-162), edges(163 raspberry-arm32, 164 raspberry-arm64)
![image](https://user-images.githubusercontent.com/46772842/187104280-3dab761b-0cd6-4c02-8c24-451f9e23f801.png)

Meanwhile, new problems have arisen.

We cannot get edgemesh agent's logs on Edge.
![image](https://user-images.githubusercontent.com/46772842/187104534-925dae94-e8ac-4935-b62b-449df2e11155.png)

In addition, we deployed the application Pod workflow-0-task-1 on edge192.168.0.164. The three task pods (workflow-0-task-0, workflow-0-task-1, workflow-0-task-2) leverage the GRPC to communicate by obtaining a Service.
![image](https://user-images.githubusercontent.com/46772842/187104878-7d190a43-a28a-4198-954d-3dc40ebdcb12.png)

Issue 1: Kubectl logs cannot read the pod log for this Error pod.
![image](https://user-images.githubusercontent.com/46772842/187104988-5b43a3d5-e308-47e0-9c37-f9f519fb8f93.png)

Issue 2: The Service (task-SVC-1, 10.68.153.163:6060) corresponds to task pod on edge node 192.168.0.164. The task pod workflow-0-task-0 can not access task-svc-1 via gRPC.   In other words, Edgemesh fails to support Service fuction.

The following is logs on workflow-0-task-0.
![image](https://user-images.githubusercontent.com/46772842/187105594-93a6d17d-b8ed-442a-8a8c-091468aea5f0.png)

![image](https://user-images.githubusercontent.com/46772842/187105543-a3d7f5c9-1271-456a-b346-d54f7f1f0c56.png)

**Comment by Poorunga** [comment]
> Issue 1: Kubectl logs cannot read the pod log for this Error pod.

This has nothing to do with edgemesh, you need to enable the stream function of kubeedge. You can refer to: https://kubeedge.io/en/docs/advanced/debug

> Issue 2: The Service (task-SVC-1, 10.68.153.163:6060) corresponds to task pod on edge node 192.168.0.164. The task pod workflow-0-task-0 can not access task-svc-1 via gRPC. In other words, Edgemesh fails to support Service fuction.

Try to invoke your serivce by cluster ip like `telnet 10.68.153.163 6060` then show me some edgemesh-agent logs.

**Comment by shanchenggang** [comment]
type 'docker logs 330a76652689' on edge node(192.168.0.164) and show edgemesh-agent logs as follows.
![image](https://user-images.githubusercontent.com/46772842/187156604-e8905401-e189-4364-8022-af8ac1643b30.png)
![image](https://user-images.githubusercontent.com/46772842/187157034-0bb6d523-feb5-4a37-b15a-04aea365254e.png)

Invoke the Service task-svc-1 by cluster ip (10.68.114.62:6060) in workflow-0-task-0 on 192.168.0.161 and show logs of edge agent on 192.168.0.161.
![image](https://user-images.githubusercontent.com/46772842/187158962-91c7aef9-bde7-47c0-bd72-737dcaea709f.png)
![image](https://user-images.githubusercontent.com/46772842/187159021-35965500-7f47-4fa4-ae69-4670bbd64c49.png)

**Comment by Poorunga** [comment]
Impotant Error Info: dail tcp 127.0.0.1:10550

You need to enable your edgecore metaServer config.

**Comment by shanchenggang** [comment]
The log above is obtained after the edgecore metaServer config is enabled. In other words, the edgecore metaServer startup is not working.
![image](https://user-images.githubusercontent.com/46772842/187225581-00963dd6-37af-4633-8b46-56ae541fa53d.png)

**Comment by Poorunga** [comment]
> the edgecore metaServer startup is not working.

You can submit an issue to kubeedge repo.
