### ISSUE TITLE
Start stream server error listen tcp :10003: bind: address already in use

### ISSUE THREAD

**Issue by jason-i-vv** [kubeedge/edgemesh#370]
**edgemesh and cloudcore use same port, which case a CrashLoopBackOff to cloudcore**:

**Can I use other ports that don't affect cloudcore**:

**deploy edgemesh by helm , then i got the cloudcore's CrashLoopBackOff**:

```
Start stream server error listen tcp :10003: bind: address already in use
```

**Comment by Poorunga** [comment]
edgemesh doesn't listen on port 10003, maybe some other process?
