### ISSUE TITLE
 Observed a panic: "invalid memory address or nil pointer dereference" 

### ISSUE THREAD

**Issue by suojy** [kubeedge/edgemesh#371]
**What happened**:
edgemesh agent crashed and here is the log:
2022/09/06 15:41:40 INFO: Install client plugin, protocol: rest
2022/09/06 15:41:40 INFO: Installed service discovery plugin: edge
I0906 15:41:40.587035       1 server.go:55] Version: -dirty
I0906 15:41:40.587081       1 server.go:89] [1] New informers manager
I0906 15:41:40.587626       1 server.go:96] [2] Prepare agent to run
I0906 15:41:40.588048       1 netif.go:98] bridge device edgemesh0 already exists
I0906 15:41:40.588132       1 server.go:100] edgemesh-agent running on EdgeMode
I0906 15:41:40.588150       1 server.go:110] [3] Register beehive modules
I0906 15:41:40.589013       1 module.go:34] Module edgedns registered successfully
I0906 15:41:40.692096       1 server.go:87] Using userspace Proxier.
I0906 15:41:40.783583       1 module.go:34] Module edgeproxy registered successfully
W0906 15:41:40.783606       1 module.go:37] Module edgegateway is disabled, do not register
I0906 15:41:40.783698       1 manager.go:44] fetch token from /etc/kubeedge/cert/tokendata success
I0906 15:41:40.783727       1 manager.go:33] Use caManager to handle security
I0906 15:41:40.784072       1 camanager.go:86] security cert, key file already exist, skip generate
I0906 15:41:40.787753       1 module.go:86] Listening on /ip4/172.31.3.203/tcp/20006/p2p/QmPxzmpw5AcVZ1RCn4zgaLhjfUh11oYbLuz7ri2nRyjHiw
I0906 15:41:40.787969       1 module.go:86] Listening on /ip4/127.0.0.1/tcp/20006/p2p/QmPxzmpw5AcVZ1RCn4zgaLhjfUh11oYbLuz7ri2nRyjHiw
I0906 15:41:40.788049       1 module.go:34] Module tunnelagent registered successfully
I0906 15:41:40.788114       1 server.go:116] [4] Start informers manager
W0906 15:41:40.788830       1 shared_informer.go:372] The sharedIndexInformer has started, run more than once is not allowed
I0906 15:41:45.688483       1 server.go:120] [5] Start all modules
I0906 15:41:45.688618       1 core.go:24] Starting module edgedns
I0906 15:41:45.688668       1 core.go:24] Starting module edgeproxy
I0906 15:41:45.688657       1 module.go:65] Runs CoreDNS v1.8.7 as a local dns
I0906 15:41:45.688703       1 core.go:24] Starting module tunnelagent
W0906 15:41:45.689533       1 tunnel.go:28] Connection between agent and server [/ip4/100.101.239.199/tcp/20004 /ip4/127.0.0.1/tcp/20004 /ip4/100.200.8.147/tcp/20004 /ip4/10.110.21.41/tcp/20004] is not established, try connect
I0906 15:41:45.689558       1 tunnel.go:31] Tunnel agent connecting to tunnel server
I0906 15:41:45.691638       1 config.go:307] "Starting service config controller"
I0906 15:41:45.691660       1 shared_informer.go:240] Waiting for caches to sync for service config
I0906 15:41:45.691682       1 config.go:125] "Starting endpoints config controller"
I0906 15:41:45.691688       1 shared_informer.go:240] Waiting for caches to sync for endpoints config
I0906 15:41:45.691708       1 config.go:544] "Starting destination rule config controller"
I0906 15:41:45.691713       1 shared_informer.go:240] Waiting for caches to sync for destination rule config
I0906 15:41:45.707650       1 tunnel.go:50] agent success connected to server [/ip4/100.101.239.199/tcp/20004 /ip4/127.0.0.1/tcp/20004 /ip4/100.200.8.147/tcp/20004 /ip4/10.110.21.41/tcp/20004]
E0906 15:41:45.780680       1 loadbalancer_strategy.go:42] destination rule object cnp-system/apig-api-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780712       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780720       1 loadbalancer_strategy.go:42] destination rule object cnp-system/apm-service-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780724       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780730       1 loadbalancer_strategy.go:42] destination rule object cnp-system/nexus-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780733       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780738       1 loadbalancer_strategy.go:42] destination rule object cnp-system/sonarqube-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780741       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780746       1 loadbalancer_strategy.go:42] destination rule object cnp-system/cam-api-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780749       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780754       1 loadbalancer_strategy.go:42] destination rule object cnp-system/cnp-insight .Spec.TrafficPolicy is nil
E0906 15:41:45.780757       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780762       1 loadbalancer_strategy.go:42] destination rule object cnp-system/keycloak-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780765       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780769       1 loadbalancer_strategy.go:42] destination rule object cnp-system/cks-rudder-api-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780772       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780776       1 loadbalancer_strategy.go:42] destination rule object cnp-system/ens-api-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780779       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780783       1 loadbalancer_strategy.go:42] destination rule object cnp-system/iam-auth-ladon-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780785       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780791       1 loadbalancer_strategy.go:42] destination rule object cnp-system/oap-server .Spec.TrafficPolicy is nil
E0906 15:41:45.780794       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780798       1 loadbalancer_strategy.go:42] destination rule object cnp-system/ocm-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780800       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780805       1 loadbalancer_strategy.go:42] destination rule object cnp-system/cad-api-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780808       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780812       1 loadbalancer_strategy.go:42] destination rule object cnp-system/cls-service-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780815       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780819       1 loadbalancer_strategy.go:42] destination rule object cnp-system/cms-service-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780822       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780826       1 loadbalancer_strategy.go:42] destination rule object cnp-system/cnp-insight-config .Spec.TrafficPolicy is nil
E0906 15:41:45.780828       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780833       1 loadbalancer_strategy.go:42] destination rule object cnp-system/gitea-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780836       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780840       1 loadbalancer_strategy.go:46] destination rule object cnp-system/multi-cluster-dr .Spec.TrafficPolicy.LoadBalancer is nil
E0906 15:41:45.780845       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780850       1 loadbalancer_strategy.go:42] destination rule object cnp-system/webshell .Spec.TrafficPolicy is nil
E0906 15:41:45.780853       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780857       1 loadbalancer_strategy.go:42] destination rule object cnp-system/ice-api-cnp .Spec.TrafficPolicy is nil
E0906 15:41:45.780860       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780866       1 loadbalancer_strategy.go:42] destination rule object cnp-system/cdr-api-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780869       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780873       1 loadbalancer_strategy.go:42] destination rule object cnp-system/cicd-api-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780876       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780880       1 loadbalancer_strategy.go:42] destination rule object cnp-system/mse-api-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780883       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780887       1 loadbalancer_strategy.go:42] destination rule object cnp-system/rds-mysql-api-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780889       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780894       1 loadbalancer_strategy.go:42] destination rule object cnp-system/kubegems .Spec.TrafficPolicy is nil
E0906 15:41:45.780897       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780901       1 loadbalancer_strategy.go:42] destination rule object cnp-system/websocket-service-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780904       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780908       1 loadbalancer_strategy.go:42] destination rule object cnp-system/cir-api-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780911       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780915       1 loadbalancer_strategy.go:42] destination rule object cnp-system/cnp-insight-collector .Spec.TrafficPolicy is nil
E0906 15:41:45.780917       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780922       1 loadbalancer_strategy.go:42] destination rule object cnp-system/dts-service-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780925       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:45.780928       1 loadbalancer_strategy.go:42] destination rule object cnp-system/icv-api-canary .Spec.TrafficPolicy is nil
E0906 15:41:45.780931       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
I0906 15:41:45.791898       1 shared_informer.go:247] Caches are synced for destination rule config 
I0906 15:41:45.892631       1 shared_informer.go:247] Caches are synced for endpoints config 
I0906 15:41:46.079100       1 shared_informer.go:247] Caches are synced for service config 
E0906 15:41:46.186359       1 loadbalancer_strategy.go:42] destination rule object cnp-system/webshell .Spec.TrafficPolicy is nil
E0906 15:41:46.186381       1 loadbalancer_ex.go:464] unsupported or empty load-balance strategy 
E0906 15:41:46.186497       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 218 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1f63860, 0x3a475d0})
        /code/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000018750})
        /code/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1f63860, 0x3a475d0})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/kubeedge/edgemesh/third_party/forked/kubernetes/pkg/proxy/userspace.(*LoadBalancerEX).OnDestinationRuleUpdate(0xc000018750, 0x0, 0xc0006981e0)
        /code/third_party/forked/kubernetes/pkg/proxy/userspace/loadbalancer_ex.go:435 +0x298
github.com/kubeedge/edgemesh/third_party/forked/kubernetes/pkg/proxy/userspace.(*Proxier).OnDestinationRuleUpdate(0x5, 0xc000018750, 0xc000069800)
        /code/third_party/forked/kubernetes/pkg/proxy/userspace/proxier.go:696 +0x22
github.com/kubeedge/edgemesh/third_party/forked/kubernetes/pkg/proxy/config.(*DestinationRuleConfig).handleUpdateDestinationRule(0xc0002599c0, {0x2254c60, 0xc00046f130}, {0x2254c60, 0xc0006981e0})
        /code/third_party/forked/kubernetes/pkg/proxy/config/config.go:581 +0x13b
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        /code/vendor/k8s.io/client-go/tools/cache/controller.go:238
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /code/vendor/k8s.io/client-go/tools/cache/shared_informer.go:785 +0x127
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f53341429c8)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00002e738, {0x26b1340, 0xc001ae63c0}, 0x1, 0xc001ae8360)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x811080, 0x3b9aca00, 0x0, 0xf, 0xc00002e788)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000668480)
        /code/vendor/k8s.io/client-go/tools/cache/shared_informer.go:781 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x88
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1ccdd98]

goroutine 218 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000018750})
        /code/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x1f63860, 0x3a475d0})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/kubeedge/edgemesh/third_party/forked/kubernetes/pkg/proxy/userspace.(*LoadBalancerEX).OnDestinationRuleUpdate(0xc000018750, 0x0, 0xc0006981e0)
        /code/third_party/forked/kubernetes/pkg/proxy/userspace/loadbalancer_ex.go:435 +0x298
github.com/kubeedge/edgemesh/third_party/forked/kubernetes/pkg/proxy/userspace.(*Proxier).OnDestinationRuleUpdate(0x5, 0xc000018750, 0xc000069800)
        /code/third_party/forked/kubernetes/pkg/proxy/userspace/proxier.go:696 +0x22
github.com/kubeedge/edgemesh/third_party/forked/kubernetes/pkg/proxy/config.(*DestinationRuleConfig).handleUpdateDestinationRule(0xc0002599c0, {0x2254c60, 0xc00046f130}, {0x2254c60, 0xc0006981e0})
        /code/third_party/forked/kubernetes/pkg/proxy/config/config.go:581 +0x13b
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        /code/vendor/k8s.io/client-go/tools/cache/controller.go:238
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /code/vendor/k8s.io/client-go/tools/cache/shared_informer.go:785 +0x127
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f53341429c8)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00002e738, {0x26b1340, 0xc001ae63c0}, 0x1, 0xc001ae8360)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x811080, 0x3b9aca00, 0x0, 0xf, 0xc00002e788)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000668480)
        /code/vendor/k8s.io/client-go/tools/cache/shared_informer.go:781 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x88

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version: v1.10.0
- Kubernetes version (use `kubectl version`):v1.20.13
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):v1.10.0
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
Can show your destinationrule yaml file?

**Comment by jianzs** [comment]
Same problem. Any help? 

```
E0403 01:54:08.420589       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 163 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2071e60, 0x3d532c0})
        /code/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0005440c0})
        /code/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x2071e60, 0x3d532c0})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/kubeedge/edgemesh/pkg/loadbalancer.(*LoadBalancer).OnDestinationRuleDelete(0xc000544080, 0xc004596780)
        /code/pkg/loadbalancer/loadbalancer.go:558 +0x205
github.com/kubeedge/edgemesh/pkg/loadbalancer.(*LoadBalancer).handleDeleteDestinationRule(0x0, {0x237e500, 0xc004596780})
        /code/pkg/loadbalancer/loadbalancer.go:283 +0x7b
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
        /code/vendor/k8s.io/client-go/tools/cache/controller.go:245
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /code/vendor/k8s.io/client-go/tools/cache/shared_informer.go:789 +0xdf
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fef158d1a00)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006fd738, {0x292b8a0, 0xc00179e000}, 0x1, 0xc001434300)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00088a008, 0x3b9aca00, 0x0, 0x8, 0x22863a0)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0006c9f00)
        /code/vendor/k8s.io/client-go/tools/cache/shared_informer.go:781 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x88
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1d78365]

goroutine 163 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0005440c0})
        /code/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x2071e60, 0x3d532c0})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/kubeedge/edgemesh/pkg/loadbalancer.(*LoadBalancer).OnDestinationRuleDelete(0xc000544080, 0xc004596780)
        /code/pkg/loadbalancer/loadbalancer.go:558 +0x205
github.com/kubeedge/edgemesh/pkg/loadbalancer.(*LoadBalancer).handleDeleteDestinationRule(0x0, {0x237e500, 0xc004596780})
        /code/pkg/loadbalancer/loadbalancer.go:283 +0x7b
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
        /code/vendor/k8s.io/client-go/tools/cache/controller.go:245
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /code/vendor/k8s.io/client-go/tools/cache/shared_informer.go:789 +0xdf
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fef158d1a00)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006fd738, {0x292b8a0, 0xc00179e000}, 0x1, 0xc001434300)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00088a008, 0x3b9aca00, 0x0, 0x8, 0x22863a0)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0006c9f00)
        /code/vendor/k8s.io/client-go/tools/cache/shared_informer.go:781 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /code/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x88
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: APP_NAME
spec:
  host: APP_NAME
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
```

**Comment by Poorunga** [comment]
Is this a must-have question? Can you describe the procedure for reproducing the problem? @jianzs
