### ISSUE TITLE
edgemesh server AdvertiseAddress support dns

### ISSUE THREAD

**Issue by fridayhub** [kubeedge/edgemesh#373]
**What would you like to be added/modified**:
edgemesh server AdvertiseAddress support dns

**Why is this needed**:
if edgemesh server behind the elb or have multi node, server need expose domain for agent.

**Comment by Poorunga** [comment]
This is indeed a feature worth supporting. 
At present, the modification method can be obtained from https://github.com/multiformats/go-multiaddr:
```
/dns4/www.domain.com/tcp/6713
```
