### ISSUE TITLE
coredns解析外部域名使用TCP和UDP协议转发至上游dns服务器

### ISSUE THREAD

**Issue by cheng-hunter** [kubeedge/edgemesh#374]
**What would you like to be added/modified**:
**当前代码**
![img](https://raw.githubusercontent.com/cheng-hunter/image/main/image4.png)
**修改代码**
  forward . {{.UpstreamServers}} {
        prefer_udp
  }
附coredns部分代码1
![img](https://raw.githubusercontent.com/cheng-hunter/image/main/image5.png)
附coredns部分代码2
![img](https://raw.githubusercontent.com/cheng-hunter/image/main/image6.png)

**Why is this needed**:
dns一般开放udp 53,也有部分时tcp/udp 53, 这样优先使用udp, udp失败时使用tcp，而不是强制使用tcp

**Comment by Poorunga** [comment]
这样的修改是可以的，你看能不能将你的修改提交成PR
