### ISSUE TITLE
Cross-Edge-Cloud communication between pods failed

### ISSUE THREAD

**Issue by zz952332446** [kubeedge/edgemesh#379]
## version
kubeedge:1.8.2
edgemesh: edgemesh (installed by kubectl apply)
* kube-proxy has been banned on the edge

![image](https://user-images.githubusercontent.com/34162360/192232201-32067097-076b-4c00-941a-8b5bf6f4bc62.png)

![image](https://user-images.githubusercontent.com/34162360/192230048-dbed6234-91bc-412a-9d00-d18ae52ee922.png)

## issue
When I deploy the case according to [Cross-Edge-Cloud](https://edgemesh.netlify.app/guide/test-case.html#cross-edge-cloud), the pod on the cloud can't communicate with the pod on the edge

on my cloud xzc-master:
![image](https://user-images.githubusercontent.com/34162360/192231911-5dbaa80c-4a24-435f-80c2-ea351c8984b1.png)

on my agent wspn2:
![image](https://user-images.githubusercontent.com/34162360/192236967-96130502-c85c-42cb-b226-b32007d2a181.png)

### logs of edgemesh agent on the cloud
![image](https://user-images.githubusercontent.com/34162360/192231869-fe240aff-8b88-48ae-b1db-a0b4a20d86b1.png)

### logs of edgemesh agent on the edge
![image](https://user-images.githubusercontent.com/34162360/192236787-2fe39368-039e-498a-a110-505c93c632fa.png)

### deployments checks
![image](https://user-images.githubusercontent.com/34162360/192231008-a485c429-dd6d-4a29-b3ac-48265d6e10cb.png)

![image](https://user-images.githubusercontent.com/34162360/192231075-7c721b31-7d3d-4685-8f39-41f0eba0a90e.png)

### chain built by edgemesh on the cloud
![image](https://user-images.githubusercontent.com/34162360/192231455-eb03c70b-438c-469c-b45e-0deb817ac583.png)

**Comment by Poorunga** [comment]
How does the command you install with helm look like?

**Comment by zz952332446** [comment]
> How does the command you install with helm look like?

helm install edgemesh --set server.nodeName=master’s name --set server.publicIP=Public IP https://raw.githubusercontent.com/kubeedge/edgemesh/main/build/helm/edgemesh.tgz

**Comment by zz952332446** [comment]
> How does the command you install with helm look like?

![C3E4ED50-F364-417A-AF4A-A626B5D96D73](https://user-images.githubusercontent.com/34162360/192287787-cde7629e-8da7-49e8-994a-68eee44069c1.png)

**Comment by Poorunga** [comment]
helm install --set agent.image=kubeedge/edgemesh-agent:v1.9.0

**Comment by zz952332446** [comment]
I solve this problem
first, I didn't notice that the installation of helm is diffenrent from the ago version
second,  in [manual installation](https://edgemesh.netlify.app/guide/#manual-installation) , I didn't set the relayNodes in build/agent/resources/04-configmap.yaml 

Now, I use  [manual installation](https://edgemesh.netlify.app/guide/#manual-installation)  to set the edgemesh, and the Cross-Edge-Cloud communication between pods is okay~
