### ISSUE TITLE
Session Persistence can't use when transport http data through tcp

### ISSUE THREAD

**Issue by ZBoIsHere** [kubeedge/edgemesh#38]
**What happened**:
Session Persistence can not work after transport http data through tcp
**What you expected to happen**:
Session Persistence can work well
**How to reproduce it (as minimally and precisely as possible)**:
create a deployment contains three http server
create a service associate with this three pods
create a destination rule associate with this service and the load balance policy set as consistent hash
**Anything else we need to know?**:

**Environment**:
- EdgeMesh version:
- Kubernetes version (use `kubectl version`):
- 1.20.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- 1.7.1
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
/close

fix in pr #113
