### ISSUE TITLE
virtual service can not use when transport http data through tcp

### ISSUE THREAD

**Issue by ZBoIsHere** [kubeedge/edgemesh#39]
**What happened**:
virtual service can not use when transport http data through tcp
if virtual service associate one more service, the traffic only redirect to the first service
**What you expected to happen**:
virtual service can work well
**How to reproduce it (as minimally and precisely as possible)**:
create deploymentA contains 3 http serverA
create deploymentB contains 3 http serverB
create serviceA associate 3 http serverA pods
create serviceB associate 3 http serverB pods
create gateway
create virtualservice, pathA redirect traffic to serviceA, pathB redirect traffic to serviceB
**Anything else we need to know?**:

**Environment**:
- EdgeMesh version:
- 1.7.1
- Kubernetes version (use `kubectl version`):
- 1.20.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- 1.7.1
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
/close

fix in pr #113
