### ISSUE TITLE
Installation failed. Some nodes start successfully and some fail

### ISSUE THREAD

**Issue by 916264367** [kubeedge/edgemesh#392]
**What happened**:
The installation method of edgemesh seems to have changed.
I followed the tutorial at this URL to install “https://edgemesh.netlify.app/zh/”. I set the relayNodes in the 04-configmap.yaml file according to the tutorial:
![image](https://user-images.githubusercontent.com/51771785/195795670-897de09e-96f9-467b-b79f-2945f4d680ab.png)
But after installation some POD are not started as expected:
![image](https://user-images.githubusercontent.com/51771785/195796826-4815e73a-dc45-486d-acd0-08ff6e62095c.png)
I checked the logs:
![image](https://user-images.githubusercontent.com/51771785/195797608-86b6a5d3-b828-41bd-8f05-66f2e4f1f0f7.png)
What I don't understand is why edge-node-2 works and the others fail?
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Write any information you need in the comments and I will provide it
**Environment**:
- EdgeMesh version: Latest
- Kubernetes version (use `kubectl version`): 1.21.3
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.10.0
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
use `docker logs xxx` print some edgemesh-agent log

**Comment by 916264367** [comment]
> use `docker logs xxx` print some edgemesh-agent log
This is Docker's log
![image](https://user-images.githubusercontent.com/51771785/196324222-e163042b-5a75-4036-bc56-1ffcedeb8b13.png)
The errors in logs are the same regardless of the master node or edge node.

**Comment by Poorunga** [comment]
please use edgemesh-agent v1.12.0

**Comment by 916264367** [comment]
> https://edgemesh.netlify.app/zh/



> please use edgemesh-agent v1.12.0
It is working. Thank you very much!

**Comment by qimiao1** [comment]
> please use edgemesh-agent v1.12.0

hello, I hava encount this problem too. but it still not works by using edgemesh-agent v1.12.0. How can I fix it?

**Comment by qimiao1** [comment]
> please use edgemesh-agent v1.12.0

do you hava the install guide for the version before v1.12.0?

**Comment by Poorunga** [comment]
An example:
```
$ git clone https://github.com/kubeedge/edgemesh.git
$ cd edgemesh
$ git checkout v1.11.0
$ helm install edgemesh \
--set agent.image=kubeedge/edgemesh-agent:v1.11.0 \
--set server.image=kubeedge/edgemesh-server:v1.11.0 \
--set server.nodeName=k8s-node1 \
--set server.advertiseAddress="{119.8.211.54}" ./build/helm/edgemesh
```

**Comment by qimiao1** [comment]
> An example:
> 
> ```
> $ git clone https://github.com/kubeedge/edgemesh.git
> $ cd edgemesh
> $ git checkout v1.11.0
> $ helm install edgemesh \
> --set agent.image=kubeedge/edgemesh-agent:v1.11.0 \
> --set server.image=kubeedge/edgemesh-server:v1.11.0 \
> --set server.nodeName=k8s-node1 \
> --set server.advertiseAddress="{119.8.211.54}" ./build/helm/edgemesh
> ```

Thank you very much!
