### ISSUE TITLE
Version selection problem

### ISSUE THREAD

**Issue by x810366146** [kubeedge/edgemesh#393]
K8s version: 1.17
kubeedge version: 1.9.2
docker version: 18.06.3-ce
I would like to ask which version of edgemesh should I select?

**Comment by Poorunga** [comment]
v1.12.0 is good for you

**Comment by x810366146** [comment]
> v1.12.0 is good for you

thanks, i'll try this version!

**Comment by qimiao1** [comment]
> v1.12.0 is good for you

hello，I try the v1.12.0,but I have met the problem.
2022/10/22 14:55:28 INFO: Install client plugin, protocol: rest
2022/10/22 14:55:28 INFO: Installed service discovery plugin: edge
F1022 14:55:28.667153       1 util.go:82] env MY_NODE_NAME not exist
could  you help me ?

**Comment by Poorunga** [comment]
@qimiao1 

EdgeMesh < v1.12
1.需要部署edgemesh-server和edgemesh-agent两个组件
2.配置文件在`/etc/kubeedge/config`目录下，环境变量叫`MY_NODE_NAME`

EdgeMesh >= v1.12 (包括latest)
1.只需要部署edgemesh-agent
2.配置文件在`/etc/edgemesh/config`目录下，环境变量叫`NODE_NAME`

---

EdgeMesh < v1.12
1. Two components, edgemesh-server and edgemesh-agent, need to be deployed
2. The configuration file is in `/etc/kubeedge/config`, and the environment variable is named `MY_NODE_NAME`

EdgeMesh > v1.12 (including latest)
1. Only need to deploy edgemesh-agent
2. The configuration file is in `/etc/edgemesh/config`, and the environment variable is named `NODE_NAME`
