### ISSUE TITLE
edgemesh-agent CrashLoopBackOff util.go:82] env MY_NODE_NAME not exist

### ISSUE THREAD

**Issue by q77190858** [kubeedge/edgemesh#395]
**What happened**:
I use helm to deploy edgemesh:latest, but the pod edgemesh-agent CrashLoopBackOff in both master and edgenode
and the kubectl logs info of  edgemesh-agent pod in master is 
```bash
root@master:~# kubectl logs pod/edgemesh-agent-rntxx -nkubeedge
2022/10/23 12:47:55 INFO: Install client plugin, protocol: rest
2022/10/23 12:47:55 INFO: Installed service discovery plugin: edge
F1023 12:47:55.184364       1 util.go:82] env MY_NODE_NAME not exist
```
and I cannot connect to edge node using kubectl logs because edgemesh agent crash
 
**What you expected to happen**:
edgemesh agent in master and edgenode shuold work well
**How to reproduce it (as minimally and precisely as possible)**:
I use ubuntu20.04
kubernetes1.22.6
kubeedge 1.12.0
edgemesh:latest from https://raw.githubusercontent.com/kubeedge/edgemesh/main/build/helm/edgemesh.tgz
**Anything else we need to know?**:
no
**Environment**:
- EdgeMesh version:edgemesh:latest from https://raw.githubusercontent.com/kubeedge/edgemesh/main/build/helm/edgemesh.tgz
- Kubernetes version (use `kubectl version`):kubernetes1.22.6
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):kubeedge 1.12.0
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
    - OS (e.g. `cat /etc/os-release`):ubuntu20.04
    - Kernel (e.g. `uname -a`):Linux master 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
    - Go version (e.g. `go version`):there is no golang
    - Others:master is a cloud ECS

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):v1.12.0
    - Hardware configuration (e.g. `lscpu`):12th Gen Intel(R) Core(TM) i7-12700F
    - OS (e.g. `cat /etc/os-release`):Ubuntu 20.04.5 LTS
    - Kernel (e.g. `uname -a`):Linux edgenode1 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
    - Go version (e.g. `go version`):no golang
    - Others:

  </details>

**Comment by q77190858** [comment]
I found the cause of this problem.
I using a aliyun dockerhub mirrors, but the kubeedge/edgemesh-agent image is 9 months old.
I chang to dockhub official source and pull the real latest kubeedge/edgemesh-agent image.
Now everything is ok

**Comment by qimiao1** [comment]
> 

hello, I have met the same problem ,and I try to sovle this problem by your method. But it is still wrong.
the logs show that  :    env MY_NODE_NAME not exist

**Comment by Poorunga** [comment]
use `helm install edgemesh --set agent.image=kubeedge/edgemesh-agent:v1.11.0 --set server.image=kubeedge/edgemesh-server:v1.11.0 xxxx`

**Comment by Poorunga** [comment]
EdgeMesh < v1.12
1.需要部署edgemesh-server和edgemesh-agent两个组件
2.配置文件在`/etc/kubeedge/config`目录下，环境变量叫`MY_NODE_NAME`

EdgeMesh > v1.12 (包括latest)
1.只需要部署edgemesh-agent
2.配置文件在`/etc/edgemesh/config`目录下，环境变量叫`NODE_NAME`

---

EdgeMesh < v1.12
1. Two components, edgemesh-server and edgemesh-agent, need to be deployed
2. The configuration file is in `/etc/kubeedge/config`, and the environment variable is named `MY_NODE_NAME`

EdgeMesh > v1.12 (including latest)
1. Only need to deploy edgemesh-agent
2. The configuration file is in `/etc/edgemesh/config`, and the environment variable is named `NODE_NAME`

**Comment by qimiao1** [comment]
> EdgeMesh < v1.12 1.需要部署edgemesh-server和edgemesh-agent两个组件 2.配置文件在`/etc/kubeedge/config`目录下，环境变量叫`MY_NODE_NAME`
> 
> EdgeMesh >= v1.12 (包括latest) 1.只需要部署edgemesh-agent 2.配置文件在`/etc/edgemesh/config`目录下，环境变量叫`NODE_NAME`
> 
> EdgeMesh < v1.12
> 
> 1. Two components, edgemesh-server and edgemesh-agent, need to be deployed
> 2. The configuration file is in `/etc/kubeedge/config`, and the environment variable is named `MY_NODE_NAME`
> 
> EdgeMesh > v1.12 (including latest)
> 
> 1. Only need to deploy edgemesh-agent
> 2. The configuration file is in `/etc/edgemesh/config`, and the environment variable is named `NODE_NAME`

非常感谢您的解答，但是我这里还是有点小问题，请问能加您的微信请教一下吗，或者您看您什么时候有空，可以腾讯会议帮我解答一下吗？有个小问题困扰我一个星期了，必将万分感谢！我的微信号15139065152

**Comment by Poorunga** [comment]
@qimiao1 已加
