### ISSUE TITLE
【边缘网关问题】当出现混合路由时，边缘网关edgemesh-gateway无法正确路由的Bug

### ISSUE THREAD

**Issue by qa137** [kubeedge/edgemesh#396]
在同时访问例如 http://192.168.0.100/welcome 和 http://192.168.0.100/api/welcome 的时候，网关路由会识别失败。要么都路由到/welcome，要么都路由到/api/welcome。而且VirtualService的prefix前缀匹配也匹配不正确，例如/api/welcome能够识别，但/api/welcome/menuInfo就会失败。

**以下是VirtualService的配置**
<img width="541" alt="截屏2022-10-25 上午1 22 35" src="https://user-images.githubusercontent.com/3113623/197589013-af6c0d9b-59b9-47cd-8bf3-768181fbac8a.png">
<img width="488" alt="截屏2022-10-25 上午1 22 25" src="https://user-images.githubusercontent.com/3113623/197589019-3884e1a7-9c65-4516-aeb7-d3e4e4f5c45f.png">

该配置在istio中正常，在edgemesh-gateway中却会出现异常情况，极度不稳定。
/welcome：为nginx程序
/api/welcome：为springboot程序

**Comment by qa137** [comment]
@Poorunga 麻烦帮忙看一下，谢谢

**Comment by qa137** [comment]
感谢大佬回复，版本是：
**kubeedge 1.9.2
edgemesh 1.12.0**

页面不停刷新，基本都会出现无法找到svc的情况，网关基本没法用

**Comment by Poorunga** [comment]
请再提供一些edgemesh-agent和edgemesh-gateway的日志信息

**Comment by qa137** [comment]
[edgemesh-gateway.log](https://github.com/kubeedge/edgemesh/files/9908765/edgemesh-gateway.log)
[edgemesh-agent.log](https://github.com/kubeedge/edgemesh/files/9908766/edgemesh-agent.log)
@Poorunga 麻烦看看

**Comment by Poorunga** [comment]
service和 virtualserver目前来说，必须在同一个k8s namespace下面

**Comment by qa137** [comment]
是的，service和 virtualservice是在同一目录下面。但是virtualservice还是不能够准确的路由到service下面，时不时出现无法找到svc的情况。同样的virtualservice在istio能够正常路由，edgemesh就是出现问题

**Comment by Poorunga** [comment]
这个官方示例能运行成功吗？  https://github.com/kubeedge/edgemesh/blob/main/examples/hostname-lb-random-gateway-route.yaml
