### ISSUE TITLE
edgemesh/build/helm/edgemesh/charts/server/ missing from release 1.12

### ISSUE THREAD

**Issue by ageoffron** [kubeedge/edgemesh#398]
**What happened**:
edgemesh/build/helm/edgemesh/charts/server/ missing from release 1.12

**What you expected to happen**:
edgemesh/build/helm/edgemesh/charts/server/  to be present
I can't find documentation, or release notes indicating that the edgemesh server is not necessary starting release 1.12

**How to reproduce it (as minimally and precisely as possible)**:
n/a
**Anything else we need to know?**:
n/a

**Environment**:
- EdgeMesh version: 1.12
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by ageoffron** [comment]
While 1.11 was calling for a server , 1.12 has full mesh and uses an elected agent as relay via its config.
Issue is when deploying this on top kubeedge with a cloud managed service such as aks. I need to add a service to expose the tunnel port for the agent running in the cloud..

**Comment by Poorunga** [comment]
> I can't find documentation, or release notes indicating that the edgemesh server is not necessary starting release 1.12

edgemesh <= v1.11
```
$ git clone https://github.com/kubeedge/edgemesh.git
$ cd edgemesh
$ git checkout v1.11.0
$ helm install edgemesh \
--set agent.image=kubeedge/edgemesh-agent:v1.11.0 \
--set server.image=kubeedge/edgemesh-server:v1.11.0 \
--set server.nodeName=k8s-node1 \
--set server.advertiseAddress="{119.8.211.54}" ./build/helm/edgemesh
```

edgemesh == v1.12
```
$ git clone https://github.com/kubeedge/edgemesh.git
$ cd edgemesh
$ git checkout v1.12.0
$ helm install edgemesh --namespace kubeedge \
--set agent.image=kubeedge/edgemesh-agent:v1.12.0 \
--set agent.relayNodes[0].nodeName=k8s-node1,agent.relayNodes[0].advertiseAddress="{119.8.211.54,2.2.2.2}" \
./build/helm/edgemesh
```

**Comment by ageoffron** [comment]
thank you
I did find some minor mention in the README.MD

"After EdgeMesh v1.12.0, the capabilities of edgemesh-server are merged into the tunnel module of edgemesh-agent, so that edgemesh-agent with relay capability can automatically become a relay server, providing other nodes with the functions of assisting hole punching and relaying"

This has interesting implications. I was using kubeedge/edgemesh with AKS somewhat successfully. With 1.12 however I need to pin the agent with a relay role to a cloud node, as this is where I need to expose that agent publically via a public load balancer.

None of the example seem to show that scenario, wonder if anyone as any input...

**Comment by Poorunga** [comment]
> This has interesting implications. I was using kubeedge/edgemesh with AKS somewhat successfully. With 1.12 however I need to pin the agent with a relay role to a cloud node, as this is where I need to expose that agent publically via a public load balancer.

Do you mean that in EdgeMesh < 1.12, you will configure a public load balancer for edgemesh-server?

**Comment by ageoffron** [comment]
That is correct. when using edgemesh 1.11. We setup a  load balancer service type to expose the edgemesh server workload running on AKS via public ip. So that our physical edge nodes with edgemesh agent can connect. We did the same deployment for kubeedge.

**Comment by Poorunga** [comment]
A suggestion, you use a separate deployment to deploy an edgemesh-agent that can act as a relay, and the remaining nodes deploy edgemesh-agent with a daemoneSet, make sure they use the same configuration files(edgemesh-agent-cfg) and PSK cipher

**Comment by ageoffron** [comment]
Thanks make sense. I was hoping to not deviate too much from current helm chart but I'll plan to do just that.
