### ISSUE TITLE
【部署安装问题】edgemesh:v1.12.0手动配置部署失败

### ISSUE THREAD

**Issue by SakuraWh** [kubeedge/edgemesh#403]
**【问题】**
根据 [edgemesh手动部署](https://edgemesh.netlify.app/zh/guide/#%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85) 快速上手进行v1.12.0版本安装出现问题
![image](https://user-images.githubusercontent.com/44866092/202382747-df120863-840a-4776-b81e-91ab662f4bb8.png)

![image](https://user-images.githubusercontent.com/44866092/202382649-2572e1dc-99e0-48db-ab8e-7ba6ec5e90ef.png)

**【原因】镜像错误**
![image](https://user-images.githubusercontent.com/44866092/202383165-e7e966ab-8ba4-435c-83a9-5694f70a7ba5.png)

![image](https://user-images.githubusercontent.com/44866092/202383344-0312b89d-a0de-4269-bbfa-aece0f152a2b.png)

**【解决方案】**
指定daemonset.yaml配置文件版本
` image: kubeedge/edgemesh-agent:v1.12.0 `

**【建议】**
及时修改镜像源

**Comment by SakuraWh** [comment]
@Poorunga

**Comment by Poorunga** [comment]
edgemesh-agent的latest镜像非最新，通过指定helm版本解决，参考下方示例：

如果选用的EdgeMesh版本 == v1.12.0
```
$ helm install edgemesh --namespace kubeedge \
--set agent.image=kubeedge/edgemesh-agent:v1.12.0 \
--set agent.relayNodes[0].nodeName=k8s-node1,agent.relayNodes[0].advertiseAddress="{119.8.211.54,2.2.2.2}" \
https://raw.githubusercontent.com/kubeedge/edgemesh/release-1.12/build/helm/edgemesh.tgz
```

如果选用的EdgeMesh版本 == v1.11.0
```
$ helm install edgemesh \
--set agent.image=kubeedge/edgemesh-agent:v1.11.0 \
--set server.image=kubeedge/edgemesh-server:v1.11.0 \
--set server.nodeName=k8s-node1 \
--set server.advertiseAddress="{119.8.211.54}" \
https://raw.githubusercontent.com/kubeedge/edgemesh/release-1.12/build/helm/edgemesh.tgz
```
