### ISSUE TITLE
failed to find any peer in table

### ISSUE THREAD

**Issue by wuming333666** [kubeedge/edgemesh#406]
[问题]
E1130 21:47:49.155119       1 tunnel.go:121] [MDNS] New stream between peer {12D3KooWC4bVkoxYENbud7iSBy8NTpYuhbaWVmR9pqBUQtQqu8km: [/ip4/127.0.0.1/tcp/20006 /ip4/10.9.65.97/tcp/20006 /ip4/172.17.0.1/tcp/20006 /ip4/169.254.96.16/tcp/20006]} err: failed to find any peer in table

[版本]
v1.12.1
[其他]
防火墙已关闭, 机器之间的udp协议是正常的;
中继节点是必须的吗? 我目前没有添加中继节点,只有2个节点

**Comment by dengbei-victor** [comment]
我有着相同的问题

**Comment by biao-lvwan** [comment]
中继节点是必须添加的嘛，我是局域网，但是用gateway就会出现Dial failed" err="get proxy stream from dev-edge-01 error: new stream between dev-edge-01: {12D3KooWGKwsGq9cZCM4KDow8pnExMDbQKJE3QX9jvSGidR3uwdE: []} err: failed to find any peer in table"
 能帮忙看看嘛
