### ISSUE TITLE
DNS requests from Edge won't resolve

### ISSUE THREAD

**Issue by stavbernazanv** [kubeedge/edgemesh#410]
**What happened**:
Deployed KubeEdge 1.12.1 and edgemesh 1.12.0 charts
deployed a pod in edge node, trying to connect consul service in a different non-edge node fails:

```
nslookup consul-server.default.svc.cluster.local
;; connection timed out; no servers could be reached
```

**What you expected to happen**:
pods on edge nodes should resolve FQDNs of services in the cloud side.

**How to reproduce it (as minimally and precisely as possible)**:
Deployed KubeEdge 1.12.1 and edgemesh 1.12.0 charts
Deployed nginx pod on edge
Try nslookup from nginx pod to service in the cloud

**Environment**:
- EdgeMesh version: 1.12.0
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.12.1
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
Check whether the /etc/resolv.conf file in the pod that initiates the access contains nameserver 169.254.96.16.

/etc/resolv.conf is used to configure the domain name resolution server of the host (or container). If you do not understand it, search for it. 169.254. 96.16 is the IP address of the bridge listened by EdgeMesh. 169.254. 96.16:53 is the socket listened by the domain name resolution module of EdgeMesh. If the /etc/resolv.conf file does not contain nameserver 169.254.96.16, the domain name resolution request cannot be sent to the domain name resolution module of EdgeMesh.

**Comment by stavbernazanv** [comment]
Issue was with the configuration of edgecore missing because it changed from 1.10 to 1.12
I was lacking the following configuration in /etc/kubeedge/config/edgecore.yaml:
`tailoredKubeletConfig:
      clusterDNS:
      - "169.254.96.16"
      clusterDomain: "cluster.local"`
