### ISSUE TITLE
Minor spelling mistake in the architecture figure

### ISSUE THREAD

**Issue by ravaga** [kubeedge/edgemesh#423]
**What would you like to be added/modified**:
I realised that in the new architecture figure, the _loadBalancer_ component is written as _loa**b**Balancer_, a minor spelling mistake that should be corrected.

**Why is this needed**:
This is needed in order to provide a clearer documentation.

**Comment by Poorunga** [comment]
Thanks for your care, we'll fix it.

**Comment by Poorunga** [comment]
fix in https://github.com/kubeedge/edgemesh/pull/425
