### ISSUE TITLE
边缘节点切换网络后容器内dns解析出现短暂不可用

### ISSUE THREAD

**Issue by stricklandye** [kubeedge/edgemesh#427]
**What happened**:
边缘节点从集群内部网络切换到外部网络（5g电话卡）以后，边缘节点的容器出现了短暂的（5min-10min不等）的svc域名不可用，直接访问svc到cluster ip可用。如果从5g切回到集群网络，这个过程恢复到很快。请问如何排查？参考知乎参考页面，但是没有符合情况的案例
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
edgemesh日志显示了对svc的dns解析请求，只不过结果是server fail。
**Environment**:
- EdgeMesh version: 
- Kubernetes version (use `kubectl version`): 1.23.4
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):  kubeedge 1.12.1

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`): X86_64
    - OS (e.g. `cat /etc/os-release`):  ubuntu-20.04
    - Kernel (e.g. `uname -a`): 5.15.0-58-generic
    - Go version (e.g. `go version`): 
    - Others:

  </details>

**Comment by Poorunga** [comment]
edgemesh会对接edgecore的metaserver模块，从中获取元数据，比如service、endpoints等，域名解析模块据此元数据解析域名。

你可以先测试一下内部网络切换到外部网络时，metaserver模块本身正不正常。metaserver模块监听在10550，可以通过类似 curl 127.0.0.1:10550/api/v1/services 等方式。如果metaserver模块本身不支持内部网络切换到外部网络场景下的正常运行，建议在kubeedge仓库提交对应issue并描述问题。

**Comment by stricklandye** [comment]
> edgemesh会对接edgecore的metaserver模块，从中获取元数据，比如service、endpoints等，域名解析模块据此元数据解析域名。
> 
> 你可以先测试一下内部网络切换到外部网络时，metaserver模块本身正不正常。metaserver模块监听在10550，可以通过类似 curl 127.0.0.1:10550/api/v1/services 等方式测试。如果metaserver模块本身不支持内部网络切换到外部网络场景下的正常运行，建议在kubeedge仓库提交对应issue并描述问题。

感谢回复！尝试了看了下源码，对于代码有些不懂的地方请教一下：
1.  edgemesh对于dns请求处理是建立了一个brige并且拦截这些请求吗，实际的dns处理是交给coredns处理的吗？
2. 在edgemesh repo中与edgecore的交互是位于哪部分？想学习下～

**Comment by Poorunga** [comment]
> edgemesh对于dns请求处理是建立了一个bridge并且拦截这些请求，实际的dns处理是交给coredns处理的吗？

你可以 exec 进入 edgemesh-agent pod 内看一下，在 / 根目录下，有一个Corefile文件。实际的dns处理是交给coredns处理的，没错。只不过coredns内嵌在edgemesh的进程中了。

> 在edgemesh repo中与edgecore的交互是位于哪部分？想学习下～

第一部分是处理Kube API Endpoint Address的，在https://github.com/kubeedge/edgemesh/blob/main/cmd/edgemesh-agent/app/server.go#L134-L148

第二部分就是调用 k8s client-go 的函数，创建informer，在https://github.com/kubeedge/edgemesh/blob/main/pkg/clients/kube.go

和edgecore的交互，其实就是和metaserver的交互，metaserver就是边缘侧的kube-apiserver，跟你云上的controller对接kube-apiserver没任何区别。

**Comment by stricklandye** [comment]
好的，感谢回复。我先按照您说的方案去拍查下，我把issue 先close了～
