### ISSUE TITLE
Edgemesh-Gateway A runs on edge node-A got conflicted with Edgemesh-Gateway B runs on edge node-B

### ISSUE THREAD

**Issue by william1008** [kubeedge/edgemesh#428]
**What happened**:
I have 2 edge nodes (172.31.0.32, 172.31.0.34) in the same vLAN(172.31.0.0/24), and these 2 edge nodes are all joined into the same k8s cluster.

I created 2 namespace uat and prod in the k8s cluster.

I deployed edgemesh-gateway-uat  via helmchart in ns uat on edge node 32, and also deployed edgemesh-gateway-prod in ns prod on edge node 34. means I deployed 2 different edgemesh-gateway k8s workloads separately in ns uat and ns prod, these workloads(or pods) will execute the traffic management rules defined via virtualService or destinationRule etc.
 
I deployed the hostname-lb-random-gateway.yaml resources in ns uat, I renamed the http-gw name to http-gw-uat
I also deployed the hostname-lb-random-gateway.yaml resources in ns prod, I renamed the http-gw name to http-gw-prod

When I executed command on node 32 or 34  below,

curl 172.31.0.32:23333 or
curl 172.31.0.34:23333

Only one edgemesh gateway worked as expected, the other one always return error below,
curl:  (52) Empty reply from server

**What you expected to happen**:

edgemesh-gateway-uat can handle service traffic to or from uat namespace

edgemesh-gateway-prod can handle service traffic to or from prod namespace

**How to reproduce it (as minimally and precisely as possible)**:

[root@sandbox-vm00 examples]# curl h4:23333
curl: (52) Empty reply from server
[root@sandbox-vm00 examples]# curl 172.31.0.32:23333
hostname-lb-edge-5f459fbd8f-bbtc4
[root@sandbox-vm00 examples]# curl 172.31.0.34:23333
curl: (52) Empty reply from server
[root@sandbox-vm00 examples]#

**Anything else we need to know?**:

**Environment**: 
- EdgeMesh version:  v1.12.0
- Kubernetes version (use `kubectl version`):  v1.21.12
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):  v1.12.0
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`): 2vU/3GB Mem
    - OS (e.g. `cat /etc/os-release`): CentOS 7.9
    - Kernel (e.g. `uname -a`):  3.10.0-1160.el7.x86_64
    - Go version (e.g. `go version`): Not installed
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):  v1.12.0
    - Hardware configuration (e.g. `lscpu`):  2vU/3GB Mem
    - OS (e.g. `cat /etc/os-release`):  CentOS 7.9
    - Kernel (e.g. `uname -a`):  3.10.0-1160.el7.x86_64
    - Go version (e.g. `go version`):  Not installed
    - Others:

  </details>

**Comment by william1008** [comment]
![edgemesh-gw-log-prod](https://user-images.githubusercontent.com/34850303/218045509-abde8b52-e6f9-493f-8b0f-759e83176af8.png)
Above is the edgemesh-gateway-prod pod's log, and below is the edgemesh-gateway-uat pod's log
![edgemesh-gw-log-uat](https://user-images.githubusercontent.com/34850303/218045519-17745239-4c6b-4268-845c-fc83e2d492d2.png)

**Comment by william1008** [comment]
After many time practice, I guess the gateway conflicts was caused by the http-gw's selector, because the uat/http-gw-uat use the gateway selector "kubeedge:  edgemesh-gateway", so it reported "... xxx bind: address already inuse". Because edgemesh-gateway-uat and edgemesh-gateway-prod, though they're created in different ns, but both they reference to the same k8s workloads, means both of them will reference the same edgemesh-gateway pod globally cross the k8s namespace.

**Comment by william1008** [comment]
To verify my guess, I did the following test:
I modified the edgemesh-gateway helm chart's template as below,
![gwchart](https://user-images.githubusercontent.com/34850303/218050355-44b12ba2-a5d6-4dc7-b4c1-50b1da29aba2.PNG) for prod
![gwchart-uat](https://user-images.githubusercontent.com/34850303/218050354-66c8c385-8396-4dee-a7d9-41ec132ceae3.PNG) for uat

I redeployed the two helm releases as edgemesh-gateway-prod and edgemesh-gateway-uat, below is the logs
![edgemesh-gw-log-prod-2](https://user-images.githubusercontent.com/34850303/218048182-e19e4b2e-8f41-4d8b-93ba-8ca6d07fd90d.png) 
![edgemesh-gw-log-uat-2](https://user-images.githubusercontent.com/34850303/218048197-9bc422ed-8149-464f-9f57-60529dde916d.png)
1st log is for prod and 2nd one is for uat, seems now there's no "... xxx bind: address already in use" issue in the log, but  node 32 and node 34 are both added as "prod.http-gateway-prod" as the log mentioned, http-gateway-uat got lost...

**Comment by Poorunga** [comment]
> ... xxx bind: address already in use
The edgemesh-gateway list-watch gateway CRD and listens to ports on node based on the `number` field. Do two gateways use the same port?

**Comment by william1008** [comment]
> > ... xxx bind: address already in use
> 
> The edgemesh-gateway list-watch gateway CRD and listens to ports on node based on the `number` field. Do two gateways use the same 23333 port?

Oh... yes. after I update the edgemesh-gateway-prod's listening port to 26666, now it works.
![edgemesh-gw-fixed](https://user-images.githubusercontent.com/34850303/218359679-398561c4-43b6-4175-a42e-5da75cf6e3ce.PNG)
But I have a question, now the edgemesh-gw-uat listens on 23333, and the edgemesh-gw-prod listens on 26666. but why do but why do the other unexpected one was also opened? For example as below, in my edgemesh-gateway-prod pod, what I configured in the http-gw is just tcp 26666, but the 23333(actually for uat) was also unexpectedly opened.
 
![edgemesh-gw-fixed2](https://user-images.githubusercontent.com/34850303/218361513-9e7ecde0-f1aa-441b-be83-8b1e3ae5ff26.PNG)

Is the other unexpected one can be disabled? So that we can save a hostPort.

**Comment by Poorunga** [comment]
By Design

Every edgemesh-gateway component will watch all gateway CRD in all namespace.

**Comment by william1008** [comment]
> By Design
> 
> Every edgemesh-gateway component will watch all gateway CRD in all namespace.

Thanks for the reply
