### ISSUE TITLE
Cross-Edge-Cloud test successed but sedna Joint Inference example dns reslove failed

### ISSUE THREAD

**Issue by Marovlo** [kubeedge/edgemesh#439]
**What happened**:
after finishing deploy edgemesh and sedna Joint Inference example, I found that my edgemesh can pass  all the test that the edgemesh doc has mentioned（including the last **Cross-Edge-Cloud** test), but can't reslove sedna DNS gm.sedna
**What you expected to happen**:
I expect the sedna DNS can work as the Cross-Edge-Cloud test did.
**How to reproduce it (as minimally and precisely as possible)**:
install edgemesh and sedna as the formal introduction does, then run the Cross-Edge-Cloud test and senda Joint Inference example

**Environment**:
- EdgeMesh version:latest
- Kubernetes version (use `kubectl version`):1.22
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.12

**logs**:

edge: edgemesh agent:
we can see that tcp-echo-cloud-svc.cloudzone.svc.cluster.local dns reslove successfully(in the middle of the picture), but the gm.sedna dns reslove constantly failed.
![7b3ae3defabee8f06958e5a1794772b](https://user-images.githubusercontent.com/45875404/221868111-5ed991a9-2167-4189-bfa0-e095211f5999.png)

cloud: edgemesh agent:
![image](https://user-images.githubusercontent.com/45875404/221868870-9af62dec-1ba6-4a84-aaae-f02a54db236c.png)

tcp-echo-cloud-svc service:
![image](https://user-images.githubusercontent.com/45875404/221869035-1c7ae3c7-ae4c-4af1-b5af-8dc07da69fa1.png)

sedna service:
![image](https://user-images.githubusercontent.com/45875404/221869102-dce86382-d442-45d6-a44c-391212373a4d.png)

node info:
![image](https://user-images.githubusercontent.com/45875404/221869761-672395b7-d914-40ab-8438-2cf4df2c23e7.png)

pods info:
![image](https://user-images.githubusercontent.com/45875404/221869877-8db2f86e-9158-4c86-8587-61878520a2b5.png)

**help please**
what should I do please?

**Comment by Poorunga** [comment]
https://zhuanlan.zhihu.com/p/585749690, see question 5.
