### ISSUE TITLE
the two edge node edgemesh-agent peer ID is same

### ISSUE THREAD

**Issue by 844700118** [kubeedge/edgemesh#443]
**1. my issues**

    why the two edge node edgemesh-agent peer ID is same ? 
    the same peer ID: QmS8zXjedoqHhagXVPje4SMx6cReYfNryxqM5JGzZYAWAw
    Where is the configuration wrong?

    EdgeMesh version: release-1.8
    Kubernetes version (use kubectl version): 1.14
    KubeEdge version(e.g. cloudcore --version and edgecore --version): 1.8
    cloud node(master) 
	ip: 39.130.243.252(172.24.178.41)
	0.0.0.0:20004   edgemesh-server 
	0.0.0.0:20006   edgemesh-agent
	
    edge node1(ynu-jxnode) 
	ip: 172.24.178.51
	0.0.0.0:20006   edgemesh-agent

    edge node2(yunnanzt) 
	ip: 172.16.70.201
	0.0.0.0:20006   edgemesh-agent

    [root@master ~]# kubectl get node
    master          Ready    master         92d       v1.14.1                   172.24.178.41
    ynu-jxnode     Ready    agent,edge   6d17h     v1.19.3-kubeedge-v1.8.2   172.24.5.21
    yunnanzt       Ready    agent,edge   13d       v1.19.3-kubeedge-v1.8.2    172.16.70.201
   
    [root@master ~]# kubectl get secret -n kubeedge edgemeshaddrsecret -o yaml
    master: eyJJRCI6IlFtWXpxV2lHRGdYRTg0SEp1ZUt5eW91aU1na1FLY2JpSlpTRnl5TTFSRTZGWnYiLCJBZGRycyI6WyIvaXA0LzE3Mi4yNC4xNzguNDEvdGNwLzIwMDA2IiwiL2lwNC8xMjcuMC4wLjEvdGNwLzIwMDA2IiwiL2lwNC8xNzIuMjQuMTc4LjQxL3RjcC8yMDAwNC9wMnAvUW1mVE1kU1pDRkhWdnhVTW5zdFlqbUZZUjdxVXFMUU5KckFXOEE1M21CWEN2VC9wMnAtY2lyY3VpdCIsIi9pcDQvMTI3LjAuMC4xL3RjcC8yMDAwNC9wMnAvUW1mVE1kU1pDRkhWdnhVTW5zdFlqbUZZUjdxVXFMUU5KckFXOEE1M21CWEN2VC9wMnAtY2lyY3VpdCIsIi9pcDQvMzkuMTMwLjI0My4yNTIvdGNwLzIwMDA0L3AycC9RbWZUTWRTWkNGSFZ2eFVNbnN0WWptRllSN3FVcUxRTkpyQVc4QTUzbUJYQ3ZUL3AycC1jaXJjdWl0Il19
    ynu-jxnode: eyJJRCI6IlFtUzh6WGplZG9xSGhhZ1hWUGplNFNNeDZjUmVZZk5yeXhxTTVKR3paWUFXQXciLCJBZGRycyI6WyIvaXA0LzE3Mi4yNC4xNzguNTEvdGNwLzIwMDA2IiwiL2lwNC8xMjcuMC4wLjEvdGNwLzIwMDA2IiwiL2lwNC8zOS4xMjkuNS45L3RjcC8yMDAwNiIsIi9pcDQvMTcyLjI0LjE3OC40MS90Y3AvMjAwMDQvcDJwL1FtZlRNZFNaQ0ZIVnZ4VU1uc3RZam1GWVI3cVVxTFFOSnJBVzhBNTNtQlhDdlQvcDJwLWNpcmN1aXQiLCIvaXA0LzEyNy4wLjAuMS90Y3AvMjAwMDQvcDJwL1FtZlRNZFNaQ0ZIVnZ4VU1uc3RZam1GWVI3cVVxTFFOSnJBVzhBNTNtQlhDdlQvcDJwLWNpcmN1aXQiLCIvaXA0LzM5LjEzMC4yNDMuMjUyL3RjcC8yMDAwNC9wMnAvUW1mVE1kU1pDRkhWdnhVTW5zdFlqbUZZUjdxVXFMUU5KckFXOEE1M21CWEN2VC9wMnAtY2lyY3VpdCJdfQ==
    yunnanzt: eyJJRCI6IlFtUzh6WGplZG9xSGhhZ1hWUGplNFNNeDZjUmVZZk5yeXhxTTVKR3paWUFXQXciLCJBZGRycyI6WyIvaXA0LzE3Mi4xNi43MC4yMDEvdGNwLzIwMDA2IiwiL2lwNC8xMjcuMC4wLjEvdGNwLzIwMDA2IiwiL2lwNC8xODMuMjI0LjgyLjIwMi90Y3AvMjA4MCIsIi9pcDQvMTcyLjI0LjE3OC40MS90Y3AvMjAwMDQvcDJwL1FtZlRNZFNaQ0ZIVnZ4VU1uc3RZam1GWVI3cVVxTFFOSnJBVzhBNTNtQlhDdlQvcDJwLWNpcmN1aXQiLCIvaXA0LzEyNy4wLjAuMS90Y3AvMjAwMDQvcDJwL1FtZlRNZFNaQ0ZIVnZ4VU1uc3RZam1GWVI3cVVxTFFOSnJBVzhBNTNtQlhDdlQvcDJwLWNpcmN1aXQiLCIvaXA0LzM5LjEzMC4yNDMuMjUyL3RjcC8yMDAwNC9wMnAvUW1mVE1kU1pDRkhWdnhVTW5zdFlqbUZZUjdxVXFMUU5KckFXOEE1M21CWEN2VC9wMnAtY2lyY3VpdCJdfQ==

    ###Base64 decode
    master:
    {"ID":"QmYzqWiGDgXE84HJueKyyouiMgkQKcbiJZSFyyM1RE6FZv","Addrs":["/ip4/172.24.178.41/tcp/20006","/ip4/127.0.0.1/tcp/20006","/ip4/172.24.178.41/tcp/20004/p2p/QmfTMdSZCFHVvxUMnstYjmFYR7qUqLQNJrAW8A53mBXCvT/p2p-circuit","/ip4/127.0.0.1/tcp/20004/p2p/QmfTMdSZCFHVvxUMnstYjmFYR7qUqLQNJrAW8A53mBXCvT/p2p-circuit","/ip4/39.130.243.252/tcp/20004/p2p/QmfTMdSZCFHVvxUMnstYjmFYR7qUqLQNJrAW8A53mBXCvT/p2p-circuit"]}

    ynu-jxnode:
    {"ID":"QmS8zXjedoqHhagXVPje4SMx6cReYfNryxqM5JGzZYAWAw","Addrs":["/ip4/172.24.178.51/tcp/20006","/ip4/127.0.0.1/tcp/20006","/ip4/39.129.5.9/tcp/20006","/ip4/172.24.178.41/tcp/20004/p2p/QmfTMdSZCFHVvxUMnstYjmFYR7qUqLQNJrAW8A53mBXCvT/p2p-circuit","/ip4/127.0.0.1/tcp/20004/p2p/QmfTMdSZCFHVvxUMnstYjmFYR7qUqLQNJrAW8A53mBXCvT/p2p-circuit","/ip4/39.130.243.252/tcp/20004/p2p/QmfTMdSZCFHVvxUMnstYjmFYR7qUqLQNJrAW8A53mBXCvT/p2p-circuit"]}

    yunnanzt:
    {"ID":"QmS8zXjedoqHhagXVPje4SMx6cReYfNryxqM5JGzZYAWAw","Addrs":["/ip4/172.16.70.201/tcp/20006","/ip4/127.0.0.1/tcp/20006","/ip4/183.224.82.202/tcp/2080","/ip4/172.24.178.41/tcp/20004/p2p/QmfTMdSZCFHVvxUMnstYjmFYR7qUqLQNJrAW8A53mBXCvT/p2p-circuit","/ip4/127.0.0.1/tcp/20004/p2p/QmfTMdSZCFHVvxUMnstYjmFYR7qUqLQNJrAW8A53mBXCvT/p2p-circuit","/ip4/39.130.243.252/tcp/20004/p2p/QmfTMdSZCFHVvxUMnstYjmFYR7qUqLQNJrAW8A53mBXCvT/p2p-circuit"]}

**2. nodeName config**

    https://zhuanlan.zhihu.com/p/585749690
    peer ID是根据节点名称哈希出来的，相同的节点名称会哈希出相同的peer ID
    配置似乎没有问题, 节点名是动态获取的
    vi 07-daemonset-edge.yaml
    ......
            image: kubeedge/edgemesh-agent:v1.8.0  
            env:
                - name: MY_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
    ......
 looking forward to your help.

**Comment by Poorunga** [comment]
配置不对，>=1.12.0后 使用NODE_NAME环境变量，而不是MY_NODE_NAME

**Comment by 844700118** [comment]
> 配置不对，>=1.12.0后 使用NODE_NAME环境变量，而不是MY_NODE_NAME
我用的edgemesh 版本是v1.8

**Comment by 844700118** [comment]
> 配置不对，>=1.12.0后 使用NODE_NAME环境变量，而不是MY_NODE_NAME

我用的edgemesh 版本是v1.8     k8s版本1.14

**Comment by Poorunga** [comment]
> https://zhuanlan.zhihu.com/p/585749690
peer ID是根据节点名称哈希出来的，相同的节点名称会哈希出相同的peer ID

上面这段话，针对>=1.12.0写的，其他版本没有这个。建议升级使用搞版本

**Comment by 844700118** [comment]
> > https://zhuanlan.zhihu.com/p/585749690
> > peer ID是根据节点名称哈希出来的，相同的节点名称会哈希出相同的peer ID
> 
> 上面这段话，针对>=1.12.0写的，其他版本没有这个。建议升级使用高版本

这个是客户环境， 升级k8s成本很高. 
想知道 低版本peer ID的生成规则是怎样的？

**Comment by Poorunga** [comment]
升级edgemesh版本。低版本生成peer ID见https://github.com/kubeedge/edgemesh/blob/release-1.8/agent/pkg/tunnel/module.go#L49

**Comment by 844700118** [comment]
目前故障是2个边缘节点edgemesh-agent, 
重启A，B上的svc服务就正常, A上的svc不正常。
重启B，A上的svc服务就正常, B上的svc不正常。

**Comment by Poorunga** [comment]
请提供日志
