### ISSUE TITLE
Issue on OpenSSL when Testing with HTTPS Gateway

### ISSUE THREAD

**Issue by chunyeow** [kubeedge/edgemesh#447]
**What happened**:
Fail on HTTPS Gateway with following errors "curl: (35) error:0A000126:SSL routines::unexpected eof while reading"

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the HTTPS gateway and running curl command over Ubuntu 22.04 machine as follow:
"curl https://<Relay Node IP address>:23333"

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version: kubeedge/edgemesh-gateway:v1.13.1
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.5", GitCommit:"804d6167111f6858541cef440ccc53887fbbc96a", GitTreeState:"clean", BuildDate:"2022-12-08T10:15:02Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.5", 
GitCommit:"804d6167111f6858541cef440ccc53887fbbc96a", GitTreeState:"clean", BuildDate:"2022-12-08T10:08:09Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`): Ubuntu 22.04
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
fix in https://github.com/kubeedge/edgemesh/pull/445

**Comment by chunyeow** [comment]
Confirm the fix is correct. Seem to hang and not proceed in my case

**Comment by Poorunga** [comment]
Would you like to print some edgemesh-agent logs?

**Comment by chunyeow** [comment]
I0321 06:41:29.035345       1 server.go:56] Version: v1.13.0-beta.0.36+26733bf32c40a8-dirty
I0321 06:41:29.035375       1 server.go:92] [1] Prepare agent to run
I0321 06:41:29.035921       1 netif.go:96] bridge device edgemesh0 already exists
I0321 06:41:29.035964       1 server.go:96] edgemesh-agent running on EdgeMode
I0321 06:41:29.035971       1 server.go:99] [2] New clients
I0321 06:41:29.037951       1 server.go:106] [3] Register beehive modules
I0321 06:41:29.038192       1 module.go:34] Module EdgeDNS registered successfully
I0321 06:41:29.038383       1 server.go:68] Using userspace Proxier.
I0321 06:41:29.338562       1 module.go:34] Module EdgeProxy registered successfully
I0321 06:41:29.339919       1 module.go:127] Configure libp2p.ForceReachabilityPrivate()
I0321 06:41:29.434860       1 module.go:182] I'm {12D3KooWL3wJsr1MEStFhKasXixDJxc8a9oFgWnvXzAf6FJUDsSN: [/ip4/192.168.40.166/tcp/20006 /ip4/127.0.0.1/tcp/20006]}
I0321 06:41:29.434886       1 module.go:204] Bootstrapping the DHT
I0321 06:41:29.435175       1 tunnel.go:80] Starting MDNS discovery service
I0321 06:41:29.435185       1 tunnel.go:93] Starting DHT discovery service
I0321 06:41:29.435225       1 module.go:34] Module EdgeTunnel registered successfully
I0321 06:41:29.435233       1 server.go:112] [4] Cache beehive modules
I0321 06:41:29.435240       1 server.go:119] [5] Start all modules
I0321 06:41:29.435274       1 core.go:24] Starting module EdgeDNS
I0321 06:41:29.435296       1 core.go:24] Starting module EdgeProxy
I0321 06:41:29.435317       1 core.go:24] Starting module EdgeTunnel
I0321 06:41:29.439433       1 tunnel.go:491] Starting relay finder
I0321 06:41:29.439674       1 dns.go:38] Runs CoreDNS v1.8.0 as a local dns
I0321 06:41:29.541541       1 config.go:317] "Starting service config controller"
I0321 06:41:29.541564       1 shared_informer.go:240] Waiting for caches to sync for service config
I0321 06:41:29.541589       1 config.go:135] "Starting endpoints config controller"
I0321 06:41:29.541593       1 shared_informer.go:240] Waiting for caches to sync for endpoints config
I0321 06:41:29.638159       1 loadbalancer.go:239] "Starting loadBalancer destinationRule controller"
I0321 06:41:29.638171       1 shared_informer.go:240] Waiting for caches to sync for loadBalancer destinationRule
I0321 06:41:29.642237       1 shared_informer.go:247] Caches are synced for endpoints config
I0321 06:41:29.642253       1 shared_informer.go:247] Caches are synced for service config
.:53 on 169.254.96.16
I0321 06:41:29.734296       1 log.go:184] [INFO] plugin/reload: Running configuration MD5 = ab8e188d63b1d1a5168d68e78fe4128d
I0321 06:41:29.840439       1 proxier.go:895] "Opened iptables from-containers public port for service" servicePortName="ingress-nginx/ingress-nginx-controller:http" protocol=TCP nodePort=31209
I0321 06:41:29.934750       1 proxier.go:906] "Opened iptables from-host public port for service" servicePortName="ingress-nginx/ingress-nginx-controller:http" protocol=TCP nodePort=31209
I0321 06:41:29.936571       1 proxier.go:916] "Opened iptables from-non-local public port for service" servicePortName="ingress-nginx/ingress-nginx-controller:http" protocol=TCP nodePort=31209
I0321 06:41:30.034087       1 log.go:184] [INFO] 169.254.96.16:49680 - 5362 "HINFO IN 3925155324112163789.4627743411165610686. udp 57 false 512" NXDOMAIN qr,rd,ra 132 0.298764987s
I0321 06:41:30.037368       1 proxier.go:895] "Opened iptables from-containers public port for service" servicePortName="ingress-nginx/ingress-nginx-controller:https" protocol=TCP nodePort=32150
I0321 06:41:30.039146       1 proxier.go:906] "Opened iptables from-host public port for service" servicePortName="ingress-nginx/ingress-nginx-controller:https" protocol=TCP nodePort=32150
I0321 06:41:30.041066       1 proxier.go:916] "Opened iptables from-non-local public port for service" servicePortName="ingress-nginx/ingress-nginx-controller:https" protocol=TCP nodePort=32150
I0321 06:41:30.333858       1 shared_informer.go:247] Caches are synced for loadBalancer destinationRule
I0321 06:41:30.547562       1 proxier.go:895] "Opened iptables from-containers public port for service" servicePortName="kubeedge/cloudcore:cloudhub" protocol=TCP nodePort=31023
I0321 06:41:30.635451       1 proxier.go:906] "Opened iptables from-host public port for service" servicePortName="kubeedge/cloudcore:cloudhub" protocol=TCP nodePort=31023
I0321 06:41:30.639235       1 proxier.go:916] "Opened iptables from-non-local public port for service" servicePortName="kubeedge/cloudcore:cloudhub" protocol=TCP nodePort=31023
I0321 06:41:30.738542       1 proxier.go:895] "Opened iptables from-containers public port for service" servicePortName="kubeedge/cloudcore:cloudhub-quic" protocol=TCP nodePort=31650
I0321 06:41:30.744530       1 proxier.go:906] "Opened iptables from-host public port for service" servicePortName="kubeedge/cloudcore:cloudhub-quic" protocol=TCP nodePort=31650
I0321 06:41:30.833689       1 proxier.go:916] "Opened iptables from-non-local public port for service" servicePortName="kubeedge/cloudcore:cloudhub-quic" protocol=TCP nodePort=31650
I0321 06:41:30.839441       1 proxier.go:895] "Opened iptables from-containers public port for service" servicePortName="kubeedge/cloudcore:cloudhub-https" protocol=TCP nodePort=30370
I0321 06:41:30.841327       1 proxier.go:906] "Opened iptables from-host public port for service" servicePortName="kubeedge/cloudcore:cloudhub-https" protocol=TCP nodePort=30370
I0321 06:41:30.843380       1 proxier.go:916] "Opened iptables from-non-local public port for service" servicePortName="kubeedge/cloudcore:cloudhub-https" protocol=TCP nodePort=30370
I0321 06:41:30.849308       1 proxier.go:895] "Opened iptables from-containers public port for service" servicePortName="kubeedge/cloudcore:cloudstream" protocol=TCP nodePort=30132
I0321 06:41:30.851357       1 proxier.go:906] "Opened iptables from-host public port for service" servicePortName="kubeedge/cloudcore:cloudstream" protocol=TCP nodePort=30132
I0321 06:41:30.853488       1 proxier.go:916] "Opened iptables from-non-local public port for service" servicePortName="kubeedge/cloudcore:cloudstream" protocol=TCP nodePort=30132
I0321 06:41:30.939642       1 proxier.go:895] "Opened iptables from-containers public port for service" servicePortName="kubeedge/cloudcore:tunnelport" protocol=TCP nodePort=30165
I0321 06:41:30.941638       1 proxier.go:906] "Opened iptables from-host public port for service" servicePortName="kubeedge/cloudcore:tunnelport" protocol=TCP nodePort=30165
I0321 06:41:30.943864       1 proxier.go:916] "Opened iptables from-non-local public port for service" servicePortName="kubeedge/cloudcore:tunnelport" protocol=TCP nodePort=30165
I0321 06:41:36.683468       1 tunnel.go:205] Discovery service got a new stream from {12D3KooWMmhQYuzv69pcEPE7C9VbzErvNFb9jrBJ5fk8xSwhw2ZU: [/ip4/10.44.29.100/tcp/20007]}
I0321 06:41:36.683597       1 tunnel.go:234] [DHT] Discovery from node5 : {12D3KooWMmhQYuzv69pcEPE7C9VbzErvNFb9jrBJ5fk8xSwhw2ZU: [/ip4/10.44.29.100/tcp/20007]}
I0321 06:50:12.577343       1 tunnel.go:126] [MDNS] Discovery found peer: {12D3KooWACjYCRcEpyZK8gaDnD4qACqfqMQFhZZe878p3j8RZWDt: [/ip4/127.0.0.1/tcp/20006 /ip4/192.168.40.163/tcp/20006 /ip4/10.233.55.45/tcp/20006 /ip4/10.233.27.4/tcp/20006 /ip4/10.233.59.100/tcp/20006 /ip4/192.168.40.187/tcp/20006 /ip4/10.233.0.3/tcp/20006 /ip4/10.233.0.1/tcp/20006 /ip4/10.233.30.125/tcp/20006 /ip4/10.233.48.215/tcp/20006 /ip4/10.233.10.255/tcp/20006 /ip4/10.233.13.82/tcp/20006 /ip4/10.233.32.110/tcp/20006 /ip4/10.233.75.0/tcp/20006 /ip4/169.254.25.10/tcp/20006 /ip4/169.254.96.16/tcp/20006]}
I0321 06:50:12.668653       1 tunnel.go:156] [MDNS] New stream between peer {12D3KooWACjYCRcEpyZK8gaDnD4qACqfqMQFhZZe878p3j8RZWDt: [/ip4/127.0.0.1/tcp/20006 /ip4/192.168.40.163/tcp/20006 /ip4/10.233.55.45/tcp/20006 /ip4/10.233.27.4/tcp/20006 /ip4/10.233.59.100/tcp/20006 /ip4/192.168.40.187/tcp/20006 /ip4/10.233.0.3/tcp/20006 /ip4/10.233.0.1/tcp/20006 /ip4/10.233.30.125/tcp/20006 /ip4/10.233.48.215/tcp/20006 /ip4/10.233.10.255/tcp/20006 /ip4/10.233.13.82/tcp/20006 /ip4/10.233.32.110/tcp/20006 /ip4/10.233.75.0/tcp/20006 /ip4/169.254.25.10/tcp/20006 /ip4/169.254.96.16/tcp/20006]} success
I0321 06:50:12.669390       1 tunnel.go:192] [MDNS] Discovery to node2 : {12D3KooWACjYCRcEpyZK8gaDnD4qACqfqMQFhZZe878p3j8RZWDt: [/ip4/127.0.0.1/tcp/20006 /ip4/192.168.40.163/tcp/20006 /ip4/10.233.55.45/tcp/20006 /ip4/10.233.27.4/tcp/20006 /ip4/10.233.59.100/tcp/20006 /ip4/192.168.40.187/tcp/20006 /ip4/10.233.0.3/tcp/20006 /ip4/10.233.0.1/tcp/20006 /ip4/10.233.30.125/tcp/20006 /ip4/10.233.48.215/tcp/20006 /ip4/10.233.10.255/tcp/20006 /ip4/10.233.13.82/tcp/20006 /ip4/10.233.32.110/tcp/20006 /ip4/10.233.75.0/tcp/20006 /ip4/169.254.25.10/tcp/20006 /ip4/169.254.96.16/tcp/20006]}
I0321 06:50:17.577741       1 tunnel.go:205] Discovery service got a new stream from {12D3KooWACjYCRcEpyZK8gaDnD4qACqfqMQFhZZe878p3j8RZWDt: [/ip4/192.168.40.187/tcp/20006]}
I0321 06:50:17.577796       1 tunnel.go:234] [MDNS] Discovery from node2 : {12D3KooWACjYCRcEpyZK8gaDnD4qACqfqMQFhZZe878p3j8RZWDt: [/ip4/192.168.40.187/tcp/20006]}
I0321 06:50:17.578107       1 tunnel.go:205] Discovery service got a new stream from {12D3KooWACjYCRcEpyZK8gaDnD4qACqfqMQFhZZe878p3j8RZWDt: [/ip4/192.168.40.187/tcp/20006]}
I0321 06:50:17.578150       1 tunnel.go:234] [MDNS] Discovery from node2 : {12D3KooWACjYCRcEpyZK8gaDnD4qACqfqMQFhZZe878p3j8RZWDt: [/ip4/192.168.40.187/tcp/20006]}
I0321 06:50:33.689953       1 tunnel.go:126] [MDNS] Discovery found peer: {12D3KooWD7xzN4RhwE2ikSLKtQbteadL26p9nzc6NiqVmZB3huH5: [/ip4/127.0.0.1/tcp/20006 /ip4/192.168.40.164/tcp/20006 /ip4/10.233.0.1/tcp/20006 /ip4/10.233.59.100/tcp/20006 /ip4/192.168.40.187/tcp/20006 /ip4/10.233.27.4/tcp/20006 /ip4/10.233.55.45/tcp/20006 /ip4/10.233.0.3/tcp/20006 /ip4/10.233.48.215/tcp/20006 /ip4/10.233.30.125/tcp/20006 /ip4/10.233.10.255/tcp/20006 /ip4/10.233.13.82/tcp/20006 /ip4/10.233.32.110/tcp/20006 /ip4/10.233.71.0/tcp/20006 /ip4/169.254.25.10/tcp/20006 /ip4/169.254.96.16/tcp/20006]}
I0321 06:50:38.692278       1 tunnel.go:156] [MDNS] New stream between peer {12D3KooWD7xzN4RhwE2ikSLKtQbteadL26p9nzc6NiqVmZB3huH5: [/ip4/127.0.0.1/tcp/20006 /ip4/192.168.40.164/tcp/20006 /ip4/10.233.0.1/tcp/20006 /ip4/10.233.59.100/tcp/20006 /ip4/192.168.40.187/tcp/20006 /ip4/10.233.27.4/tcp/20006 /ip4/10.233.55.45/tcp/20006 /ip4/10.233.0.3/tcp/20006 /ip4/10.233.48.215/tcp/20006 /ip4/10.233.30.125/tcp/20006 /ip4/10.233.10.255/tcp/20006 /ip4/10.233.13.82/tcp/20006 /ip4/10.233.32.110/tcp/20006 /ip4/10.233.71.0/tcp/20006 /ip4/169.254.25.10/tcp/20006 /ip4/169.254.96.16/tcp/20006]} success
I0321 06:50:38.692694       1 tunnel.go:192] [MDNS] Discovery to node3 : {12D3KooWD7xzN4RhwE2ikSLKtQbteadL26p9nzc6NiqVmZB3huH5: [/ip4/127.0.0.1/tcp/20006 /ip4/192.168.40.164/tcp/20006 /ip4/10.233.0.1/tcp/20006 /ip4/10.233.59.100/tcp/20006 /ip4/192.168.40.187/tcp/20006 /ip4/10.233.27.4/tcp/20006 /ip4/10.233.55.45/tcp/20006 /ip4/10.233.0.3/tcp/20006 /ip4/10.233.48.215/tcp/20006 /ip4/10.233.30.125/tcp/20006 /ip4/10.233.10.255/tcp/20006 /ip4/10.233.13.82/tcp/20006 /ip4/10.233.32.110/tcp/20006 /ip4/10.233.71.0/tcp/20006 /ip4/169.254.25.10/tcp/20006 /ip4/169.254.96.16/tcp/20006]}
I0321 06:50:44.309164       1 tunnel.go:126] [MDNS] Discovery found peer: {12D3KooWBEJ5BWJwBvdxeWQfXcFcjtpAYeNuf744wcEvawt3HEP5: [/ip4/127.0.0.1/tcp/20006 /ip4/192.168.40.165/tcp/20006 /ip4/10.233.30.125/tcp/20006 /ip4/10.233.0.1/tcp/20006 /ip4/10.233.27.4/tcp/20006 /ip4/10.233.0.3/tcp/20006 /ip4/10.233.48.215/tcp/20006 /ip4/10.233.59.100/tcp/20006 /ip4/192.168.40.187/tcp/20006 /ip4/10.233.55.45/tcp/20006 /ip4/10.233.10.255/tcp/20006 /ip4/10.233.13.82/tcp/20006 /ip4/10.233.32.110/tcp/20006 /ip4/10.233.74.64/tcp/20006 /ip4/169.254.25.10/tcp/20006 /ip4/169.254.96.16/tcp/20006]}
I0321 06:50:49.311973       1 tunnel.go:156] [MDNS] New stream between peer {12D3KooWBEJ5BWJwBvdxeWQfXcFcjtpAYeNuf744wcEvawt3HEP5: [/ip4/127.0.0.1/tcp/20006 /ip4/192.168.40.165/tcp/20006 /ip4/10.233.30.125/tcp/20006 /ip4/10.233.0.1/tcp/20006 /ip4/10.233.27.4/tcp/20006 /ip4/10.233.0.3/tcp/20006 /ip4/10.233.48.215/tcp/20006 /ip4/10.233.59.100/tcp/20006 /ip4/192.168.40.187/tcp/20006 /ip4/10.233.55.45/tcp/20006 /ip4/10.233.10.255/tcp/20006 /ip4/10.233.13.82/tcp/20006 /ip4/10.233.32.110/tcp/20006 /ip4/10.233.74.64/tcp/20006 /ip4/169.254.25.10/tcp/20006 /ip4/169.254.96.16/tcp/20006]} success
I0321 06:50:49.312575       1 tunnel.go:192] [MDNS] Discovery to node4 : {12D3KooWBEJ5BWJwBvdxeWQfXcFcjtpAYeNuf744wcEvawt3HEP5: [/ip4/127.0.0.1/tcp/20006 /ip4/192.168.40.165/tcp/20006 /ip4/10.233.30.125/tcp/20006 /ip4/10.233.0.1/tcp/20006 /ip4/10.233.27.4/tcp/20006 /ip4/10.233.0.3/tcp/20006 /ip4/10.233.48.215/tcp/20006 /ip4/10.233.59.100/tcp/20006 /ip4/192.168.40.187/tcp/20006 /ip4/10.233.55.45/tcp/20006 /ip4/10.233.10.255/tcp/20006 /ip4/10.233.13.82/tcp/20006 /ip4/10.233.32.110/tcp/20006 /ip4/10.233.74.64/tcp/20006 /ip4/169.254.25.10/tcp/20006 /ip4/169.254.96.16/tcp/20006]}
I0321 07:38:55.233827       1 tunnel.go:328] Proxy service got a new stream from {12D3KooWD7xzN4RhwE2ikSLKtQbteadL26p9nzc6NiqVmZB3huH5: [/ip4/192.168.40.164/tcp/20006]}
I0321 07:38:55.234664       1 tunnel.go:378] Success proxy for {tcp master1 172.17.0.3:9376}
I0321 07:38:56.241608       1 tunnel.go:328] Proxy service got a new stream from {12D3KooWD7xzN4RhwE2ikSLKtQbteadL26p9nzc6NiqVmZB3huH5: [/ip4/192.168.40.164/tcp/20006]}
I0321 07:38:56.241777       1 tunnel.go:378] Success proxy for {tcp master1 172.17.0.3:9376}
I0321 07:39:01.949625       1 tunnel.go:328] Proxy service got a new stream from {12D3KooWD7xzN4RhwE2ikSLKtQbteadL26p9nzc6NiqVmZB3huH5: [/ip4/192.168.40.164/tcp/20006]}
I0321 07:39:01.949832       1 tunnel.go:378] Success proxy for {tcp master1 172.17.0.3:9376}
I0321 07:39:03.021017       1 tunnel.go:328] Proxy service got a new stream from {12D3KooWD7xzN4RhwE2ikSLKtQbteadL26p9nzc6NiqVmZB3huH5: [/ip4/192.168.40.164/tcp/20006]}
I0321 07:39:03.021207       1 tunnel.go:378] Success proxy for {tcp master1 172.17.0.3:9376}
I0321 07:39:08.506643       1 tunnel.go:328] Proxy service got a new stream from {12D3KooWD7xzN4RhwE2ikSLKtQbteadL26p9nzc6NiqVmZB3huH5: [/ip4/192.168.40.164/tcp/20006]}
I0321 07:39:08.506855       1 tunnel.go:378] Success proxy for {tcp master1 172.17.0.3:9376}
I0321 07:39:09.779320       1 tunnel.go:328] Proxy service got a new stream from {12D3KooWD7xzN4RhwE2ikSLKtQbteadL26p9nzc6NiqVmZB3huH5: [/ip4/192.168.40.164/tcp/20006]}
I0321 07:39:09.779593       1 tunnel.go:378] Success proxy for {tcp master1 172.17.0.3:9376}

**Comment by chunyeow** [comment]
The following error is more relevant on the related HTTPS. 
curl: (35) error:0A000126:SSL routines::unexpected eof while reading

====================================================
I0322 08:35:36.250879       1 loadbalancer.go:732] Dial libp2p network between hostname-lb-edge-5d69f9d984-kg5fv - {tcp node5 172.17.0.5:9376}
E0322 08:36:12.250189       1 http.go:34] read http request err: malformed HTTP request "\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x06\x9e\xf1\xa3`*{\x83\xd2e\xe0\x82\xba\x05\x12\x9a\x9e'V\xac_A\xb6k(hTU\x8d\x03s\xff e[\v|\x1a\xdc\"\xfa\xe7\x18\x91\xfad\xef\x86\xe8%\xc4z\xb1\xbf\xcf\xf12\xffY1WO\xa6\\\x1c\x00>\x13\x02\x13\x03\x13\x01\xc0,\xc00\x00\x9f̨̩̪\xc0+\xc0/\x00\x9e\xc0$\xc0(\x00k\xc0#\xc0'\x00g\xc0"
E0322 08:36:16.749157       1 http.go:34] read http request err: malformed HTTP request "\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03Ҳ(B\x93\x10-\x18w\xd1R\x95\xa4]E-\xac\x97\x10\x0f\xbfV\xefT\x1dnz.u\x86\xbb\xfd G\xbd\xbd?\xb8Yj\xd1\xcf\xf4\x9f\x85\xc2Y\xca\xdf\x1e\xe3\x8e\xd1\x1fXH.{{uӎȫv\x00>\x13\x02\x13\x03\x13\x01\xc0,\xc00\x00\x9f̨̩̪\xc0+\xc0/\x00\x9e\xc0$\xc0(\x00k\xc0#\xc0'\x00g\xc0"
