### ISSUE TITLE
通过edgemesh完成Ros的跨子网访问问题

### ISSUE THREAD

**Issue by a732264856** [kubeedge/edgemesh#455]
**What happened**:
边端局域网的ros节点连接不到云端的rosmaster节点,pod日志如下图所示
![erroor](https://user-images.githubusercontent.com/71765455/227419600-586070f7-f9aa-4b9a-bc17-73a90d659800.jpg)

roscore跟Listener节点显示是正常的，pod日志如下图
![listen](https://user-images.githubusercontent.com/71765455/227419541-36ae4be3-13e5-482c-9912-54745f56de4d.jpg)
![roscore](https://user-images.githubusercontent.com/71765455/227419542-3d6c7e54-6481-41d2-8dbd-9d5432af06e9.jpg)

创建的service与pod如下图
![service](https://user-images.githubusercontent.com/71765455/227419735-99f07608-3dd6-4587-bdc6-bafd798c9bab.png)
![pod](https://user-images.githubusercontent.com/71765455/227419752-f8b68fe1-891f-444e-bac2-444db71c7832.png)
使用的部署文件内容如下所示：
############################
############################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: roscore-deployment
  labels:
    app: ros1
    node: roscore
spec:
  replicas: 1
  selector:
    matchLabels:
      node: roscore
  template:
    metadata:
      labels:
        node: roscore
    spec:
      containers:
      - name: roscore
        tty: true
        image: tomoyafujita/ros:noetic
        command: ["/bin/bash", "-c"]
        args: ["source /opt/ros/$ROS_DISTRO/setup.bash && roscore"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11311
          name: roscoreport
      nodeSelector:
        nodetype: master
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

---

### This is required to map to app roscore so that other pods can DNS rosmaster IP address dynamically.
apiVersion: v1
kind: Service
metadata:
  name: rosmaster
  labels:
    app: ros1
    node: roscore
spec:
  #clusterIP: None
  ports:
    - port: 11311
       targetPort: 11311
       protocol: TCP
  selector:
    node: roscore

---

##################
##################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: talker-deployment
  labels:
    app: ros1
    node: talker
spec:
  replicas: 1
  selector:
    matchLabels:
      node: talker
  template:
    metadata:
      labels:
        node: talker
    spec:
      containers:
      - name: publisher
        tty: true
        image: tomoyafujita/ros:noetic
        command: ["/bin/bash", "-c"]
        args: ["source /opt/ros/$ROS_DISTRO/setup.bash && until rostopic list; do sleep 1; done && rosrun roscpp_tutorials talker"]
        imagePullPolicy: IfNotPresent
        env:
        - name: ROS_MASTER_URI
          value: http://rosmaster:11311
        - name: ROS_HOSTNAME
          value: ros-talker
      nodeSelector:
        nodetype: worker

---

### This is required to map to app publisher so that other pods can DNS IP address dynamically.
apiVersion: v1
kind: Service
metadata:
  name: ros-talker
  labels:
    app: ros1
    node: talker
spec:
  clusterIP: None
  selector:
    node: talker

---

####################
####################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-deployment
  labels:
    app: ros1
    node: listener
spec:
  replicas: 1
  selector:
    matchLabels:
      node: listener
  template:
    metadata:
      labels:
        node: listener
    spec:
      containers:
      - name: subscription
        tty: true
        image: tomoyafujita/ros:noetic
        command: ["/bin/bash", "-c"]
        args: ["source /opt/ros/$ROS_DISTRO/setup.bash && until rostopic list; do sleep 1; done && rosrun rospy_tutorials listener.py"]
        imagePullPolicy: IfNotPresent
        env:
        - name: ROS_MASTER_URI
          value: http://rosmaster:11311
        - name: ROS_HOSTNAME
          value: ros-listener
      nodeSelector:
        nodetype: master
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

---

### This is required to map to app subscription so that other pods can DNS IP address dynamically.
apiVersion: v1
kind: Service
metadata:
  name: ros-listener
  labels:
    app: ros1
    node: listener
spec:
  clusterIP: None                                                      
  selector:
    node: listener

**What you expected to happen**:
边上的talker节点可以连接至云端的roscore，云端的listener节点可以接收到边上的talker节点发送的话题信息

**How to reproduce it (as minimally and precisely as possible)**:
参考https://github.com/fujitatomoya/ros_k8s/blob/master/docs/ROS_Deployment_Demonstration.md

kubectl label nodes <yourMasterNodeName> nodetype=master
kubectl label nodes <yourEdgeNodeName> nodetype=worker
在主节点和边节点分别docker pull tomoyafujita/ros:noetic
kubectl apply -f deployment.yaml    文件内容在上面已经全部给出

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version: 1.13.0
- Kubernetes version (use `kubectl version`): 1.20.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.8.2
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):  2 U
    - OS (e.g. `cat /etc/os-release`):  Ubuntu18.04
    - Kernel (e.g. `uname -a`):  4.15.0
    - Go version (e.g. `go version`):  1.17.3
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`): 1.8.2
    - Hardware configuration (e.g. `lscpu`): 8 U
    - OS (e.g. `cat /etc/os-release`): Ubuntu18.04
    - Kernel (e.g. `uname -a`): 5.4.95-050495-generic
    - Go version (e.g. `go version`): 1.17.3
    - Others:

  </details>

**Comment by a732264856** [comment]
这是边端edgemesh的运行日志
![edgemesh1](https://user-images.githubusercontent.com/71765455/227420743-db63db92-c938-4a05-b427-4207460617d8.jpg)
![edgemesh2](https://user-images.githubusercontent.com/71765455/227420790-29372451-9c4f-477b-afcf-4c4fff8e73d4.png)

这是云端edgemesh的运行日志

![cloud1](https://user-images.githubusercontent.com/71765455/227421067-90c5f247-f726-4c94-9751-2b703948d468.jpg)
![cloud2](https://user-images.githubusercontent.com/71765455/227421071-3ba27d3f-8dba-4c53-b143-b3e8f6c43c70.png)
![cloud3](https://user-images.githubusercontent.com/71765455/227421074-4f631f10-9215-465f-8e9e-adfe6da42bd8.png)
![cloud4](https://user-images.githubusercontent.com/71765455/227421079-66840887-fc7c-4f5b-a374-19419c967575.jpg)

**Comment by a732264856** [comment]
案例参考为 https://github.com/fujitatomoya/ros_k8s/blob/master/docs/ROS_Deployment_Demonstration.md

**Comment by a732264856** [comment]
因为edgemesh的中继节点问题
https://zhuanlan.zhihu.com/p/585749690问题16

设置中继节点以后，每次部署之后，重启edgemesh-agent可以连接成功，但是为什么要每次都重启呢，还在寻找原因

**Comment by a732264856** [comment]
进一步的问题，卸载edgemesh重装以后，第一次apply部署文件，ros的边端节点可以正常发送信息，在云上使用kubectl logs -f PodName也能看到信息。但是第二次apply部署文件，边上的节点便连接不上ros的主节点了，kubectl logs查看pod日志也是空的。边端agent每次重启如下图显示
![21509b0db736f9d9192d31c1104d222](https://user-images.githubusercontent.com/71765455/227461383-6711a2d0-86ad-4d1b-a153-bb1eb272dfb7.jpg)

**Comment by a732264856** [comment]
云端的edgemesh-agent日志显示rosmaster节点的端口号访问被拒绝（这个端口号应该是被service集群中的所有pod可以访问的）
![1679663814082](https://user-images.githubusercontent.com/71765455/227531502-8339b670-f21e-4dac-b63a-ed69236d778d.png)
![1679663860901](https://user-images.githubusercontent.com/71765455/227531549-b34de82a-f236-4412-8f34-68777cf76390.jpg)

**Comment by Poorunga** [comment]
直接访问此后端： 10.244.0.90:11311 看看此后端能不能被访问。edgemesh仅能访问正常运行的后端服务
