### ISSUE TITLE
ingress反向代码边端的服务返回timeOut

### ISSUE THREAD

**Issue by fumenglin** [kubeedge/edgemesh#464]
**What happened**:
通过edgemesh部署，云端访问边端服务，nodePort和云上容器内都可以访问，将服务加入ingress里就外面就无法访问，但是如果ingress里是配置的云上的服务就可以访问；ingress类型：ingress-nginx,kong都试过，都是一样的；
ingress配置：
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: whoami
            port:
              number: 80
        path: /admin
        pathType: Prefix
ingress-contr日志:
2023/04/26 12:17:37 [error] 3519#3519: *559633 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.123.187, server: cloud.domain.com, request: "GET /foo HTTP/1.1", upstream: "http://172.18.0.1:80/foo", host: "cloud.domain.com:8881"
192.168.123.187 - - [26/Apr/2023:12:17:41 +0000] "GET /foo HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.58" 479 8.616 [default-whoami-80] [] 172.18.0.1:80, 172.18.0.6:80 0, 0 5.000, 3.615 504, - c6bf6fc0047a534e26af0e8635588e32
2023/04/26 12:17:46 [error] 3518#3518: *562513 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.123.187, server: cloud.domain.com, request: "GET /bar HTTP/1.1", upstream: "http://172.18.0.1:80/bar", host: "cloud.domain.com:8881"
2023/04/26 12:17:51 [error] 3518#3518: *562513 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.123.187, server: cloud.domain.com, request: "GET /bar HTTP/1.1", upstream: "http://172.18.0.6:80/bar", host: "cloud.domain.com:8881"
2023/04/26 12:17:56 [error] 3518#3518: *562513 upstream timed out (110: Operation timed out) while connecting to upstream, client: 192.168.123.187, server: cloud.domain.com, request: "GET /bar HTTP/1.1", upstream: "http://172.18.0.1:80/bar", host: "cloud.domain.com:8881"
192.168.123.187 - - [26/Apr/2023:12:17:56 +0000] "GET /bar HTTP/1.1" 504 562 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.58" 479 15.003 [default-whoami-80] [] 172.18.0.1:80, 172.18.0.6:80, 172.18.0.1:80 0, 0, 0 5.001, 5.001, 5.001 504, 504, 504 6bd58abd561153bf40b63d689af8f0a6

从上面的日志看最后直接访问的边端的Ip，故没有成功；

在edge上没有日志出现，怀疑是没有拦截到流量，在服务上也添加了labels：service.kubernetes.io/service-proxy-name: ""

**What you expected to happen**:
 因为边端会自动下发很多的服务供云端访问，故edgemesh+ingress实现云端的服务访问
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version:v1.13.2
- Kubernetes version (use `kubectl version`):v1.26.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.12
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):  8核16G
    - OS (e.g. `cat /etc/os-release`):
            NAME="openEuler"
          VERSION="22.09"
          ID="openEuler"
          VERSION_ID="22.09"
          PRETTY_NAME="openEuler 22.09"
          ANSI_COLOR="0;31"
    - Kernel (e.g. `uname -a`):
    Linux master01 5.10.0-106.18.0.68.oe2209.x86_64 #1 SMP Wed Sep 28 07:03:00 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
    - Go version (e.g. `go version`):1.19.0
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>
     同上
    - edgecore version (e.g. `edgecore --version`): 同上
    - Hardware configuration (e.g. `lscpu`):同上
    - OS (e.g. `cat /etc/os-release`): 同上
    - Kernel (e.g. `uname -a`):同上
    - Go version (e.g. `go version`):同上
    - Others:

  </details>

**Comment by Poorunga** [comment]
Ingress的原理是怎么样的，是不是把流量分发导入到ClusterIP+Port？
所以建议先从云上通过ClusterIP+Port的方式访问边缘的后端服务看看能不能行，能行我理解就没问题。

**Comment by fumenglin** [comment]
通过 CLUSTER-IP:Port在云端是可以访问的，但是通过ingress就无法访问

**Comment by fumenglin** [comment]
![1682562066048](https://user-images.githubusercontent.com/15940670/234743377-346848bd-951a-4432-9674-d3a6126921f0.png)
这个地址是边端的地址

**Comment by fumenglin** [comment]
在配置ingess的Annotations需要加上
nginx.ingress.kubernetes.io/service-upstream: "true"
描述：默认 Nginx 以 Service 中 Pod 的 IP 和端口为 Upstream 中的成员列表，该参数为 true 时，将以 Service 的 ClusterIP 和端口为被代理入口，该功能避免了因 Pod 漂移带来的 Upstream 的配置变化

**Comment by Poorunga** [comment]
从日志看，流量进过ingress后，直接发到podIP了，然而目前edgemesh不支持代理转发podIP的流量；

edgemesh-gateway组件，也具备类似ingress的功能，你可以参考参考：https://edgemesh.netlify.app/guide/edge-gateway.html
