### ISSUE TITLE
[OSPP] Container Network supports CNI features

### ISSUE THREAD

**Issue by Poorunga** [kubeedge/edgemesh#465]
### project name:
Container network supports edge CNI feature

### project description:
At present, the EdgeMesh project already supports K8s Service-based traffic proxy and forwarding functions, and can access services in another area across subnets through p2p tunnels. EdgeMesh can access the backend service through the service domain name or the ClusterIP mapped to the domain name. However, EdgeMesh currently does not support assisting Pods to access another backend service through the Pod IP. This project needs to enable EdgeMesh to support the ability of CNI plug-ins similar to K8s. Referring to flannel and calico, etc., it is necessary to add node Pod network division and container IP allocation, and support proxy Pod IP granularity traffic forwarding, so that Pods in different networks You can directly access each other through Pod IP.

### Skill Requirements:
Linux, Golang, Kubernetes, CNI

### Output standard:
1. Develop node network division and container IP allocation functions based on EdgeMesh, compatible with CNI standards
2. Based on EdgeMesh, develop Pod IP traffic proxy and forwarding functions that support cross-subnets, and are compatible with CNI standards
3. Submit demos and documentation, and write new feature introduction articles

#### Basic tasks:
- [Target: Get familiar with the kubeedge gameplay quickly and simulate an edge computing environment] Able to build the entire kubeedge cluster environment, not limited to virtual machines, real physical machines, and cloud servers; the kubeedge environment has at least one cloud LAN and one edge LAN. The network topology is as follows (for reference only):
![image](https://user-images.githubusercontent.com/43004096/236430786-7286ef43-a9ca-42df-a3fe-188fc3a9c722.png)
- [Target: Quickly understand container network-related knowledge based on kubeedge] Deploy and run kube-proxy and CNI plug-ins (not limited to flannel, calicao, cilium, etc.) on edge nodes. You can refer to https://github. com/kubeedge/kubeedge/issues/2677
- [Objective: Discover the core problem to be solved: the current mainstream cni plug-in does not have the ability to forward traffic across subnets, and it relies on the network to be reachable at the third layer] Create an edge application and expose a Service. Try to explain why accessing this service via ClusterIP on the cloud LAN cannot be accessed, but accessing this service via ClusterIP on the edge LAN can be accessed (the more detailed the better)
- [Target: Quickly get familiar with edgemesh gameplay] Deploy edgemesh components in the kubeedge cluster, and verify that all instances given by the official website have passed, you can refer to https://edgemesh.netlify.app/guide/test-case.html
- [Objective: quickly learn the principle of edgemesh, and quickly discover the core problems to be solved: although edgemesh currently supports the cross-subnet traffic forwarding capability at the ClusterIP level, it does not yet have the traffic forwarding capability of PodIP] Try to explain why the LAN on the cloud passes ClusterIP can access this service (if you only answer because edgemesh is installed, you will not get points, you need to answer clearly the principle), but you cannot access this application through PodIP (the more detailed the better)

#### Advanced tasks(Can put forward ideas also OK, have code implementation can add points.):
- [Target: Try to solve the problem in advance, and also quickly learn the principle of edgemesh and CNI; solve the problem by using the existing open source CNI project] Through the design and implementation of some solutions, let edgemesh have the following capabilities: CNI basic function - container network segment Divide (allows direct reference to existing open source CNI plug-in code) CNI basic function - podIP traffic forwarding (allows direct reference to existing open source CNI plug-in code)
- [Target: Challenge goal] By designing and implementing some solutions, the podIP traffic in the same LAN can be forwarded using the capabilities of the CNI plug-in itself, and only cross-subnet podIP traffic can be forwarded through libp2p

---

### 项目名称：
容器网络支持边缘CNI特性

### 项目描述：
目前EdgeMesh项目已经支持基于K8s Service的流量代理与转发功能，能够通过p2p隧道的方式跨子网访问另一个区域的服务。EdgeMesh可以通过服务域名或者域名映射的ClusterIP访问到后端服务，然而，EdgeMesh当前还是不支持协助Pod通过Pod IP访问另一个后端服务。本项目需要让EdgeMesh支持类似K8s的CNI插件的能力，参考flannel和calico等，需要新增节点Pod网络划分与容器IP分配，以及支持代理Pod IP粒度的流量转发，使得处于不同网络内的Pod之间可以直接通过Pod IP直接互访。

### 技能要求：
Linux, Golang, Kubernetes, CNI

### 产出标准：
1. 基于EdgeMesh开发节点网络划分与容器IP分配功能，兼容CNI标准
2. 基于EdgeMesh开发支持跨子网的Pod IP流量代理与转发功能，兼容CNI标准
3. 提交使用demo和使用文档，撰写新特性宣传介绍文章

#### 基础任务：
- 【目标：快速熟悉kubeedge玩法，并且模拟一个边缘计算环境】能够搭建起整个kubeedge集群环境，不限虚拟机、真实物理机、云服务器；kubeedge环境至少具备一个云上局域网，一个边缘局域网。网络拓扑如下所示（仅供参考）：
![image](https://user-images.githubusercontent.com/43004096/236430786-7286ef43-a9ca-42df-a3fe-188fc3a9c722.png)
- 【目标：基于kubeedge快速了解容器网络相关知识】在边缘节点上部署并运行kube-proxy和CNI插件（不限制种类，可以是flannel、calicao、cilium等等），可以参考https://github.com/kubeedge/kubeedge/issues/2677
- 【目标：发现课题要解决的核心问题：当前主流的cni插件并不具备跨子网流量转发的能力，本身依赖网络三层可达】创建边缘应用，并暴露出一个Services。尝试解释为什么在云上局域网通过ClusterIP访问此服务无法访问通，然而在边缘局域网通过ClusterIP访问此服务可以访问通（越详细越好）
- 【目标：快速熟悉edgemesh玩法】在kubeedge集群部署起edgemesh组件，并验证通过所有官网给的实例，可以参考https://edgemesh.netlify.app/guide/test-case.html
- 【目标：快速学习edgemesh原理，快速发现课题要解决的核心问题：edgemesh目前虽然支持ClusterIP层面的跨子网流量转发能力，但是还不具备PodIP的流量转发能力】尝试解释为什么在云上局域网通过ClusterIP访问此服务可以通（如果仅回答因为装了edgemesh不得分，需要回答清楚原理），然而通过PodIP访问此应用不能通（越详细越好）

#### 高阶任务（能提出思路也行，有代码实现可加分）：
- 【目标：尝试提前解决问题，同时也快速学习edgemesh原理与CNI原理；通过借助已有开源CNI项目解决问题】通过设计并实现一些方案，让edgemesh具备如下能力：CNI基础功能——容器网段划分（允许直接引用已有的开源CNI插件代码）CNI基础功能——podIP的流量转发（允许直接引用已有的开源CNI插件代码）
- 【目标：挑战目标】通过设计并实现一些方案，让同一局域网内的podIP流量转发使用CNI插件自身的能力，仅有跨子网的podIP流量转发通过libp2p转发

**Comment by fujitatomoya** [comment]
@Poorunga coming from slack discussion, i was not clear on if this is going to be either way for user experience.

- edgemesh will be compatible as CNI? so that user can bind edgemesh as CNI-plugin to the pods?
- Or, edgemesh will be capable of proxy to forward the pod IP basis? that means, edgemesh will not be CNI compatible, but the communication can be forwared based on pod IP? (pods can be bound to other CNIs like hostnic, cilium, calico and so on.)

i might be mistaken since i really do not have much experience for edgemesh.

**Comment by Poorunga** [comment]
@fujitatomoya Thanks for the attention to edgemesh. To be precise, edgemesh will be a CNI plug-in in the future. It will have the basic functions of CNI.

**Comment by fujitatomoya** [comment]
I see, that sounds really interesting. AFAIK, CNI with edge autonomy features would be pretty much new, i guess that is the original driver for edgemesh. thanks!

**Comment by JiaweiGithub** [comment]
I have a question, the idea of ​​edgemesh's cni function is to complete all functions without other cni plug-ins, such as calico and flannel. Or another one, some cni components must be combined to achieve complete capabilities.

**Comment by JiaweiGithub** [comment]
Recently discovered an interesting project for cross cluster network communication, which may provide some reference value.https://github.com/liqotech/liqo.

**Comment by lengcangche-gituhub** [comment]
> @fujitatomoya Thanks for the attention to edgemesh. To be precise, edgemesh will be a CNI plug-in in the future. It will have the basic functions of CNI.

So can edgemesh be used as a CNI plugin now?
