### ISSUE TITLE
The communication between pods on the same edge node failed

### ISSUE THREAD

**Issue by mhh12121** [kubeedge/edgemesh#469]
**What happened**:
I deployed two deps on the same edge node, and tried to let them communicate with each other by calling **service FQDN** but failed;
I got 
![image](https://github.com/kubeedge/edgemesh/assets/7931370/14ddf4c7-19c5-491a-a487-13ad301ff090)

And the edgemesh on the edgenode would show SERVFAIL error

![image](https://github.com/kubeedge/edgemesh/assets/7931370/f7d01c8b-3c78-4c57-96bd-d81e0f09b7eb)

**What you expected to happen**:
The pods on the same edge node could communicate with each other;

**How to reproduce it (as minimally and precisely as possible)**:
Just deploy two pods on the same edge node;

**Anything else we need to know?**:

I didn't switch on cloudcore **dynamicController**, does it matter? 

**Environment**:
- EdgeMesh version:
v1.13.0
- Kubernetes version (use `kubectl version`):
v1.20.15
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
v1.13.0
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    v1.13.0
    - Hardware configuration (e.g. `lscpu`):
   2g2u
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
refer to https://edgemesh.netlify.app/guide/#prerequisites and https://edgemesh.netlify.app/guide/edge-kube-api.html

**Comment by mhh12121** [comment]
Thank you for your reply @Poorunga   Indeed I noticed that they might need some meta info from edge api-server. But I don't want to expose my cluster info( like services, namespaces etc) to edge node, any other way to enable apps on the same edge node to communicate with each other( instead of service, endpoint) ? Is it possible to achieve it with MQTT ?

**Comment by Poorunga** [comment]
When edgemesh is running, it must be connected to edge-api-server. And Edgemesh's domain name resolution needs to obtain metadata from edgecore's metaserver module, and the metaserver module needs to communicate with cloudcore's syncController module to obtain metadata, such as services and endpoints, etc., edgemesh needs to consume these metadata to provide normal domain name resolution function.

**Comment by mhh12121** [comment]
Thank you @Poorunga . That's exactly wat I saw. However due to my personal requirement, I need to restrict the edge to have  limited access to the whole cluster's metadata(maybe only specific namespaces but not the whole cluster anyway).
I'm afraid that currently kubeedge does not fully fulfill my requirements, but i would try to do customized development on it and still follow up the latest version.
