### ISSUE TITLE
Telnet: bad address 'tcp-echo-cloud-svc.cloudzone'

### ISSUE THREAD

**Issue by JiaweiGithub** [kubeedge/edgemesh#471]
**What happened**:
The edge container failed to resolve the domain name, and executing nslookup on the edge node also failed to resolve it. I have reviewed this document（ https://zhuanlan.zhihu.com/p/585749690 ）, but still cannot resolve it. Do you have any suggestions for a solution?

edgenode
<img width="913" alt="image" src="https://github.com/kubeedge/edgemesh/assets/8078735/1bd9237e-ffa1-4682-ae0a-67c6d33835a8">

cloudnode pod
<img width="703" alt="image" src="https://github.com/kubeedge/edgemesh/assets/8078735/9c6c5746-ac4f-4c98-9090-1e455c480bc3">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version: 1.13.2
- Kubernetes version (use `kubectl version`):  v1.20
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.13.0
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
As long as a domain name can be resolved normally, I understand that the domain name resolution module of edgemesh is normal. Edgemesh's domain name resolution needs to obtain metadata from edgecore's metaserver module, and the metaserver module needs to communicate with cloudcore's syncController module to obtain metadata, such as services and endpoints, etc., edgemesh needs to consume these metadata to provide normal domain name resolution function. If these metadata cannot be sent to the edge node normally, the domain name resolution of edgemesh will be affected.

**Comment by JiaweiGithub** [comment]
> As long as a domain name can be resolved normally, I understand that the domain name resolution module of edgemesh is normal. Edgemesh's domain name resolution needs to obtain metadata from edgecore's metaserver module, and the metaserver module needs to communicate with cloudcore's syncController module to obtain metadata, such as services and endpoints, etc., edgemesh needs to consume these metadata to provide normal domain name resolution function. If these metadata cannot be sent to the edge node normally, the domain name resolution of edgemesh will be affected.

Thanks, after restarting the edgecore and regenerating the edgemesh agent on the edge, it can now work.
<img width="804" alt="image" src="https://github.com/kubeedge/edgemesh/assets/8078735/6bedff1c-9fc5-48e9-94b8-49954fbce68b">
