### ISSUE TITLE
failed to negotiate security protocol: privnet: could not read full nonce

### ISSUE THREAD

**Issue by wuming333666** [kubeedge/edgemesh#480]
**What happened**:
when edgemesh restart it cannot connect to the  relayNodes； and log is
```
[Bootstrap] failed to bootstrap with {xxxx: [/ip4/10.10.xx.xxx/tcp/20006]}: failed to dial xxx:
  * [/ip4/10.10.xx.xxx/tcp/20006] failed to negotiate security protocol: privnet: could not read full nonce
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version: 1.12
- Kubernetes version (use `kubectl version`): 1.20
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.12
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
two edgemesh-agent need have same psk
