### ISSUE TITLE
The edgemesh agent shutdown in 30s, and keep on restarting.

### ISSUE THREAD

**Issue by sunblack110** [kubeedge/edgemesh#481]
**What happened**:
The edgemesh agent shutdown in 30s, and keep on restarting.
**What you expected to happen**:
It should run correct and I would access edge side service via API
**How to reproduce it (as minimally and precisely as possible)**:
I just setup in the app-store, and it is not working, I set the env like NODE_NAME, and NAME_SPACE, and set also the log version to 8.
**Anything else we need to know?**:

**Environment**:
- EdgeMesh version: latest
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12", GitCommit:"b058e1760c79f46a834ba59bd7a3486ecf28237d", GitTreeState:"clean", BuildDate:"2022-07-13T14:53:39Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 
KubeEdge v1.9.2
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`): NAME="Ubuntu" VERSION="20.04.5 LTS (Focal Fossa)"
    - Kernel (e.g. `uname -a`):Linux k8s-master 5.4.0-146-generic #163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`): CentOS 7.6
    - Kernel (e.g. `uname -a`):Linux centos7 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
    - Go version (e.g. `go version`):
    - Others:

  </details>

The cloudcore.yml :
apiVersion: cloudcore.config.kubeedge.io/v1alpha2
kind: CloudCore
kubeAPIConfig:
  kubeConfig: ""
  master: ""
modules:
  cloudHub:
    advertiseAddress:
    - 119.3.46.150
    nodeLimit: 1000
    tlsCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsCertFile: /etc/kubeedge/certs/edge.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/edge.key
    unixsocket:
      address: unix:///var/lib/kubeedge/kubeedge.sock
      enable: true
    websocket:
      address: 0.0.0.0
      enable: true
      port: 10000
    quic:
      address: 0.0.0.0
      enable: false
      maxIncomingStreams: 10000
      port: 10001
    https:
      address: 0.0.0.0
      enable: true
      port: 10002
  cloudStream:
    enable: true
    streamPort: 10003
    tunnelPort: 10004
  dynamicController:
    enable: true
  router:
    enable: false
  iptablesManager:
    enable: true
    mode: external

edge-agent.yml:
apiVersion: agent.edgemesh.config.kubeedge.io/v1alpha1
commonConfig:
  configMapName: edgemes-slrpl5-agent-cfg
  dummyDeviceIP: 169.254.96.16
  dummyDeviceName: edgemesh0
goChassisConfig:
  loadBalancer:
    consistentHash:
      load: 1.25
      partitionCount: 100
      replicationFactor: 10
    defaultLBStrategy: RoundRobin
    supportLBStrategies:
    - RoundRobin
    - Random
    - ConsistentHash
  protocol:
    tcpBufferSize: 8192
    tcpClientTimeout: 5
    tcpReconnectTimes: 3
kind: EdgeMeshAgent
modules:
  edgeDNS:
    listenPort: 53
  edgeProxy:
    enable: true
    listenPort: 40001
    socks5Proxy:
      enable: true
      listenPort: 10800
    subNet: 10.96.0.0/12
  tunnel:
    enable: true
    enableHolePunch: true
    listenPort: 20006
    security:
      tlsCaFile: /etc/kubeedge/edgemesh/agent/acls/rootCA.crt
      tlsCertFile: /etc/kubeedge/edgemesh/agent/acls/server.crt
      tlsPrivateKeyFile: /etc/kubeedge/edgemesh/agent/acls/server.key
      token: "48fc8a601acb538a9b01fdf913edcb793fb6981758266f7f678d940ea72e935d.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODk2NTA3ODN9.dQvNDunQlfkbGUr4z5UTmeo9JCqwT0U76Zq8p8OiSm0"

log:
.....
hulu-cloud-customer-dev/hulu-cloud-iot-service:http -p tcp -m tcp --dport 32074 -j DNAT --to-destination 169.254.96.16:36906]
I0717 14:08:52.799096       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -C KUBE-NODEPORT-HOST -t nat -m comment --comment hulu-cloud-customer-dev/hulu-cloud-iot-service:http -p tcp -m tcp --dport 32074 -j DNAT --to-destination 169.254.96.16:36906]
I0717 14:08:52.800560       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -C KUBE-NODEPORT-NON-LOCAL -t filter -m comment --comment hulu-cloud-customer-dev/hulu-cloud-iot-service:http -p tcp -m tcp --dport 36906 -m state --state NEW -j ACCEPT]
I0717 14:08:52.801715       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -C KUBE-PORTALS-CONTAINER -t nat -m comment --comment kubesphere-logging-system/logsidecar-injector-admission -p tcp -m tcp --dport 443 -d 10.106.31.157 -j DNAT --to-destination 169.254.96.16:45356]
I0717 14:08:52.803172       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -C KUBE-PORTALS-HOST -t nat -m comment --comment kubesphere-logging-system/logsidecar-injector-admission -p tcp -m tcp --dport 443 -d 10.106.31.157 -j DNAT --to-destination 169.254.96.16:45356]
I0717 14:08:52.804668       1 proxier.go:378] "Userspace syncProxyRules complete" elapsed="575.193032ms"
I0717 14:08:52.804684       1 bounded_frequency_runner.go:296] userspace-proxy-sync-runner: ran, next possible in 1s, periodic in 30s
I0717 14:08:54.103981       1 config.go:171] "Calling handler.OnEndpointsUpdate"
I0717 14:08:56.107233       1 config.go:171] "Calling handler.OnEndpointsUpdate"
I0717 14:08:58.112117       1 config.go:171] "Calling handler.OnEndpointsUpdate"
I0717 14:09:00.118406       1 config.go:171] "Calling handler.OnEndpointsUpdate"
I0717 14:09:02.125624       1 config.go:171] "Calling handler.OnEndpointsUpdate"
I0717 14:09:04.129589       1 config.go:171] "Calling handler.OnEndpointsUpdate"
I0717 14:09:06.132427       1 config.go:171] "Calling handler.OnEndpointsUpdate"
I0717 14:09:08.135490       1 config.go:171] "Calling handler.OnEndpointsUpdate"
I0717 14:09:10.140471       1 config.go:171] "Calling handler.OnEndpointsUpdate"
I0717 14:09:12.149695       1 config.go:171] "Calling handler.OnEndpointsUpdate"
I0717 14:09:14.150125       1 config.go:171] "Calling handler.OnEndpointsUpdate"
I0717 14:09:16.155339       1 config.go:171] "Calling handler.OnEndpointsUpdate"
I0717 14:09:18.157913       1 config.go:171] "Calling handler.OnEndpointsUpdate"
I0717 14:09:20.167611       1 config.go:171] "Calling handler.OnEndpointsUpdate"
I0717 14:09:21.523437       1 core.go:35] Get os signal terminated
I0717 14:09:21.523464       1 core.go:40] Cleanup module EdgeDNS
I0717 14:09:21.545368       1 core.go:40] Cleanup module EdgeProxy
I0717 14:09:21.565572       1 module.go:36] Shutdown module EdgeProxy
I0717 14:09:21.566222       1 module.go:36] Shutdown module EdgeDNS
I0717 14:09:21.566357       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -C OUTPUT -t nat -m comment --comment handle ClusterIPs; NOTE: this must be before the NodePort rules -j KUBE-PORTALS-HOST]
I0717 14:09:21.568005       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -D OUTPUT -t nat -m comment --comment handle ClusterIPs; NOTE: this must be before the NodePort rules -j KUBE-PORTALS-HOST]
I0717 14:09:21.569639       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -C PREROUTING -t nat -m comment --comment handle ClusterIPs; NOTE: this must be before the NodePort rules -j KUBE-PORTALS-CONTAINER]
I0717 14:09:21.570767       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -D PREROUTING -t nat -m comment --comment handle ClusterIPs; NOTE: this must be before the NodePort rules -j KUBE-PORTALS-CONTAINER]
I0717 14:09:21.572617       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -C OUTPUT -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-HOST]
I0717 14:09:21.573853       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -D OUTPUT -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-HOST]
I0717 14:09:21.576070       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -C PREROUTING -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-CONTAINER]
I0717 14:09:21.577628       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -D PREROUTING -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-CONTAINER]
I0717 14:09:21.579158       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -C INPUT -t filter -m comment --comment Ensure that non-local NodePort traffic can flow -j KUBE-NODEPORT-NON-LOCAL]
I0717 14:09:21.580335       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -D INPUT -t filter -m comment --comment Ensure that non-local NodePort traffic can flow -j KUBE-NODEPORT-NON-LOCAL]
I0717 14:09:21.581257       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -F KUBE-PORTALS-CONTAINER -t nat]
I0717 14:09:21.583357       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -X KUBE-PORTALS-CONTAINER -t nat]
I0717 14:09:21.584773       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -F KUBE-PORTALS-HOST -t nat]
I0717 14:09:21.586255       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -X KUBE-PORTALS-HOST -t nat]
I0717 14:09:21.587391       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -F KUBE-NODEPORT-HOST -t nat]
I0717 14:09:21.588193       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -X KUBE-NODEPORT-HOST -t nat]
I0717 14:09:21.589286       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -F KUBE-NODEPORT-CONTAINER -t nat]
I0717 14:09:21.590903       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -X KUBE-NODEPORT-CONTAINER -t nat]
I0717 14:09:21.592450       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -F KUBE-NODEPORT-NON-LOCAL -t filter]
I0717 14:09:21.593995       1 iptables.go:462] running iptables: iptables [-w 5 -W 100000 -X KUBE-NODEPORT-NON-LOCAL -t filter]
I0717 14:09:21.595448       1 server.go:122] edgemesh-agent exited

**Comment by fisherxu** [comment]
/assign @Poorunga @JiaweiGithub 
Please help take a look, thanks :)

**Comment by Poorunga** [comment]
The edgemesh configuration in kubesphere has expired.
If you must use it, please specify the version of edgemesh-agent and edgemesh-server, for example: kubeedge/edgemesh-agent:v1.9.0

**Comment by sunblack110** [comment]
Wow, it works, bro. 2 days vs 1 second.....
