### ISSUE TITLE
run edgemesh-agent failed

### ISSUE THREAD

**Issue by xmxxiong** [kubeedge/edgemesh#492]
**What happened**:
bug:
I0818 15:47:33.639181       1 server.go:56] Version: v1.13.1-dirty
I0818 15:47:33.639237       1 server.go:92] [1] Prepare agent to run
I0818 15:47:33.640456       1 netif.go:96] bridge device edgemesh0 already exists
I0818 15:47:33.640515       1 server.go:96] edgemesh-agent running on EdgeMode
I0818 15:47:33.640527       1 server.go:99] [2] New clients
I0818 15:47:33.736510       1 server.go:106] [3] Register beehive modules
I0818 15:47:33.737011       1 module.go:34] Module EdgeDNS registered successfully
I0818 15:47:33.737205       1 server.go:68] Using userspace Proxier.
I0818 15:47:34.140896       1 module.go:127] Configure libp2p.ForceReachabilityPrivate()
I0818 15:47:34.336053       1 module.go:182] I'm {12D3KooWHQEjo6mRfiaLCNHL8Peo4zjJsymDMqryZiFMuYwnaWqt: [/ip4/172.18.8.182/tcp/20006 /ip4/127.0.0.1/tcp/20006]}
I0818 15:47:34.337244       1 module.go:204] Bootstrapping the DHT
I0818 15:47:34.436296       1 tunnel.go:433] [Bootstrap] bootstrapping to 12D3KooWHNwqeEjLp68MfqZ3vyepC3vdH5HuHA8xdVnZZRm863CZ
I0818 15:47:34.536764       1 tunnel.go:443] [Bootstrap] success bootstrapped with {12D3KooWHNwqeEjLp68MfqZ3vyepC3vdH5HuHA8xdVnZZRm863CZ: [/ip4/172.18.9.206/tcp/20006]}
I0818 15:47:34.537925       1 tunnel.go:80] Starting MDNS discovery service
I0818 15:47:34.537961       1 tunnel.go:93] Starting DHT discovery service
I0818 15:47:34.538199       1 module.go:34] Module EdgeTunnel registered successfully
I0818 15:47:34.538253       1 server.go:108] edgemesh-agent exited
F0818 15:47:34.538277       1 server.go:58] run edgemesh-agent failed: [
  register module edgeproxy error: new proxy server err: unable to create proxier: failed to initialize iptables: error checking rule: exit status 2: iptables v1.8.3 (legacy): Couldn't load match `comment':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
**What you expected to happen**:
edgemesh-agent work
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version:v1.13.1
- Kubernetes version (use `kubectl version`):v1.21.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):v1.13.1
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):ubuntu 20.04
    - Kernel (e.g. `uname -a`):6.2.0-26-generic
    - Go version (e.g. `go version`):
    - Others:iptables version: iptables v1.8.4 (legacy)

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):ubuntu 20.04
    - Kernel (e.g. `uname -a`):5.10.110
    - Go version (e.g. `go version`):
    - Others:iptables version:iptables v1.8.7 (nf_tables)

  </details>

**Comment by Poorunga** [comment]
Your linux kernel need  have iptables `comment`.

**Comment by zhushuaifeifei** [comment]
I0325 02:02:43.205688       1 server.go:58] Version: v1.13.0-beta.0.136+ca8ebc27189266-dirty
I0325 02:02:43.205960       1 server.go:94] [1] Prepare agent to run
I0325 02:02:43.207228       1 netif.go:96] bridge device edgemesh0 already exists
I0325 02:02:43.207592       1 server.go:98] edgemesh-agent running on EdgeMode
I0325 02:02:43.296172       1 server.go:101] [2] New clients
I0325 02:02:43.300400       1 server.go:108] [3] Register beehive modules
I0325 02:02:43.304885       1 module.go:34] Module EdgeDNS registered successfully
I0325 02:02:43.396794       1 server.go:68] Using userspace Proxier.
I0325 02:02:46.036925       1 util.go:273] Listening to tunl0 is meaningless, skip it.
I0325 02:02:46.098493       1 util.go:273] Listening to docker0 is meaningless, skip it.
I0325 02:02:46.098844       1 util.go:273] Listening to edgemesh0 is meaningless, skip it.
I0325 02:02:46.799705       1 module.go:189] I'm {12D3KooWQQsDnTJz128WcrMTApSgXtSsYGya7ghM73wkPEQ4Sz1E: [/ip4/[127.0.0.1/tcp/20006](http://127.0.0.1/tcp/20006) /ip4/[10.220.90.184/tcp/20006](http://10.220.90.184/tcp/20006)]}
I0325 02:02:46.801490       1 module.go:211] Bootstrapping the DHT
I0325 02:02:46.801651       1 tunnel.go:439] [Bootstrap] bootstrapping to 12D3KooW9yF6fZvnMC3zxXSrxZSq1JM8otuwz7uTQ7FjNfKtFxVK
I0325 02:02:47.596728       1 tunnel.go:449] [Bootstrap] success bootstrapped with {12D3KooW9yF6fZvnMC3zxXSrxZSq1JM8otuwz7uTQ7FjNfKtFxVK: [/ip4/[36.133.50.140/tcp/20006](http://36.133.50.140/tcp/20006)]}
I0325 02:02:47.800953       1 tunnel.go:86] Starting MDNS discovery service
I0325 02:02:47.801123       1 tunnel.go:99] Starting DHT discovery service
I0325 02:02:47.801480       1 module.go:34] Module EdgeTunnel registered successfully
W0325 02:02:47.801516       1 module.go:37] Module EdgeCNI is disabled, do not register
I0325 02:02:47.801545       1 server.go:110] edgemesh-agent exited
F0325 02:02:47.801565       1 server.go:60] run edgemesh-agent failed: [
  register module edgeproxy error: new proxy server err: unable to create proxier: failed to initialize iptables: error checking rule: exit status 2: iptables v1.8.3 (legacy): Couldn't load target `KUBE-NODEPORT-NON-LOCAL':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.

**Comment by zhushuaifeifei** [comment]
I0321 13:02:12.906861       1 server.go:58] Version: v1.16.0-dirty
I0321 13:02:12.907210       1 server.go:94] [1] Prepare agent to run
I0321 13:02:12.910147       1 netif.go:96] bridge device edgemesh0 already exists
I0321 13:02:12.910541       1 server.go:98] edgemesh-agent running on EdgeMode
I0321 13:02:12.910624       1 server.go:101] [2] New clients
I0321 13:02:12.999645       1 server.go:108] [3] Register beehive modules
I0321 13:02:13.002572       1 module.go:34] Module EdgeDNS registered successfully
I0321 13:02:13.003709       1 server.go:68] Using userspace Proxier.
I0321 13:02:15.199411       1 util.go:273] Listening to tunl0 is meaningless, skip it.
I0321 13:02:15.300927       1 util.go:273] Listening to docker0 is meaningless, skip it.
I0321 13:02:15.301906       1 util.go:273] Listening to edgemesh0 is meaningless, skip it.
I0321 13:02:16.095863       1 module.go:189] I'm {12D3KooWQQsDnTJz128WcrMTApSgXtSsYGya7ghM73wkPEQ4Sz1E: [/ip4/[127.0.0.1/tcp/20006](http://127.0.0.1/tcp/20006) /ip4/[10.220.90.184/tcp/20006](http://10.220.90.184/tcp/20006)]}
I0321 13:02:16.095987       1 module.go:211] Bootstrapping the DHT
I0321 13:02:16.096028       1 tunnel.go:439] [Bootstrap] bootstrapping to 12D3KooW9yF6fZvnMC3zxXSrxZSq1JM8otuwz7uTQ7FjNfKtFxVK
I0321 13:02:16.802671       1 tunnel.go:449] [Bootstrap] success bootstrapped with {12D3KooW9yF6fZvnMC3zxXSrxZSq1JM8otuwz7uTQ7FjNfKtFxVK: [/ip4/[36.133.50.140/tcp/20006](http://36.133.50.140/tcp/20006)]}
I0321 13:02:16.906432       1 tunnel.go:86] Starting MDNS discovery service
I0321 13:02:16.906560       1 tunnel.go:99] Starting DHT discovery service
I0321 13:02:16.907127       1 module.go:34] Module EdgeTunnel registered successfully
W0321 13:02:16.907307       1 module.go:37] Module EdgeCNI is disabled, do not register
I0321 13:02:16.907412       1 server.go:110] edgemesh-agent exited
F0321 13:02:16.907455       1 server.go:60] run edgemesh-agent failed: [
  register module edgeproxy error: new proxy server err: unable to create proxier: failed to initialize iptables: error checking rule: exit status 2: iptables v1.8.3 (legacy): Couldn't load target `KUBE-NODEPORT-NON-LOCAL':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.

]

**Comment by zhushuaifeifei** [comment]
I tried two versions but failed to run successfully，can you help me?
