### ISSUE TITLE
Edgemesh Gateway and Edgemesh Agent x509: certificate signed by unknown authority error

### ISSUE THREAD

**Issue by Mr-Verb** [kubeedge/edgemesh#494]
**What happened**:
Background on system, even though there is a section for it later on:
Running the K8s master node on a VM on a server run by my institution so it has its MASTER_IP which we use to ssh into it and its LOCAL_IP which is the address produced when running "ip route get 8.8.8.8"

The edgenode is run on my laptop which is running windows 10, so I am using a virtualbox VM with NAT network to connect to the institutions' VM.

- Created K8s cluster with sudo kubeadm init --flags, etc
- Installed Calico network addon
- Created the cloudcore pod with helm
- Installed CRDs
- Created edgemesh agent and edgemesh gateway with helm (same psk)
- Joined the edgenode to the master node with sudo keadm join

Followed the steps on the edgemesh guide to deploy edgemesh agent and gateway, created psk cipher, enabled Edge Kube-Api Endpoint and setup Edgemesh HA features. 

The problems started to arise when I went to test edgemesh with the test cases, as none of the services or pods were able to communicate between the cloud vm and edge device.

When getting the logs for the edgemesh gateway pod on the master node, it produced x509 certificate signed by unknown authority, even though I did not create any self signed certs. A similar thing happened with the edgemesh agent running on the master node:

**Edgemesh-gateway logs**
[edgemesh-gateway.log](https://github.com/kubeedge/edgemesh/files/12387268/edgemesh-gateway.log)

**Edgemesh-agent logs**
[edgemesh-agent.log](https://github.com/kubeedge/edgemesh/files/12387269/edgemesh-agent.log)

**What you expected to happen**:
Tests to run correctly

**How to reproduce it (as minimally and precisely as possible)**:
```bash Setup K8s cluster with sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=LOCAL_IP --apiserver-cert-extra-sans=MASTER_IP --kubernetes-version=1.23.15```

```bash kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml```
```bash kubectl apply -f https://docs.projectcalico.org/v3.25/manifests/calico.yaml```

```bash 
helm upgrade --install cloudcore ./cloudcore \
    --namespace kubeedge \
    --create-namespace -f ./cloudcore/values.yaml \
    --kubeconfig $HOME/.kube/config \
    --set cloudCore.modules.cloudHub.advertiseAddress[0]=$MASTER_IP \
    --set cloudCore.image.tag=1.23.15
```
```bash
helm upgrade --install edgemesh --namespace kubeedge \
    --set agent.image=kubeedge/edgemesh-agent:$EDGEMESH_VERSION \
    --set agent.relayNodes[0].nodeName=$MASTER_NODE_NAME \
    --set agent.relayNodes[0].advertiseAddress="{$MASTER_IP}" \
    --set agent.kubeAPIConfig.master=https://$MASTER_IP:6443 \
    --set agent.psk=$PSK_CIPHER_KEY \
    https://raw.githubusercontent.com/kubeedge/edgemesh/main/build/helm/edgemesh.tgz
```
```bash
helm upgrade --install edgemesh-gateway --namespace kubeedge \
    --set image=kubeedge/edgemesh-gateway:$EDGEMESH_VERSION \
    --set nodeName=$MASTER_NODE_NAME \
    --set relayNodes[0].nodeName=$MASTER_NODE_NAME \
    --set relayNodes[0].advertiseAddress="{$MASTER_IP}" \
    --set kubeAPIConfig.master=https://$MASTER_IP:6443 \
    --set psk=$PSK_CIPHER_KEY \
    https://raw.githubusercontent.com/kubeedge/edgemesh/main/build/helm/edgemesh-gateway.tgz
```
- In the cloudcore configmap (kubectl edit cm cloudcore -nkubeedge:
```yaml
modules:
...
    cloudStream:
        enable: true
...
    dynamicController:
        enable: true
```

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version:  v1.13.1-dirty
- Kubernetes version (use `kubectl version`): Client Version: v1.23.15, Server Version: v1.23.15
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.13.1
- <details><summary>Cloud nodes Environment:</summary>
    - Hardware configuration (e.g. `lscpu`): virtual machine with Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz
    - OS (e.g. `cat /etc/os-release`): Ubuntu 22.04.3 LTS
    - Kernel (e.g. `uname -a`): 5.15.0-78-generic
    - Go version (e.g. `go version`): go1.18.1 linux/amd64
    - Others: Calico network addon v3.25.0
  </details>
- <details><summary>Edge nodes Environment (virtual machine):</summary>
    - edgecore version (e.g. `edgecore --version`): 1.23.15-kubeedge-v1.13.1
    - Hardware configuration (e.g. `lscpu`): 
    - OS (e.g. `cat /etc/os-release`): Ubuntu 22.04.3 LTS
    - Kernel (e.g. `uname -a`):  6.2.0-26-generic
    - Go version (e.g. `go version`):
    - Others:

  </details>

Any help/insight will be very much appreciated, as I have been pulling my hair out over this for the last week

**Comment by Poorunga** [comment]
I'm anlysis your logs:
> istio.io/client-go/pkg/informers/externalversions/factory.gen.go:118: Failed to watch *v1alpha3.DestinationRule: failed to list *v1alpha3.DestinationRule: Get "https://MASTER_IP:6443/apis/networking.istio.io/v1alpha3/destinationrules?limit=500&resourceVersion=0": dial tcp MASTER_IP:6443: connect: no route to host

Is MASTER_IP an env var? Maybe MASTER_IP can not parse a valid IP address.

**Comment by Mr-Verb** [comment]
> I'm anlysis your logs:
> 
> > istio.io/client-go/pkg/informers/externalversions/factory.gen.go:118: Failed to watch *v1alpha3.DestinationRule: failed to list *v1alpha3.DestinationRule: Get "https://MASTER_IP:6443/apis/networking.istio.io/v1alpha3/destinationrules?limit=500&resourceVersion=0": dial tcp MASTER_IP:6443: connect: no route to host
> 
> Is MASTER_IP an env var? Maybe MASTER_IP can not parse a valid IP address.

I substituted my node's IP address with "MASTER_IP" before uploading the logs so I don't think it is that. Further down in the logs is when I start getting the x509 error so I think what you've found is the initial pod starting up and not immediately establishing a connection.

**Comment by Poorunga** [comment]
If your node and kube-apiserver are not in the same subnet, you need to use the edge Kube-API server function of kubeedge. For details, see: https://edgemesh.netlify.app/guide/edge-kube-api.html

**Comment by Mr-Verb** [comment]
Even after following the steps from the page mentioned above (https://edgemesh.netlify.app/guide/edge-kube-api.html) I am still getting the same error

I have also renewed the certs with sudo kubeadm certs renew all, deleted all the pods and no luck.

I finally setup a cluster on my laptop with only the master node, followed the kubeedge setup and edgemesh setup with it resulting in the same x509 error

**Comment by Poorunga** [comment]
>     --set kubeAPIConfig.master=https://$MASTER_IP:6443 \

no need to special kubeAPIConfig.master.

1. edgemesh-agent or edgemesh-gateway on cloud, will use k8s serviceAccount and RBAC to access kube-apiserver
2. edgemesh-agent or edgemesh-gateway on cloud, will use edgecore metaServer to access k8s metadata.

**Comment by Mr-Verb** [comment]
@Poorunga that fixed it!!! 
Thank you heaps!!!
My team and I are relatively new to Kubernetes  so it has been interesting learning about the nuances along the way.
