### ISSUE TITLE
Can't deploy edgemesh-agent on edge node RK3588？

### ISSUE THREAD

**Issue by victorming666** [kubeedge/edgemesh#512]
I installed EdgeMesh on a k8s+kubesphere+kubeedge cluster following the [installing guide of edgemesh](https://edgemesh.netlify.app/). Everything seems ok except I can't find the edgemesh-agent on the edge node(RK3588: Ubuntu20.04 on Arm64). I changed the tolerations policy according to the [this blog on kubesphere website](https://www.kubesphere.io/zh/blogs/kubesphere-kubeedge-edgemesh/#edgemesh-%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86), but no effects. Anybody can help?

**Comment by Piwriw** [comment]
Maybe you should offer more info or you can read the [edgemesh webstie](https://edgemesh.netlify.app/) more

**Comment by Poorunga** [comment]
Close it first. If there are other problems, you can open it again.
