### ISSUE TITLE
Can edgemesh support the latest version of kubeedge1.15？

### ISSUE THREAD

**Issue by kkkkeynoted** [kubeedge/edgemesh#516]
Recently, the version of Kubeedge was updated. Can edgemesh work properly on the latest version of Kubeedge?

**Comment by Poorunga** [comment]
Yes, and edgemesh will release v1.15 soon.

**Comment by CKchen0726** [comment]
I heard that KubeEdge has already been applied in the constellation cluster of Beijing University of Posts and Telecommunications, and it is a common consensus in the industry to use laser communication for satellite communication. I wonder if EdgeMesh has plans to support laser communication in the future?

**Comment by CKchen0726** [comment]
> Yes, and edgemesh will release v1.15 soon.

I heard that KubeEdge has already been applied in the constellation cluster of Beijing University of Posts and Telecommunications, and it is a common consensus in the industry to use laser communication for satellite communication. I wonder if EdgeMesh has plans to support laser communication in the future?

**Comment by Poorunga** [comment]
`I wonder if EdgeMesh has plans to support laser communication in the future?`

---
@CKchen0726  Not yet, but we can discuss technology and scenarios at community meetings
