### ISSUE TITLE
Supporting a function that will only be proxied if the tag is added

### ISSUE THREAD

**Issue by JiaweiGithub** [kubeedge/edgemesh#529]
**What would you like to be added/modified**:

**Why is this needed**:

Currently, Edgemesh supports adding filter tags to k8s services. But our scenario is that there are many places to create services on the cloud, and there is no guarantee that filter tags will be added to all places. Additionally, some cloud services are deployed before installing Edgemesh.Can  supporting a function that will only be proxied if the tag is added?

**Comment by Poorunga** [comment]
@JiaweiGithub  A exists feature, you can refer to https://github.com/kubeedge/edgemesh/blob/main/pkg/apis/config/v1alpha1/types.go#L175

**Comment by JiaweiGithub** [comment]
> @JiaweiGithub A exists feature, you can refer to https://github.com/kubeedge/edgemesh/blob/main/pkg/apis/config/v1alpha1/types.go#L175

Thanks
