### ISSUE TITLE
Failed to ensure portal" err="can't open node port for

### ISSUE THREAD

**Issue by nihaoliushuai** [kubeedge/edgemesh#530]
![image](https://github.com/kubeedge/edgemesh/assets/125954716/0b8a7a68-18e1-4315-a7dd-11b3f553ccdb)
在云端节点运行的edgemesh-agent会报这个错误cloudcore端口占用错误，其他edge节点正常，不清楚是什么原因，应该找怎么解决呢
k8s版本：1.23.10
kubeedge版本：keadm-v1.13.3
edgemesh版本：1.14

**Comment by Poorunga** [comment]
@nihaoliushuai  edgemesh会代理所有service，包括nodeport。cloudcore也有一个nodePort类型的service，可以过滤掉。
参考https://zhuanlan.zhihu.com/p/585749690，问题8
