### ISSUE TITLE
edgemesh跨边云通信案例出现问题

### ISSUE THREAD

**Issue by xingxingna** [kubeedge/edgemesh#537]
**What happened**:
I had a problem with edgeMesh cross-cloud communication, and this example is very important for me to build sedna later
This problem has been bothering me for a long time,/etc/resolv.conf does not have nameserver 169.254.96.16 in the content,How to solve this,What does /etc/resolv.conf mean in pod? I checked the nameserver in this file, I set the DNS address 8.8.8.8 when I started to set the static IP in the cluster, what is the relationship between this and the nameserver?
And when I install degemesh, I follow the tutorial on the official website to manually install without specifying a specific version, is it also related to this?
Most of the information I looked up online is obscure, and I really hope that I can solve it and communicate successfully.
Here's how I deployed
![image](https://github.com/kubeedge/edgemesh/assets/143973588/22469e7e-4e40-4222-9016-910bd90a65e0)
![image](https://github.com/kubeedge/edgemesh/assets/143973588/73daef43-5764-4b5b-a0a8-7c39a84c6025)
Now I want to do edge cloud communication
![image](https://github.com/kubeedge/edgemesh/assets/143973588/3636fcbc-8fee-440f-b69b-fb32b66dcbdf)
Problem occurred
1.  kubectl logs edgemesh-agent-7dv67 -n kubeedge
![image](https://github.com/kubeedge/edgemesh/assets/143973588/67163afe-f73e-4db5-b7ea-f6842751af66)
2. kubectl logs edgemesh-agent-hprkd  -n kubeedge
![image](https://github.com/kubeedge/edgemesh/assets/143973588/1dc761f3-d666-45ea-a514-9825b36fff62)
3. kubectl logs edgemesh-agent-hr8td  -n kubeedge
![image](https://github.com/kubeedge/edgemesh/assets/143973588/8a441ee6-701c-48d0-9e93-a900c0a1002e)
4.vi build/agent/resources/04-configmap.yaml
Here the psk is self-generated, and I write all the nodes in the cluster to relayNodes
![image](https://github.com/kubeedge/edgemesh/assets/143973588/d0a87b85-eba0-412b-b103-6dc059582fb0)
5. cat /etc/resolv.conf 
![image](https://github.com/kubeedge/edgemesh/assets/143973588/561c243d-8579-413f-90a5-e8c105d1c972)
6. Cluster IP also does not work
![image](https://github.com/kubeedge/edgemesh/assets/143973588/b26665cf-b9b0-4ced-ab15-d6ccab614fb4)

**What you expected to happen**:
I'd very much like I'll be able to go through the example of cross-cloud edge communication
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version:
- 1.13.+
- Kubernetes version (use `kubectl version`):
- 
![image](https://github.com/kubeedge/edgemesh/assets/143973588/42981651-b372-447c-a346-13e1309ea54e)

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- 
![image](https://github.com/kubeedge/edgemesh/assets/143973588/27a6e41f-9a0a-4a1b-83a3-6454a5ae4a90)

- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by xingxingna** [comment]
虽然问题已解决但困扰了很长时间，文档太简略且复杂

**Comment by biao-lvwan** [comment]
可以看下配置嘛，我配置了edgemesh-gateway也是这样，还有中继一点要填外网嘛，如果内网，是不是可以就不填了
