### ISSUE TITLE
Helm install  edgemesh-gateway error

### ISSUE THREAD

**Issue by JiaweiGithub** [kubeedge/edgemesh#541]
**What happened**:
Installation failed according to official documentation
![image](https://github.com/kubeedge/edgemesh/assets/8078735/4ded5796-0179-4df5-ad8a-2b1d12270106)

![image](https://github.com/kubeedge/edgemesh/assets/8078735/c7e8f2dc-aad2-4b3d-b315-2b0c78be51b5)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I looked at the source code and when I added the -- set nodeName=masternode parameter, the installation succeeded. But I don't understand why there is a nodeName, and we still need to configure relayNodes. What is the use of relayNodes in the gateway?

**Environment**:
- EdgeMesh version:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
The nodeName parameter is only used to specify the k8s node deployed by edgemesh-gateway.
