### ISSUE TITLE
EdgeMesh communication with cloudcore and edgecore

### ISSUE THREAD

**Issue by SherlockShemol** [kubeedge/edgemesh#555]
为了表达清楚我的问题，我先用中文陈述一遍。
按照[这里](https://github.com/kubeedge/kubeedge/issues/5447)所说的，实际上我建立了一个使用EdgeMesh作为CNI的KubeEdge云边通信方式。此时如果我在Cloudhub只启动QUIC server,请问是不是quic包是按照下图的路径传输的（打叉的地方因为没有安装CNI plugin所以没办法通过）？
![image](https://github.com/kubeedge/kubeedge/assets/87739402/8ce06197-b577-42a3-9e23-c66005aae42d)

As stated [here](https://github.com/kubeedge/kubeedge/issues/5447), I actually built a KubeEdge cloud-edge communication method using EdgeMesh as CNI. At this time, if I only start the QUIC server in Cloudhub, is the quic package transmitted according to the path in the figure below (the crossed area cannot be passed because the CNI plugin is not installed)?
![image](https://github.com/kubeedge/kubeedge/assets/87739402/8ce06197-b577-42a3-9e23-c66005aae42d)

**Comment by SherlockShemol** [comment]
> @SherlockShemol 你好，是这样的，edgecore和cloudcore之间的连接，不依赖edgemesh。 edgemesh仅是kubeedge的插件，不影响kubeedge使用，是个可选的安装项

那请问就算我安装了edgemesh,数据也只会从打叉的地方传输吗？

**Comment by Poorunga** [comment]
>那请问就算我安装了edgemesh,数据也只会从打叉的地方传输吗？

是的。只有部署在节点的pod，并且有个service暴露服务，访问此service的域名或clusterIP，才会走edgemesh
