### ISSUE TITLE
Case "HTTPS GateWay": use "curl -k" is enough without  key file

### ISSUE THREAD

**Issue by muxuelan** [kubeedge/edgemesh#6]
**What happened**:
Using “curl -k https://ip:port” without certificate file is enough to access the service.
![image](https://user-images.githubusercontent.com/71764707/120638601-eaebcc80-c4a2-11eb-9aaf-19897de069a0.png)

**What you expected to happen**:
When gateway is mode " https", accessing the service must carrying certificate files

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Test procedure:
1）create a test key file：
![image](https://user-images.githubusercontent.com/71764707/120638850-40c07480-c4a3-11eb-9392-675f42547bcf.png)
2）create a 'Secret' according to the key file:
![image](https://user-images.githubusercontent.com/71764707/120638889-4fa72700-c4a3-11eb-8d06-38aa725b973e.png)
![image](https://user-images.githubusercontent.com/71764707/120638773-25556980-c4a3-11eb-8079-ecadaf50c3b3.png)
3)create 'Gateway' and 'VirtualService' 
cat gateway.yaml:
![image](https://user-images.githubusercontent.com/71764707/120638529-cd1e6780-c4a2-11eb-9c99-453ba58571d3.png)

**Environment**:
- EdgeMesh version:  release-1.7
- Kubernetes version (use `kubectl version`):  Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): cloudcore: release-1.7, edgecore: release-1.7
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
Thanks for raising this issue. This problem may be a bug, we are locating now.

**Comment by muxuelan** [comment]
Done
