### ISSUE TITLE
'Gateway' doesn't work once EdgeMesh-Ingress-Gateway is deployley firstly 

### ISSUE THREAD

**Issue by muxuelan** [kubeedge/edgemesh#7]
**What happened**:
Gateway works:
1) Create new 'Gateway' and 'VirtualService'
2) Deploy edgemesh-gateway
![image](https://user-images.githubusercontent.com/71764707/120641488-3bb0f480-c4a6-11eb-89c7-27beebd63050.png)

Gateway  fails:
1) Deploy edgemesh-gateway
2) Create new 'Gateway' and 'VirtualService'
![image](https://user-images.githubusercontent.com/71764707/120641930-d3164780-c4a6-11eb-82a2-15656292c101.png)

**What you expected to happen**:
Once edgemesh-gateway is running， 'Gateway' and 'VirtualService' created later will always work.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version:release-1.7
- Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}  

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):cloudcore: release-1.7, edgecore: release-1.7
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by muxuelan** [comment]
The issus is similar to kubeedge/kubeedge#2769
The solution can refers to kubeedge/kubeedge#2811

**Comment by muxuelan** [comment]
The issus is similar to kubeedge/kubeedge#2769
The solution can refers to kubeedge/kubeedge#2811

**Comment by Poorunga** [comment]
@fisherxu Please consider merge this pr: https://github.com/kubeedge/kubeedge/pull/2811

**Comment by muxuelan** [comment]
Done
