### ISSUE TITLE
edgemesh-agent-cloud cannnot work nomally

### ISSUE THREAD

**Issue by siguoyicl** [kubeedge/edgemesh#82]
**What happened**:
when I deploy edgemesh follow the README, the daemonset.app of edgemesh-agent-cloud cannot work normally. It shows DESIRED 0， it is different from README.

**What you expected to happen**:
edgemesh-agent-cloud work nomally
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version: v1.8.0
- Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:13:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.8.0
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`): vmware
    - OS (e.g. `cat /etc/os-release`): centos 7.9
    - Kernel (e.g. `uname -a`): Linux ke-cloud 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by Poorunga** [comment]
Please check the node taint-and-toleration, you can refer to https://kubernetes.io/zh/docs/concepts/scheduling-eviction/taint-and-toleration/.

**Comment by Poorunga** [comment]
@lynxcat Have you encountered the same problem and can you provide your solution?

**Comment by siguoyicl** [comment]
@Poorunga I deployed edgemesh-agent-edge as well as edgemesh-agent-cloud, it work normally. So I do not know where is the problem.

**Comment by lynxcat** [comment]
@siguoyicl You can try to check whether this file ( "edgemesh/build/agent/kubernetes/edgemesh-agent/06-configmap-cloud.yaml") is consistent with your local virtual bridge. the default value of configmap-cloud is cni0.

**Comment by siguoyicl** [comment]
@Poorunga @lynxcat According to my understanding, edgemesh-agent-cloud should run on cloud nodes and edgemesh-agent-edge should run on edge nodes. Am I right? It seems impossible to schedule edgemesh-agent-cloud to cloud nodes

**Comment by Poorunga** [comment]
@siguoyicl Yes, you are right.

DESIRED 0 represents that K8s believes that no node is worth scheduling. Are your cloud nodes normal, or they are tainted?

**Comment by siguoyicl** [comment]
@Poorunga In my condition, I have a cloud node called ke-cloud, two edge nodes called  ke-edge1 and ke-edge2, now edgemesh-agent-edge has scheduled to edge nodes successfully, edgemesh-agent-cloud cannot be scheduled normally. I have confirmed that the Taints of cloud node is **node-role.kubernetes.io/master:NoSchedule**, so whether this is the cause of this problem.

**Comment by Poorunga** [comment]
If ke-cloud is a K8s master node, you need remove it's taint.

You can try `kubectl taint node ke-cloud node-role.kubernetes.io/master-`

**Comment by siguoyicl** [comment]
@Poorunga Problem solved, thanks. I have a suggestion that maybe this detail can be added into README.

**Comment by siguoyicl** [comment]
edgemesh-agent-cloud has scheduled to cloud node successfully by remove cloud node‘s taint

**Comment by Poorunga** [comment]
OK
