### ISSUE TITLE
Deploying edgemesh failed

### ISSUE THREAD

**Issue by blackdobb** [kubeedge/edgemesh#9]
**What happened**:

I deployed edgeMesh following the readme, but it doesn’t seem to work
I prepared two nodes, a master node and an edge node.
I run a Pod on the edge node, and the yaml files of the pod and service are as follows:
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  labels:
    app: edge-nginx
spec:
  containers:
    - image: nginx
      name: hello
      ports:
        - containerPort: 9376
          hostPort: 9376
  nodeSelector:
    type: dao-48-21
  tolerations:
    - effect: PreferNoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
    - effect: NoSchedule
      key: dec.daocloud.io/edge
      operator: Equal
      value: dao-48-21
---
apiVersion: v1
kind: Service
metadata:
  name: edge-nginx
  namespace: default
spec:
  ports:
    - name: http-0
      port: 18080
      protocol: TCP
      targetPort: 9376
  selector:
    app: edge-nginx
  clusterIP: None  

```
NAME                        READY   STATUS    RESTARTS   AGE   IP            NODE        NOMINATED NODE   READINESS GATES
pod-b                       1/1     Running   0          39h   172.17.0.2    dao-48-21   <none>           <none>
```  

```
NAME         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE    SELECTOR
edge-nginx   ClusterIP   None             <none>        18080/TCP        39h    app=edge-nginx
```  

```
NAME         ENDPOINTS         AGE
edge-nginx   172.17.0.2:9376   39h
```  

I successfully performed the following operations at the edge node:  

```
nano@nano-desktop:~$ curl 172.17.0.2
<!DOCTYPE html>
<html>
···
</body>
</html>
```  

But when I try to connect through the domain name, it fails：  

```
nano@nano-desktop:~$ curl http://edge-nginx.default.svc.cluster.local:9376curl: (6) Could not resolve host: edge-nginx.default.svc.cluster.local  
```

**What you expected to happen**:
I want to get the Nginx response

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EdgeMesh version: 
- Kubernetes version (use `kubectl version`):  
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}  
```
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):  

`KubeEdge v1.6.0-beta.0.182+beed66d71625f5`  

- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):  
   
  `edgecore --version: command not found`  

    - Hardware configuration (e.g. `lscpu`):
    - OS (e.g. `cat /etc/os-release`):
    - Kernel (e.g. `uname -a`):
    - Go version (e.g. `go version`):
    - Others:

  </details>

**Comment by blackdobb** [comment]
This is my logs:
6月 05 14:16:43 nano-desktop systemd[1]: Started edgecore.service.
6月 05 14:16:47 nano-desktop edgecore[3987]: INFO: Install client plugin, protocol: rest
6月 05 14:16:47 nano-desktop edgecore[3987]: INFO: Installed service discovery plugin: edge
6月 05 14:16:47 nano-desktop edgecore[3987]: I0605 14:16:47.390284    3987 server.go:72] Version: v1.6.1
6月 05 14:16:47 nano-desktop edgecore[3987]: I0605 14:16:47.431612    3987 sql.go:21] Begin to register twin db model
6月 05 14:16:47 nano-desktop edgecore[3987]: I0605 14:16:47.436529    3987 module.go:34] Module twin registered successfully
6月 05 14:16:47 nano-desktop edgecore[3987]: I0605 14:16:47.469099    3987 client.go:77] Connecting to docker on unix:///var/run/docker.sock
6月 05 14:16:47 nano-desktop edgecore[3987]: I0605 14:16:47.469178    3987 client.go:94] Start docker client with request timeout=0s
6月 05 14:16:50 nano-desktop edgecore[3987]: I0605 14:16:50.590644    3987 docker_service.go:241] Hairpin mode set to "hairpin-veth"
6月 05 14:16:50 nano-desktop edgecore[3987]: W0605 14:16:50.590923    3987 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
6月 05 14:16:50 nano-desktop edgecore[3987]: W0605 14:16:50.599559    3987 hostport_manager.go:71] The binary conntrack is not installed, this can cause failures in network connection cl
6月 05 14:16:50 nano-desktop edgecore[3987]: W0605 14:16:50.599642    3987 hostport_manager.go:71] The binary conntrack is not installed, this can cause failures in network connection cl
6月 05 14:16:50 nano-desktop edgecore[3987]: I0605 14:16:50.603220    3987 docker_service.go:256] Docker cri networking managed by kubernetes.io/no-op
6月 05 14:16:50 nano-desktop edgecore[3987]: I0605 14:16:50.631747    3987 docker_service.go:261] Docker Info: &{ID:7LMS:I5Y4:SYN7:GTYF:QK3P:S4YO:R47H:VVXY:AGVA:NPHW:LEZ7:ZAE4 Containers
6月 05 14:16:50 nano-desktop edgecore[3987]: I0605 14:16:50.631993    3987 docker_service.go:274] Setting cgroupDriver to cgroupfs
6月 05 14:16:50 nano-desktop edgecore[3987]: I0605 14:16:50.639920    3987 edged.go:522] RemoteRuntimeEndpoint: "unix:///var/run/dockershim.sock", remoteImageEndpoint: "unix:///var/run/d
6月 05 14:16:50 nano-desktop edgecore[3987]: I0605 14:16:50.640012    3987 edged.go:525] Starting the GRPC server for the docker CRI shim.
6月 05 14:16:50 nano-desktop edgecore[3987]: I0605 14:16:50.690231    3987 remote_runtime.go:59] parsed scheme: ""
6月 05 14:16:50 nano-desktop edgecore[3987]: I0605 14:16:50.690285    3987 remote_runtime.go:59] scheme "" not registered, fallback to default scheme
6月 05 14:16:50 nano-desktop edgecore[3987]: I0605 14:16:50.690392    3987 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/dockershim.sock  <nil> 0 <nil>}] <nil>
6月 05 14:16:50 nano-desktop edgecore[3987]: I0605 14:16:50.690425    3987 clientconn.go:948] ClientConn switching balancer to "pick_first"
6月 05 14:16:50 nano-desktop edgecore[3987]: I0605 14:16:50.690881    3987 remote_image.go:50] parsed scheme: ""
6月 05 14:16:50 nano-desktop edgecore[3987]: I0605 14:16:50.690911    3987 remote_image.go:50] scheme "" not registered, fallback to default scheme
6月 05 14:16:50 nano-desktop edgecore[3987]: I0605 14:16:50.691065    3987 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/dockershim.sock  <nil> 0 <nil>}] <nil>
6月 05 14:16:50 nano-desktop edgecore[3987]: I0605 14:16:50.691090    3987 clientconn.go:948] ClientConn switching balancer to "pick_first"
6月 05 14:16:50 nano-desktop edgecore[3987]: W0605 14:16:50.840035    3987 nvidia.go:61] NVIDIA GPU metrics will not be available: Could not initialize NVML: could not load NVML library
6月 05 14:16:50 nano-desktop edgecore[3987]: W0605 14:16:50.844349    3987 sysinfo.go:203] Nodes topology is not available, providing CPU topology

**Comment by Poorunga** [comment]
EdgeMesh needs a cluster ip for each service, you can try to remove `cluserIP: None` and try again. :)

**Comment by blackdobb** [comment]
> EdgeMesh needs a cluster ip for each service, you can try to remove `cluserIP: None` and try again. :)
I removed it, but on the edge side, the response just like the same:  

```
nano@nano-desktop:~$ curl edge-nginx.default.svc.cluster.local：18080
curl: (6) Could not resolve host: edge-nginx.default.svc.cluster.local:18080  
```  

if I curl the Ip+port, it will be like:  

```
nano@nano-desktop:~$ curl 10.107.71.152:18080
curl: (7) Failed to connect to 10.107.71.152 port 18080: Connection timed out
```  

the svc as follows:
[root@master-7-1 tmp]# kubectl get svc
NAME         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
edge-nginx   ClusterIP   10.107.71.152    <none>        18080/TCP        4m32s

**Comment by Poorunga** [comment]
Can you provide edgemesh log information? You can use the following command:
```
docker logs <edgemesh_container_id>
```

**Comment by blackdobb** [comment]
> Can you provide edgemesh log information? You can use the following command:
> 
> ```
> docker logs <edgemesh_container_id>
> ```

I just checked the containers running on the edge side. there is no edgemesh, I thought there must be something wrong on the deploy part. How could i deploy the edgeMesh. So far, i just following the steps on the readMe, but I blocked in the Test Case. Other steps went well.

These are containers on the edge node:  

```
nano@nano-desktop:~$ sudo docker ps -a
CONTAINER ID        IMAGE                                                           COMMAND                  CREATED             STATUS              PORTS                    NAMES
e04857b0fefd        nginx                                                           "/docker-entrypoint.…"   3 hours ago         Up 3 hours                                   k8s_hello_pod-b_default_27060508-4a34-4677-935b-aabc38066d55_0
eb4f0cedf861        registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.1   "/pause"                 3 hours ago         Up 3 hours          0.0.0.0:9376->9376/tcp   k8s_POD_pod-b_default_27060508-4a34-4677-935b-aabc38066d55_0
3d1bf07ba76e        registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.1   "/pause"                 2 days ago          Up 2 days                                    k8s_POD_6-4-222-776f8749f9-nj96t_dec-public_d367044c-c28c-4f4d-b680-ccb1c09f1c57_0
```  
Only the first container has logs, showing like:  

```
nano@nano-desktop:~$ sudo docker logs e04857b0fefd
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2021/06/09 06:08:59 [notice] 1#1: using the "epoll" event method
2021/06/09 06:08:59 [notice] 1#1: nginx/1.21.0
2021/06/09 06:08:59 [notice] 1#1: built by gcc 8.3.0 (Debian 8.3.0-6)
2021/06/09 06:08:59 [notice] 1#1: OS: Linux 4.9.201-tegra
2021/06/09 06:08:59 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/06/09 06:08:59 [notice] 1#1: start worker processes
2021/06/09 06:08:59 [notice] 1#1: start worker process 30
2021/06/09 06:08:59 [notice] 1#1: start worker process 31
2021/06/09 06:08:59 [notice] 1#1: start worker process 32
2021/06/09 06:08:59 [notice] 1#1: start worker process 33
172.17.0.1 - - [09/Jun/2021:06:09:34 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.58.0" "-"
```  

These are the containers on the master node:  
```
[root@master-7-1 ~]# docker ps
CONTAINER ID   IMAGE                                                           COMMAND                  CREATED       STATUS       PORTS     NAMES
ce51932b65c5   bfe3a36ebd25                                                    "/coredns -conf /etc…"   3 weeks ago   Up 3 weeks             k8s_coredns_coredns-54d67798b7-4dmsv_kube-system_cc00a1a0-8ff9-4737-ae45-e17916a72f62_4
acb04b0047e5   bfe3a36ebd25                                                    "/coredns -conf /etc…"   3 weeks ago   Up 3 weeks             k8s_coredns_coredns-54d67798b7-rd2qk_kube-system_8e12b4f2-6cf5-49e2-b035-c7c8ced75966_4
eba26b5121ca   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2   "/pause"                 3 weeks ago   Up 3 weeks             k8s_POD_coredns-54d67798b7-4dmsv_kube-system_cc00a1a0-8ff9-4737-ae45-e17916a72f62_42
04256a48fd25   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2   "/pause"                 3 weeks ago   Up 3 weeks             k8s_POD_coredns-54d67798b7-rd2qk_kube-system_8e12b4f2-6cf5-49e2-b035-c7c8ced75966_41
691a09503670   f03a23d55e57                                                    "/opt/bin/flanneld -…"   3 weeks ago   Up 3 weeks             k8s_kube-flannel_kube-flannel-ds-4lq47_kube-system_6fc6e837-2cd2-4a08-8cf1-dda846337b3a_1
54db8e4f11f9   10cc881966cf                                                    "/usr/local/bin/kube…"   3 weeks ago   Up 3 weeks             k8s_kube-proxy_kube-proxy-vtfpd_kube-system_94cb9487-89a1-4807-9383-7573877a40fe_3
22c590ef4d5c   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2   "/pause"                 3 weeks ago   Up 3 weeks             k8s_POD_kube-flannel-ds-4lq47_kube-system_6fc6e837-2cd2-4a08-8cf1-dda846337b3a_1
2bfb829f6ae9   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2   "/pause"                 3 weeks ago   Up 3 weeks             k8s_POD_kube-proxy-vtfpd_kube-system_94cb9487-89a1-4807-9383-7573877a40fe_3
11f84d9a2a9f   b9fa1895dcaa                                                    "kube-controller-man…"   3 weeks ago   Up 3 weeks             k8s_kube-controller-manager_kube-controller-manager-master-7-1_kube-system_e1bb2575f5fda387e140503b11e8dd6d_12
76a5f9bdad0d   3138b6e3d471                                                    "kube-scheduler --au…"   3 weeks ago   Up 3 weeks             k8s_kube-scheduler_kube-scheduler-master-7-1_kube-system_2e62181f8c3bdfba24fafa896c76b6a7_13
128e07279e91   ca9843d3b545                                                    "kube-apiserver --ad…"   3 weeks ago   Up 3 weeks             k8s_kube-apiserver_kube-apiserver-master-7-1_kube-system_2d442416c8a90d560a780513d7a89cc6_5
45b6320b2b49   0369cf4303ff                                                    "etcd --advertise-cl…"   3 weeks ago   Up 3 weeks             k8s_etcd_etcd-master-7-1_kube-system_afeaffefb497c873ee1bb4b47d43b7fd_4
ffd178139be2   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2   "/pause"                 3 weeks ago   Up 3 weeks             k8s_POD_kube-scheduler-master-7-1_kube-system_2e62181f8c3bdfba24fafa896c76b6a7_3
8374e216cb6d   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2   "/pause"                 3 weeks ago   Up 3 weeks             k8s_POD_kube-controller-manager-master-7-1_kube-system_e1bb2575f5fda387e140503b11e8dd6d_3
e61e2e7f31b0   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2   "/pause"                 3 weeks ago   Up 3 weeks             k8s_POD_kube-apiserver-master-7-1_kube-system_2d442416c8a90d560a780513d7a89cc6_4
52557afdbcbb   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2   "/pause"                 3 weeks ago   Up 3 weeks             k8s_POD_etcd-master-7-1_kube-system_afeaffefb497c873ee1bb4b47d43b7fd_3
```

**Comment by Poorunga** [comment]
EdgeMesh is created using `DaemonSet`, and each edge node is deployed one. Try it with the following command:
```
# Please set the subNet to the value of service-cluster-ip-range of kube-apiserver.
# You can obtain the value from the /etc/kubernetes/manifests/kube-apiserver.yaml file on the master node
$ kubectl apply -f build/kubernetes/edgemesh/03-configmap.yaml
configmap/edgemesh-cfg created
$ kubectl apply -f build/kubernetes/edgemesh/04-daemonset.yaml
daemonset.apps/edgemesh created
```
You can use the `kubectl get all -n kubeedge` to check whether edgemesh is deployed successfully. **If the deployment fails, please tell me what went wrong.**

**Comment by blackdobb** [comment]
> EdgeMesh is created using `DaemonSet`, and each edge node is deployed one. Try it with the following command:
> 
> ```
> # Please set the subNet to the value of service-cluster-ip-range of kube-apiserver.
> # You can obtain the value from the /etc/kubernetes/manifests/kube-apiserver.yaml file on the master node
> $ kubectl apply -f build/kubernetes/edgemesh/03-configmap.yaml
> configmap/edgemesh-cfg created
> $ kubectl apply -f build/kubernetes/edgemesh/04-daemonset.yaml
> daemonset.apps/edgemesh created
> ```
> 
> You can use the `kubectl get all -n kubeedge` to check whether edgemesh is deployed successfully. **If the deployment fails, please tell me what went wrong.**

Yeap, Of cause I have do it on the master node, and it show me `configmap/edgemesh-cfg created` `daemonset.apps/edgemesh created`.
when i do `kubectl get all -n kubeedge` , there is a daemonset:   

```
NAME                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/edgemesh   0         0         0       0            0           <none>          2d21h
```

I don't know what's going on

**Comment by khalid-davis** [comment]
The "DESIRED" is zero in the damonset.apps/edgemesh, which indicates that no proper node can be used to deploy the pod. You need to check the node label and daemonset selector or affinity.

**Comment by blackdobb** [comment]
> The "DESIRED" is zero in the damonset.apps/edgemesh, which indicates that no proper node can be used to deploy the pod. You need to check the node label and daemonset selector or affinity.

Thank you so much, but I just fix it,  it still not work. There are two damonset pod running on the edge nodes are Error  

```
[root@master-7-1 tmp]# kubectl get po -n kubeedge
NAME                             READY   STATUS    RESTARTS   AGE
admission-56546d88f6-dt8qz   1/1     Running   0          23d
backend-55d79fd59d-4w475     1/1     Running   0          6h25m
frontend-5c96c5549c-rxx9t    1/1     Running   0          3d3h
manual-6f8599784f-whpmd      1/1     Running   0          3d6h
mysql57-6786c8c978-t9mbw     1/1     Running   1          48d
edgemesh-4z64b                   1/1     Running   0          40m
edgemesh-gvmgt                   1/1     Running   0          40m
edgemesh-ngh4l                   1/1     Running   0          40m
edgemesh-sj7jw                   0/1     Error     11         40m
edgemesh-zn46f                   0/1     Error     10         40m
```  
This is the log of these two pod:  
```
[root@master-7-1 tmp]# kubectl logs edgemesh-zn46f -n kubeedge
standard_init_linux.go:211: exec user process caused "exec format error"  
```  

The daemonset details as follow:  

```
NAME                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/edgemesh   5         5         3       5            3           <none>          40m
```  

```
[root@master-7-1 tmp]# kubectl describe daemonset.apps/edgemesh -n kubeedge
Name:           edgemesh
Selector:       k8s-app=kubeedge,kubeedge=edgemesh
Node-Selector:  <none>
Labels:         k8s-app=kubeedge
                kubeedge=edgemesh
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 5
Current Number of Nodes Scheduled: 5
Number of Nodes Scheduled with Up-to-date Pods: 5
Number of Nodes Scheduled with Available Pods: 3
Number of Nodes Misscheduled: 0
Pods Status:  5 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  k8s-app=kubeedge
           kubeedge=edgemesh
  Containers:
   edgemesh:
    Image:      poorunga/edgemesh:0.1
    Port:       <none>
    Host Port:  <none>
    Limits:
      cpu:     200m
      memory:  256Mi
    Requests:
      cpu:        100m
      memory:     128Mi
    Environment:  <none>
    Mounts:
      /etc/kubeedge/config from conf (rw)
      /etc/resolv.conf from resolv (rw)
  Volumes:
   conf:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      edgemesh-cfg
    Optional:  false
   resolv:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/resolv.conf
    HostPathType:
Events:
  Type    Reason            Age   From                  Message
  ----    ------            ----  ----                  -------
  Normal  SuccessfulCreate  42m   daemonset-controller  Created pod: edgemesh-4z64b
  Normal  SuccessfulCreate  42m   daemonset-controller  Created pod: edgemesh-gvmgt
  Normal  SuccessfulCreate  42m   daemonset-controller  Created pod: edgemesh-zn46f
  Normal  SuccessfulCreate  42m   daemonset-controller  Created pod: edgemesh-ngh4l
  Normal  SuccessfulCreate  42m   daemonset-controller  Created pod: edgemesh-sj7jw
```

I'm sry for lots of doubts, I'm a fresh man on kubeedge

**Comment by Poorunga** [comment]
Are the two machines not of amd64 architecture?

By the way, you can do what you want on a machine where edgemesh is already running. :)

**Comment by blackdobb** [comment]
> Are the two machines not of amd64 architecture?
> 
> By the way, you can do what you want on a machine where edgemesh is already running. :)

no it's arm64,Ubuntu 18.04.5 LTS, but the other nodes are not the edge nodes I need, they are all CentOS

**Comment by Poorunga** [comment]
Maybe you need to check daemonset selector or affinity, ensure that edgemesh only runs on edge nodes.

**Comment by blackdobb** [comment]
> only

The machine on my edge side is arm64. I just checked the images "poorunga/edgemesh" , it looks like only support Linux/Amd64 but arm64. Is there other way to deploy edgemesh

**Comment by blackdobb** [comment]
> only

The machine on my edge side is arm64. I just checked the images "poorunga/edgemesh" , it looks like only support Linux/Amd64 but arm64. Is there other way to deploy edgemesh

**Comment by Poorunga** [comment]
Sorry, this is a shortcoming in our work. We will provide you with a image of kubeedge/edgemesh_arm64:v1.7.0 soon. :)

**Comment by blackdobb** [comment]
> /cc @fisherxu

Thanks for your patience ! Well Done
