### ISSUE TITLE
安装edgemesh后，服务域名解析失败

### ISSUE THREAD

**Issue by 18664599806** [kubeedge/edgemesh#90]
**What happened**:
安装edgemesh后，在中心集群的节点上POD内无法解析域名（使用服务的Cluster-IP可正常访问服务）
**What you expected to happen**:
在中心集群的节点上POD内能正常解析域名
**How to reproduce it (as minimally and precisely as possible)**:
正常安装edgemesh后，出现此现象
**Anything else we need to know?**:

**Environment**:
- EdgeMesh version:  kubeedge/edgemesh-agent:latest
- Kubernetes version (use `kubectl version`): 1.21.3
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.7.2
- <details><summary>Cloud nodes Environment:</summary>

    - Hardware configuration (e.g. `lscpu`):
    - Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              56
On-line CPU(s) list: 0-55
Thread(s) per core:  2
Core(s) per socket:  14
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
Stepping:            4
CPU MHz:             3307.946
BogoMIPS:            5200.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            19712K
NUMA node0 CPU(s):   0-13,28-41
NUMA node1 CPU(s):   14-27,42-55

    - OS (e.g. `cat /etc/os-release`): 
   NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"

    - Kernel (e.g. `uname -a`):
Linux controller04 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
    - Go version (e.g. `go version`):
go version go1.14.4 linux/amd64
    - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

    - edgecore version (e.g. `edgecore --version`):
KubeEdge v1.7.2
    - Hardware configuration (e.g. `lscpu`):
 Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              64
    - OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"

    - Kernel (e.g. `uname -a`):
Linux infer-1 4.15.0-156-generic #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
    - Go version (e.g. `go version`):

    - Others:

  </details>

**Comment by Poorunga** [comment]
云上的edgemesh-agent一般会关闭edgedns模块。
你可以先检查一下在不启动edgemesh的时候，pod内域名解析是否正常。

**Comment by Poorunga** [comment]
云上的edgemesh-agent一般会关闭edgedns模块。
你可以先检查一下在不启动edgemesh的时候，pod内域名解析是否正常。

**Comment by 18664599806** [comment]
在部署edgemesh之前，确认域名解析是正常的。 因为是刚重新安装的环境，重新安装的原因是之前有个NPU节点的ascend-device-plugin访问kubernetes的服务有问题，重新安装后解决。有专门确认域名访问正常。

**Comment by Poorunga** [comment]
好的，可否使用 `kubectl get all -n kubeedge` 看一下edgemesh的部署情况？

**Comment by 18664599806** [comment]
问题已解决，跟edgemesh-agent的ConfigMap中的配置相关。
问题原因：本集群使用的K8S网络插件式calico，POD IP是通过calico创建的网桥接口tunl0分配IP，但06-configmap-cloud.yaml中配置的listenInterface项使用的docker0.  

修复措施：
1. 修改配置：kubectl edit cm edgemesh-agent-cloud-cfg -n kubeedge，修改其中的listenInterface配置项为tunl0接口（使用POD实际分配IP的接口）
2. 重启edgemesh-agent
删除agent：kubectl  delete -f build/agent/kubernetes/edgemesh-agent/07-daemonset-cloud.yaml
重新创建agent：kubectl apply -f build/agent/kubernetes/edgemesh-agent/07-daemonset-cloud.yaml
3. 等待恢复正常即可。

**Comment by Poorunga** [comment]
good
