### ISSUE TITLE
the edge's ​list-watch can't get destinationrule

### ISSUE THREAD

**Issue by lynxcat** [kubeedge/edgemesh#93]
edge log:   
![image](https://user-images.githubusercontent.com/2222701/133879322-7b647369-2098-4c62-bb9f-2e36a8361589.png)
list-watch can't get DestinationRule

Cloud:  
![image](https://user-images.githubusercontent.com/2222701/133879358-7530833a-6c91-433d-a828-e3ed2c4881d9.png)

**Environment**:
- EdgeMesh version: 1.8
- Kubernetes version : v1.20.4
- KubeEdge version: 1.7.2(run in container)

**Comment by Poorunga** [comment]
Can you successfully obtain data on the edge node by `curl http://localhost:8080/apis/networking.istio.io/v1alpha3/destinationrules`?

**Comment by lynxcat** [comment]
No, no data can be obtained at the edge. 
```
[root@node-2 1.7.2]# curl http://localhost:10550/apis/networking.istio.io/v1alpha3/DestinationRule
{"apiVersion":"networking.istio.io/v1alpha3","items":[],"kind":"DestinationRuleList","metadata":{"selfLink":"/apis/networking.istio.io/v1alpha3/DestinationRule"}}
```
it is success in the cloud and other interfaces are also success.   

```
root@node-2 1.7.2]# curl 127.0.0.1:10550/api/v1/services
{"apiVersion":"v1","items":[{"apiVersion":"v1","kind":"Service","metadata":{"creationTimestamp":"2021-09-18T02:46:32Z","labels":{"component":"apiserver","provider":"kubernetes"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:component":{},"f:provider":{}}},"f:spec":{"f:clusterIP":{},"f:ipFamilyPolicy":{},"f:ports":{".":{},"k:{\"port\":443,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:sessionAffinity":{},"f:type":{}}},"manager":"kube-apiserver","operation":"Update","time":"2021-09-18T02:46:32Z"}],"name":"kubernetes","namespace":"default", ......
```

**Comment by lynxcat** [comment]
@Poorunga 
In the cloud, I can get data normally.

```
 curl http://127.0.0.1:8001/apis/networking.istio.io/v1alpha3/destinationrules
{"apiVersion":"networking.istio.io/v1alpha3","items":[{"apiVersion":"networking.istio.io/v1alpha3","kind":"DestinationRule","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"DestinationRule\",\"metadata\":{\"annotations\":{},\"name\":\"hostname-lb-svc\",\"namespace\":\"default\"},\"spec\":{\"host\":\"hostname-lb-svc\",\"trafficPolicy\":{\"loadBalancer\":{\"simple\":\"ROUND_ROBIN\"}}}}\n"},"creationTimestamp":"2021-09-18T06:35:30Z","generation":1,"managedFields":[{"apiVersion":"networking.istio.io/v1alpha3","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{".":{},"f:host":{},"f:trafficPolicy":{".":{},"f:loadBalancer":{".":{},"f:simple":{}}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2021-09-18T06:35:30Z"}],"name":"hostname-lb-svc","namespace":"default","resourceVersion":"46750","uid":"022b8a99-df8a-4931-9e95-3ba0d474c078"},"spec":{"host":"hostname-lb-svc","trafficPolicy":{"loadBalancer":{"simple":"ROUND_ROBIN"}}}}],"kind":"DestinationRuleList","metadata":{"continue":"","resourceVersion":"76189"}}
```

**Comment by lynxcat** [comment]
The problem has been solved with the help of @Poorunga 

When we looked at the logs in the cloud, we found that the account i used did not have permissions, which led to the return of empty data.
![image](https://user-images.githubusercontent.com/2222701/134273563-91c479a7-fa43-4548-bd0a-dea6d3033def.png)


When I add the corresponding permissions to the account.

```
kubectl edit clusterrole cloudcore
----
- apiGroups:
  - networking.istio.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
```
 the Agent can work normally
![0649458f5bab6721c9f49976f6402bf](https://user-images.githubusercontent.com/2222701/134273793-44bef821-af54-4c09-a323-f591b7a6f1b2.png)

**Comment by anirudh1626** [comment]
Hi @Poorunga , 

I am trying to integrate Edgemesh with my Kubeedge 1.20 setup on Ubuntu 22.04 image with Kubernetes version 1.30 Release.

I am facing some issues

After doing the config from the below link, the items are still empty

https://edgemesh.netlify.app/guide/edge-kube-api.html

curl http://127.0.0.1:10550/api/v1/services | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    64  100    64    0     0      6      0  0:00:10  0:00:10 --:--:--    16
{
  "apiVersion": "v1",
  "items": [],
  "kind": "ServiceList"
}

The edgemesh agent logs show the below error

2025-03-24T13:32:29.317916133Z stderr F E0324 13:32:29.317664       1 reflector.go:138] istio.io/client-go/pkg/informers/externalversions/factory.gen.go:118: Failed to watch *v1alpha3.DestinationRule: failed to list *v1alpha3.DestinationRule: no kind "DestinationruleList" is registered for version "networking.istio.io/v1alpha3" in scheme "istio.io/client-go/pkg/clientset/versioned/scheme/register.gen.go:32"

Lastly I also don't see iptables rule getting configured for Ip 169.254.96.16

It would be great if you could provide some pointers

**Comment by anirudh1626** [comment]
> Hi [@Poorunga](https://github.com/Poorunga) ,
> 
> I am trying to integrate Edgemesh with my Kubeedge 1.20 setup on Ubuntu 22.04 image with Kubernetes version 1.30 Release.
> 
> I am facing some issues
> 
> After doing the config from the below link, the items are still empty
> 
> https://edgemesh.netlify.app/guide/edge-kube-api.html
> 
> curl http://127.0.0.1:10550/api/v1/services | jq % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 100 64 100 64 0 0 6 0 0:00:10 0:00:10 --:--:-- 16 { "apiVersion": "v1", "items": [], "kind": "ServiceList" }
> 
> The edgemesh agent logs show the below error
> 
> 2025-03-24T13:32:29.317916133Z stderr F E0324 13:32:29.317664 1 reflector.go:138] istio.io/client-go/pkg/informers/externalversions/factory.gen.go:118: Failed to watch *v1alpha3.DestinationRule: failed to list *v1alpha3.DestinationRule: no kind "DestinationruleList" is registered for version "networking.istio.io/v1alpha3" in scheme "istio.io/client-go/pkg/clientset/versioned/scheme/register.gen.go:32"
> 
> Lastly I also don't see iptables rule getting configured for Ip 169.254.96.16
> 
> It would be great if you could provide some pointers

The issues got resolved, once I explicitly restarted the cloudcore pod, after which things started working
