### ISSUE TITLE
More Explicit Intro

### ISSUE THREAD

**Issue by seveirbian** [kubeedge/edgemesh#98]
**What would you like to be added/modified**:

Change "At the edge node, close edgeMesh module, open metaServer module, and restart edgecore" to "At the edge node, close edgeMesh module if it exists, open metaServer module, and restart edgecore" or some what. 
![image](https://user-images.githubusercontent.com/33503641/134947412-1f9ad02f-4982-45d0-a440-cd89a852635d.png)

**Why is this needed**:

Since the edgemesh module in edgecore has been removed, there is necessary to make the declaration more clear. 
![image](https://user-images.githubusercontent.com/33503641/134947305-98f9c960-7c51-493d-bf11-3759af41c600.png)

**Comment by Poorunga** [comment]
KubeEdge only removed this configuration in version 1.8.0, so I will change it to:

(If your KubeEdge < 1.8.0) At the edge node, close edgeMesh module, open metaServer module...
